"""
Centralized audit action identifiers.

Use these constants instead of hard-coded strings to keep audit action
taxonomy consistent across endpoints and tests.
"""


class AuditAction:
    # User/Admin exports
    USER_EXPORT = "USER_EXPORT"
    AUDIT_LOG_EXPORT = "AUDIT_LOG_EXPORT"

    # Incident report exports
    INCIDENT_REPORT_EXPORT = "INCIDENT_REPORT_EXPORT"
    INCIDENT_REPORT_EXPORT_FAILED = "INCIDENT_REPORT_EXPORT_FAILED"

    # Agency report exports
    AGENCY_REPORT_EXPORT = "AGENCY_REPORT_EXPORT"
    SCHEDULED_EXPORT_CREATED = "SCHEDULED_EXPORT_CREATED"
    SCHEDULED_EXPORT_DELETED = "SCHEDULED_EXPORT_DELETED"

    # Analytics exports
    ANALYTICS_EXPORT_SYNC = "ANALYTICS_EXPORT_SYNC"
    ANALYTICS_EXPORT_SYNC_FAILED = "ANALYTICS_EXPORT_SYNC_FAILED"
    ANALYTICS_EXPORT_REQUESTED = "ANALYTICS_EXPORT_REQUESTED"
    ANALYTICS_EXPORT_REQUEST_FAILED = "ANALYTICS_EXPORT_REQUEST_FAILED"
    ANALYTICS_EXPORT_DOWNLOADED = "ANALYTICS_EXPORT_DOWNLOADED"
    ANALYTICS_EXPORT_JOB_COMPLETED = "ANALYTICS_EXPORT_JOB_COMPLETED"
    ANALYTICS_EXPORT_JOB_FAILED = "ANALYTICS_EXPORT_JOB_FAILED"

    # Admin dashboard
    ADMIN_DASHBOARD_VIEWED = "ADMIN_DASHBOARD_VIEWED"
    ADMIN_DASHBOARD_ERROR = "ADMIN_DASHBOARD_ERROR"
    CLASSIFICATION_CACHE_WARM = "CLASSIFICATION_CACHE_WARM"
    CLASSIFICATION_CACHE_INVALIDATE = "CLASSIFICATION_CACHE_INVALIDATE"

    # Admin profile self-service
    ADMIN_PROFILE_UPDATED = "ADMIN_PROFILE_UPDATED"
    ADMIN_PASSWORD_CHANGED = "ADMIN_PASSWORD_CHANGED"

    # Account self-service, any authenticated role (manager, supervisor, parent).
    # The ADMIN_* pair above is reachable only through require_admin, so every
    # non-admin role had no audited path to change its own profile or password.
    USER_PROFILE_UPDATED = "USER_PROFILE_UPDATED"
    USER_PASSWORD_CHANGED = "USER_PASSWORD_CHANGED"
    USER_PASSWORD_CHANGE_FAILED = "USER_PASSWORD_CHANGE_FAILED"
    USER_NOTIFICATION_PREFS_UPDATED = "USER_NOTIFICATION_PREFS_UPDATED"

    # Backup operations
    BACKUP_ENQUEUED = "BACKUP_ENQUEUED"
    BACKUP_ENQUEUE_ATTEMPTED = "BACKUP_ENQUEUE_ATTEMPTED"
    BACKUP_RESTORE_ATTEMPTED = "BACKUP_RESTORE_ATTEMPTED"
    BACKUP_DELETE_ATTEMPTED = "BACKUP_DELETE_ATTEMPTED"
    BACKUP_CLEANUP_ATTEMPTED = "BACKUP_CLEANUP_ATTEMPTED"
    BACKUP_FAILED = "BACKUP_FAILED"

    # Admin password
    ADMIN_PASSWORD_CHANGE_FAILED = "ADMIN_PASSWORD_CHANGE_FAILED"

    # Kindergarten imports
    KINDERGARTEN_IMPORT = "KINDERGARTEN_IMPORT"

    # Agency reports — MOH national immunization schedule upload
    IMMUNIZATION_SCHEDULE_UPLOAD = "IMMUNIZATION_SCHEDULE_UPLOAD"

    # Alert management
    ALERT_ACKNOWLEDGED = "ALERT_ACKNOWLEDGED"

    # User lifecycle
    USER_CREATED = "USER_CREATED"
    USER_UPDATED = "USER_UPDATED"
    USER_DELETED = "USER_DELETED"
    BULK_USER_CREATE = "BULK_USER_CREATE"
    BULK_USER_DELETE = "BULK_USER_DELETE"
    BULK_STATUS_UPDATE = "BULK_STATUS_UPDATE"
    CSV_IMPORT = "CSV_IMPORT"
    CHILDREN_CREATED = "CHILDREN_CREATED"

    # Access control
    ACCESS_DENIED = "ACCESS_DENIED"
    BULK_ACCESS_DENIED = "BULK_ACCESS_DENIED"
    MFA_BYPASS_INITIATED = "MFA_BYPASS_INITIATED"
    MFA_BYPASS_FAILED_AUTH = "MFA_BYPASS_FAILED_AUTH"

    # Impersonation
    IMPERSONATION_START = "IMPERSONATION_START"
    IMPERSONATION_END = "IMPERSONATION_END"
    IMPERSONATION_ATTEMPT_FAILED = "IMPERSONATION_ATTEMPT_FAILED"

    # Password management
    ADMIN_PASSWORD_RESET = "ADMIN_PASSWORD_RESET"
    ADMIN_PASSWORD_RESET_FAILED = "ADMIN_PASSWORD_RESET_FAILED"
    PASSWORD_RESET_REQUESTED = "PASSWORD_RESET_REQUESTED"
    PASSWORD_RESET_COMPLETED = "PASSWORD_RESET_COMPLETED"

    # Messaging
    ADMIN_MESSAGE_SENT = "ADMIN_MESSAGE_SENT"
    ADMIN_MESSAGE_PREVIEW = "ADMIN_MESSAGE_PREVIEW"
    MESSAGE_NOTIFICATIONS_QUEUED = "MESSAGE_NOTIFICATIONS_QUEUED"
    MESSAGE_NOTIFICATIONS_SKIPPED = "MESSAGE_NOTIFICATIONS_SKIPPED"
    GOVERNANCE_REMINDER_SENT = "GOVERNANCE_REMINDER_SENT"
    GOVERNANCE_REMINDER_ATTEMPTED = "GOVERNANCE_REMINDER_ATTEMPTED"
    CONTACT_MESSAGE_RESOLVED = "CONTACT_MESSAGE_RESOLVED"

    # Backup operations
    BACKUP_RESTORED = "BACKUP_RESTORED"
    BACKUP_DELETED = "BACKUP_DELETED"
    BACKUP_CLEANUP = "BACKUP_CLEANUP"

    # Reports
    REPORT_GENERATED = "REPORT_GENERATED"

    # KPI maintenance
    KPI_GOVERNANCE_BACKFILL = "KPI_GOVERNANCE_BACKFILL"

    # Heat map data supply
    HEATMAP_DATASET_REGENERATED = "HEATMAP_DATASET_REGENERATED"

    # Daily reports
    DAILY_REPORT_CREATED = "DAILY_REPORT_CREATED"
    DAILY_REPORT_EDITED = "DAILY_REPORT_EDITED"
    DAILY_REPORT_FORCE_UPDATED = "DAILY_REPORT_FORCE_UPDATED"
    DAILY_REPORT_SUBMITTED = "DAILY_REPORT_SUBMITTED"
    DAILY_REPORT_SENT_TO_PARENT = "DAILY_REPORT_SENT_TO_PARENT"
    DAILY_REPORT_DELETED = "DAILY_REPORT_DELETED"

    # Incident reports (supervisor)
    INCIDENT_RESOLVED = "INCIDENT_RESOLVED"

    # Attendance (supervisor)
    ATTENDANCE_OVERRIDE = "ATTENDANCE_OVERRIDE"

    # 2FA / MFA self-service
    MFA_ENABLED = "MFA_ENABLED"
    MFA_DISABLED = "MFA_DISABLED"

    # Audit log management
    AUDIT_LOG_CLEANUP = "AUDIT_LOG_CLEANUP"

    # Message lifecycle (communication_service)
    MESSAGE_SENT = "MESSAGE_SENT"
    MESSAGE_ANNOUNCEMENT_SENT = "MESSAGE_ANNOUNCEMENT_SENT"
    MESSAGE_VIEWED = "MESSAGE_VIEWED"
    MESSAGE_READ = "MESSAGE_READ"
    MESSAGE_REPLIED = "MESSAGE_REPLIED"
    MESSAGE_DELETED = "MESSAGE_DELETED"
    MESSAGE_ARCHIVED = "MESSAGE_ARCHIVED"
    MESSAGE_UNARCHIVED = "MESSAGE_UNARCHIVED"
    MESSAGE_ATTACHMENT_ADDED = "MESSAGE_ATTACHMENT_ADDED"
    MESSAGE_ATTACHMENT_ACCESS_AUTHORIZED = "MESSAGE_ATTACHMENT_ACCESS_AUTHORIZED"
    # Retained for historical audit rows; new FileResponse/redirect flows cannot
    # truthfully assert that the client received bytes.
    MESSAGE_ATTACHMENT_DOWNLOADED = "MESSAGE_ATTACHMENT_DOWNLOADED"

    # Classification cache
    CLASSIFICATION_CACHE = "CLASSIFICATION_CACHE"

    # Import tasks
    BULK_USER_IMPORT = "BULK_USER_IMPORT"

    # Backup tasks
    BACKUP_CREATED = "BACKUP_CREATED"

    # Auth lifecycle
    LOGIN_SUCCESS = "LOGIN_SUCCESS"
    LOGIN_FAILED = "LOGIN_FAILED"
    LOGIN_LOCKED = "LOGIN_LOCKED"
    LOGOUT = "LOGOUT"
    REGISTER = "REGISTER"
    REGISTER_SUCCESS = "REGISTER_SUCCESS"
    TOKEN_REFRESH = "TOKEN_REFRESH"
    PASSWORD_RESET = "PASSWORD_RESET"

    # MFA
    MFA_REQUIRED = "MFA_REQUIRED"
    MFA_VERIFIED = "MFA_VERIFIED"
    MFA_FAILED = "MFA_FAILED"

    # Attendance
    ATTENDANCE_CHECK_IN = "ATTENDANCE_CHECK_IN"
    ATTENDANCE_CHECK_OUT = "ATTENDANCE_CHECK_OUT"
    ATTENDANCE_STATUS_CORRECTED = "ATTENDANCE_STATUS_CORRECTED"

    # Classes
    CLASS_CREATED = "CLASS_CREATED"
    CLASS_UPDATED = "CLASS_UPDATED"
    CLASS_DEACTIVATED = "CLASS_DEACTIVATED"
    CLASS_DELETED = "CLASS_DELETED"
    CHILD_ASSIGNED_TO_CLASS = "CHILD_ASSIGNED_TO_CLASS"
    CHILD_MOVED_CLASS = "CHILD_MOVED_CLASS"
    REPLACEMENT_SUPERVISOR_ASSIGNED = "REPLACEMENT_SUPERVISOR_ASSIGNED"
    SUPERVISOR_ASSIGNED = "SUPERVISOR_ASSIGNED"
    SUPERVISOR_UNASSIGNED = "SUPERVISOR_UNASSIGNED"

    # Absence requests
    ABSENCE_REQUEST_APPROVED = "ABSENCE_REQUEST_APPROVED"
    ABSENCE_REQUEST_REJECTED = "ABSENCE_REQUEST_REJECTED"

    # Staff
    STAFF_CREATED = "STAFF_CREATED"

    # Kindergartens
    KINDERGARTEN_CREATED = "KINDERGARTEN_CREATED"
    KINDERGARTEN_UPDATED = "KINDERGARTEN_UPDATED"
    KINDERGARTEN_ARCHIVED = "KINDERGARTEN_ARCHIVED"
    KINDERGARTEN_DELETED = "KINDERGARTEN_DELETED"
    KINDERGARTEN_RESTORED = "KINDERGARTEN_RESTORED"
    KINDERGARTEN_FROZEN = "KINDERGARTEN_FROZEN"
    KINDERGARTEN_UNFROZEN = "KINDERGARTEN_UNFROZEN"
    # Manager assignment / reassignment lifecycle
    MANAGER_ASSIGNED = "MANAGER_ASSIGNED"
    MANAGER_REASSIGNED = "MANAGER_REASSIGNED"
    MANAGER_DETACHED = "MANAGER_DETACHED"
    SUPERVISOR_ROLE_REMOVED = "SUPERVISOR_ROLE_REMOVED"
    KINDERGARTEN_SERVICE_CREATED = "KINDERGARTEN_SERVICE_CREATED"
    KINDERGARTEN_SERVICE_UPDATED = "KINDERGARTEN_SERVICE_UPDATED"
    KINDERGARTEN_SERVICE_DELETED = "KINDERGARTEN_SERVICE_DELETED"

    # Enrollment decisions
    ENROLLMENT_ACCEPTED = "ENROLLMENT_ACCEPTED"
    ENROLLMENT_REJECTED = "ENROLLMENT_REJECTED"

    # External / government API
    GOVERNMENT_API_ACCESS = "GOVERNMENT_API_ACCESS"

    # Parent/child data access (privacy-compliance traceability)
    PARENT_DATA_VIEWED = "PARENT_DATA_VIEWED"
    CHILD_DATA_ACCESSED = "CHILD_DATA_ACCESSED"


EXPORT_ACTIONS = {
    "user_export": AuditAction.USER_EXPORT,
    "audit_log_export": AuditAction.AUDIT_LOG_EXPORT,
    "incident_report_export": AuditAction.INCIDENT_REPORT_EXPORT,
    "incident_report_export_failed": AuditAction.INCIDENT_REPORT_EXPORT_FAILED,
    "analytics_export_sync": AuditAction.ANALYTICS_EXPORT_SYNC,
    "analytics_export_sync_failed": AuditAction.ANALYTICS_EXPORT_SYNC_FAILED,
    "analytics_export_requested": AuditAction.ANALYTICS_EXPORT_REQUESTED,
    "analytics_export_request_failed": AuditAction.ANALYTICS_EXPORT_REQUEST_FAILED,
    "analytics_export_downloaded": AuditAction.ANALYTICS_EXPORT_DOWNLOADED,
    "analytics_export_job_completed": AuditAction.ANALYTICS_EXPORT_JOB_COMPLETED,
    "analytics_export_job_failed": AuditAction.ANALYTICS_EXPORT_JOB_FAILED,
}


EXPORT_ACTION_VALUES = frozenset(EXPORT_ACTIONS.values())

