"""
Centralized audit action identifiers.

Use these constants instead of hard-coded strings to keep audit action
taxonomy consistent across endpoints and tests.
"""


class AuditAction:
    # User/Admin exports
    USER_EXPORT = "USER_EXPORT"
    AUDIT_LOG_EXPORT = "AUDIT_LOG_EXPORT"

    # Incident report exports
    INCIDENT_REPORT_EXPORT = "INCIDENT_REPORT_EXPORT"
    INCIDENT_REPORT_EXPORT_FAILED = "INCIDENT_REPORT_EXPORT_FAILED"

    # Analytics exports
    ANALYTICS_EXPORT_SYNC = "ANALYTICS_EXPORT_SYNC"
    ANALYTICS_EXPORT_SYNC_FAILED = "ANALYTICS_EXPORT_SYNC_FAILED"
    ANALYTICS_EXPORT_REQUESTED = "ANALYTICS_EXPORT_REQUESTED"
    ANALYTICS_EXPORT_REQUEST_FAILED = "ANALYTICS_EXPORT_REQUEST_FAILED"
    ANALYTICS_EXPORT_DOWNLOADED = "ANALYTICS_EXPORT_DOWNLOADED"
    ANALYTICS_EXPORT_JOB_COMPLETED = "ANALYTICS_EXPORT_JOB_COMPLETED"
    ANALYTICS_EXPORT_JOB_FAILED = "ANALYTICS_EXPORT_JOB_FAILED"

    # Admin dashboard
    ADMIN_DASHBOARD_VIEWED = "ADMIN_DASHBOARD_VIEWED"
    ADMIN_DASHBOARD_ERROR = "ADMIN_DASHBOARD_ERROR"
    CLASSIFICATION_CACHE_WARM = "CLASSIFICATION_CACHE_WARM"
    CLASSIFICATION_CACHE_INVALIDATE = "CLASSIFICATION_CACHE_INVALIDATE"

    # Admin profile self-service
    ADMIN_PROFILE_UPDATED = "ADMIN_PROFILE_UPDATED"
    ADMIN_PASSWORD_CHANGED = "ADMIN_PASSWORD_CHANGED"

    # Backup operations
    BACKUP_ENQUEUED = "BACKUP_ENQUEUED"
    BACKUP_FAILED = "BACKUP_FAILED"

    # Admin password
    ADMIN_PASSWORD_CHANGE_FAILED = "ADMIN_PASSWORD_CHANGE_FAILED"

    # Kindergarten imports
    KINDERGARTEN_IMPORT = "KINDERGARTEN_IMPORT"

    # Alert management
    ALERT_ACKNOWLEDGED = "ALERT_ACKNOWLEDGED"

    # User lifecycle
    USER_CREATED = "USER_CREATED"
    USER_UPDATED = "USER_UPDATED"
    USER_DELETED = "USER_DELETED"
    BULK_USER_CREATE = "BULK_USER_CREATE"
    BULK_USER_DELETE = "BULK_USER_DELETE"
    BULK_STATUS_UPDATE = "BULK_STATUS_UPDATE"
    CSV_IMPORT = "CSV_IMPORT"
    CHILDREN_CREATED = "CHILDREN_CREATED"

    # Access control
    ACCESS_DENIED = "ACCESS_DENIED"
    BULK_ACCESS_DENIED = "BULK_ACCESS_DENIED"
    MFA_BYPASS_INITIATED = "MFA_BYPASS_INITIATED"
    MFA_BYPASS_FAILED_AUTH = "MFA_BYPASS_FAILED_AUTH"

    # Impersonation
    IMPERSONATION_START = "IMPERSONATION_START"
    IMPERSONATION_END = "IMPERSONATION_END"
    IMPERSONATION_ATTEMPT_FAILED = "IMPERSONATION_ATTEMPT_FAILED"

    # Password management
    ADMIN_PASSWORD_RESET = "ADMIN_PASSWORD_RESET"
    ADMIN_PASSWORD_RESET_FAILED = "ADMIN_PASSWORD_RESET_FAILED"
    PASSWORD_RESET_REQUESTED = "PASSWORD_RESET_REQUESTED"
    PASSWORD_RESET_COMPLETED = "PASSWORD_RESET_COMPLETED"

    # Messaging
    ADMIN_MESSAGE_SENT = "ADMIN_MESSAGE_SENT"
    ADMIN_MESSAGE_PREVIEW = "ADMIN_MESSAGE_PREVIEW"
    MESSAGE_NOTIFICATIONS_QUEUED = "MESSAGE_NOTIFICATIONS_QUEUED"
    MESSAGE_NOTIFICATIONS_SKIPPED = "MESSAGE_NOTIFICATIONS_SKIPPED"
    GOVERNANCE_REMINDER_SENT = "GOVERNANCE_REMINDER_SENT"
    CONTACT_MESSAGE_RESOLVED = "CONTACT_MESSAGE_RESOLVED"

    # Backup operations
    BACKUP_RESTORED = "BACKUP_RESTORED"
    BACKUP_DELETED = "BACKUP_DELETED"
    BACKUP_CLEANUP = "BACKUP_CLEANUP"

    # Reports
    REPORT_GENERATED = "REPORT_GENERATED"

    # Audit log management
    AUDIT_LOG_CLEANUP = "AUDIT_LOG_CLEANUP"

    # Message lifecycle (communication_service)
    MESSAGE_SENT = "MESSAGE_SENT"
    MESSAGE_ANNOUNCEMENT_SENT = "MESSAGE_ANNOUNCEMENT_SENT"
    MESSAGE_VIEWED = "MESSAGE_VIEWED"
    MESSAGE_READ = "MESSAGE_READ"
    MESSAGE_REPLIED = "MESSAGE_REPLIED"
    MESSAGE_DELETED = "MESSAGE_DELETED"
    MESSAGE_ARCHIVED = "MESSAGE_ARCHIVED"
    MESSAGE_UNARCHIVED = "MESSAGE_UNARCHIVED"
    MESSAGE_ATTACHMENT_ADDED = "MESSAGE_ATTACHMENT_ADDED"
    MESSAGE_ATTACHMENT_DOWNLOADED = "MESSAGE_ATTACHMENT_DOWNLOADED"

    # Classification cache
    CLASSIFICATION_CACHE = "CLASSIFICATION_CACHE"

    # Import tasks
    BULK_USER_IMPORT = "BULK_USER_IMPORT"

    # Backup tasks
    BACKUP_CREATED = "BACKUP_CREATED"

    # Auth lifecycle
    LOGIN_SUCCESS = "LOGIN_SUCCESS"
    LOGIN_FAILED = "LOGIN_FAILED"
    LOGIN_LOCKED = "LOGIN_LOCKED"
    LOGOUT = "LOGOUT"
    REGISTER = "REGISTER"
    REGISTER_SUCCESS = "REGISTER_SUCCESS"
    TOKEN_REFRESH = "TOKEN_REFRESH"
    PASSWORD_RESET = "PASSWORD_RESET"

    # MFA
    MFA_REQUIRED = "MFA_REQUIRED"
    MFA_VERIFIED = "MFA_VERIFIED"
    MFA_FAILED = "MFA_FAILED"

    # Attendance
    ATTENDANCE_CHECK_IN = "ATTENDANCE_CHECK_IN"
    ATTENDANCE_CHECK_OUT = "ATTENDANCE_CHECK_OUT"
    ATTENDANCE_STATUS_CORRECTED = "ATTENDANCE_STATUS_CORRECTED"

    # Classes
    CLASS_CREATED = "CLASS_CREATED"
    CLASS_UPDATED = "CLASS_UPDATED"
    CLASS_DEACTIVATED = "CLASS_DEACTIVATED"
    CLASS_DELETED = "CLASS_DELETED"
    CHILD_ASSIGNED_TO_CLASS = "CHILD_ASSIGNED_TO_CLASS"
    REPLACEMENT_SUPERVISOR_ASSIGNED = "REPLACEMENT_SUPERVISOR_ASSIGNED"
    SUPERVISOR_ASSIGNED = "SUPERVISOR_ASSIGNED"

    # Staff
    STAFF_CREATED = "STAFF_CREATED"

    # Kindergartens
    KINDERGARTEN_CREATED = "KINDERGARTEN_CREATED"
    KINDERGARTEN_UPDATED = "KINDERGARTEN_UPDATED"
    KINDERGARTEN_ARCHIVED = "KINDERGARTEN_ARCHIVED"
    KINDERGARTEN_DELETED = "KINDERGARTEN_DELETED"
    KINDERGARTEN_RESTORED = "KINDERGARTEN_RESTORED"
    KINDERGARTEN_SERVICE_CREATED = "KINDERGARTEN_SERVICE_CREATED"
    KINDERGARTEN_SERVICE_UPDATED = "KINDERGARTEN_SERVICE_UPDATED"
    KINDERGARTEN_SERVICE_DELETED = "KINDERGARTEN_SERVICE_DELETED"

    # Enrollment decisions
    ENROLLMENT_ACCEPTED = "ENROLLMENT_ACCEPTED"
    ENROLLMENT_REJECTED = "ENROLLMENT_REJECTED"

    # External / government API
    GOVERNMENT_API_ACCESS = "GOVERNMENT_API_ACCESS"


EXPORT_ACTIONS = {
    "user_export": AuditAction.USER_EXPORT,
    "audit_log_export": AuditAction.AUDIT_LOG_EXPORT,
    "incident_report_export": AuditAction.INCIDENT_REPORT_EXPORT,
    "incident_report_export_failed": AuditAction.INCIDENT_REPORT_EXPORT_FAILED,
    "analytics_export_sync": AuditAction.ANALYTICS_EXPORT_SYNC,
    "analytics_export_sync_failed": AuditAction.ANALYTICS_EXPORT_SYNC_FAILED,
    "analytics_export_requested": AuditAction.ANALYTICS_EXPORT_REQUESTED,
    "analytics_export_request_failed": AuditAction.ANALYTICS_EXPORT_REQUEST_FAILED,
    "analytics_export_downloaded": AuditAction.ANALYTICS_EXPORT_DOWNLOADED,
    "analytics_export_job_completed": AuditAction.ANALYTICS_EXPORT_JOB_COMPLETED,
    "analytics_export_job_failed": AuditAction.ANALYTICS_EXPORT_JOB_FAILED,
}


EXPORT_ACTION_VALUES = frozenset(EXPORT_ACTIONS.values())

