"""Structured content for the Admin Help Center.

The manifest keeps the page data-driven so coverage, search, and rendering
remain consistent as the Admin navigation evolves.
"""

from __future__ import annotations

from typing import Dict, List


def bi(ar: str, en: str) -> Dict[str, str]:
    return {"ar": ar, "en": en}


def make_search_blob(*parts: object) -> str:
    tokens: List[str] = []
    for part in parts:
        if not part:
            continue
        if isinstance(part, str):
            tokens.append(part)
        elif isinstance(part, dict):
            tokens.extend(str(value) for value in part.values() if value)
        elif isinstance(part, (list, tuple, set)):
            tokens.extend(str(value) for value in part if value)
        else:
            tokens.append(str(part))
    return " ".join(tokens)


def topic(
    *,
    id: str,
    route: str,
    title_ar: str,
    title_en: str,
    purpose_ar: str,
    purpose_en: str,
    who_ar: str,
    who_en: str,
    scope_ar: str,
    scope_en: str,
    before_ar: str,
    before_en: str,
    step1_ar: str,
    step1_en: str,
    step2_ar: str,
    step2_en: str,
    step3_ar: str,
    step3_en: str,
    expected_ar: str,
    expected_en: str,
    status_defs_ar: List[str],
    status_defs_en: List[str],
    common_errors_ar: List[str],
    common_errors_en: List[str],
    privacy_ar: str,
    privacy_en: str,
    status_label_ar: str = "مُطبَّق ومُتحقَّق منه",
    status_label_en: str = "Implemented and verified",
    aliases_ar: List[str] | None = None,
    aliases_en: List[str] | None = None,
    related_links: List[Dict[str, str]] | None = None,
) -> Dict[str, object]:
    aliases_ar = aliases_ar or []
    aliases_en = aliases_en or []
    related_links = related_links or [{"href": route, "label": bi("الانتقال إلى الصفحة", "Open the page")}]
    search_blob = make_search_blob(
        id,
        route,
        title_ar,
        title_en,
        purpose_ar,
        purpose_en,
        who_ar,
        who_en,
        scope_ar,
        scope_en,
        before_ar,
        before_en,
        step1_ar,
        step1_en,
        step2_ar,
        step2_en,
        step3_ar,
        step3_en,
        expected_ar,
        expected_en,
        status_defs_ar,
        status_defs_en,
        common_errors_ar,
        common_errors_en,
        privacy_ar,
        privacy_en,
        aliases_ar,
        aliases_en,
    )
    return {
        "id": id,
        "route": route,
        "title": bi(title_ar, title_en),
        "status": bi(status_label_ar, status_label_en),
        "purpose": bi(purpose_ar, purpose_en),
        "who": bi(who_ar, who_en),
        "scope": bi(scope_ar, scope_en),
        "before": bi(before_ar, before_en),
        "steps": [bi(step1_ar, step1_en), bi(step2_ar, step2_en), bi(step3_ar, step3_en)],
        "expected": bi(expected_ar, expected_en),
        "status_defs": [bi(item_ar, item_en) for item_ar, item_en in zip(status_defs_ar, status_defs_en)],
        "common_errors": [bi(item_ar, item_en) for item_ar, item_en in zip(common_errors_ar, common_errors_en)],
        "privacy": bi(privacy_ar, privacy_en),
        "aliases": {"ar": aliases_ar, "en": aliases_en},
        "related_links": related_links,
        "search_blob": search_blob,
    }


HELP_CENTER_META = {
    "content_owner": bi("فريق المنصة / الإدارة", "Platform / Admin Content Team"),
    "product_version": "2.0.0",
    "help_version": "2026.07.21",
    "last_reviewed": "2026-07-21",
}


DEFAULT_ERRORS_AR = [
    "403 يعني أن الدور أو النطاق لا يسمح بالإجراء، أو أن التحقق الأمني للطلب المعدِّل فشل.",
    "422 يعني أن أحد الحقول أو الصيغ يحتاج إلى تصحيح.",
    "404 يعني أن السجل غير متاح ضمن نطاقك أو غير موجود في هذا العرض.",
]
DEFAULT_ERRORS_EN = [
    "403 means the role or scope does not allow the action, or the write request failed security validation.",
    "422 means one of the fields or formats needs correction.",
    "404 means the record is unavailable within your scope or does not exist in this view.",
]

DEFAULT_PRIVACY_AR = "لا تشارك كلمات المرور أو الرموز أو بيانات الطفل خارج النطاق المصرح به."
DEFAULT_PRIVACY_EN = "Do not share passwords, tokens, or child-level data outside the approved scope."

HELP_CENTER_TOPICS = [
    topic(
        id="dashboard",
        route="/admin/dashboard",
        title_ar="لوحة التحكم الإدارية",
        title_en="Admin Dashboard",
        purpose_ar="عرض ملخص تنفيذي للحالة العامة والحركة والمهام التي تحتاج متابعة.",
        purpose_en="Show the executive summary of platform health, activity, and items that need follow-up.",
        who_ar="المسؤولون",
        who_en="Admins",
        scope_ar="النطاق العام للمنصة ضمن الفترة المحددة.",
        scope_en="Platform-wide scope for the selected time window.",
        before_ar="تأكد من صحة الفترة واللغة قبل تفسير البطاقات.",
        before_en="Confirm the date range and language before interpreting the cards.",
        step1_ar="افتح لوحة التحكم من الشريط الجانبي لمراجعة المؤشرات الأساسية.",
        step1_en="Open the dashboard from the sidebar to review the core indicators.",
        step2_ar="استخدم الفترة والمرشحات لتضييق النتائج إذا بدت الأرقام غير متوقعة.",
        step2_en="Use the period and filters to narrow the result if a number looks unexpected.",
        step3_ar="افتح صفحات التفاصيل المرتبطة عندما تحتاج إلى سبب أو إجراء.",
        step3_en="Open the linked detail pages when you need a driver or next action.",
        expected_ar="تظهر لك حالة المنصة والاتجاهات والصفحات التي تحتاج اهتمامًا.",
        expected_en="You can see platform status, trends, and the pages that need attention.",
        status_defs_ar=["الأرقام هنا مقاسة وليست أهدافًا.", "الشرطة تعني أن القيمة غير متاحة ضمن الفترة أو النطاق الحالي."],
        status_defs_en=["The values are measured results, not targets.", "A dash means the value is unavailable for the current period or scope."],
        common_errors_ar=DEFAULT_ERRORS_AR,
        common_errors_en=DEFAULT_ERRORS_EN,
        privacy_ar=DEFAULT_PRIVACY_AR,
        privacy_en=DEFAULT_PRIVACY_EN,
        aliases_ar=["الملخص الإداري", "الصفحة الرئيسية للمسؤول"],
        aliases_en=["Executive summary", "Admin home"],
    ),
    topic(
        id="observability",
        route="/admin/observability",
        title_ar="مراقبة النظام",
        title_en="System Health / Observability",
        purpose_ar="مراقبة زمن الاستجابة والأخطاء والتخزين المؤقت وصحة الخدمات.",
        purpose_en="Monitor latency, errors, caching, and service health.",
        who_ar="المسؤولون",
        who_en="Admins",
        scope_ar="مؤشرات الصحة الخاصة بالمنصة والخدمات الخلفية.",
        scope_en="Health indicators for the platform and backend services.",
        before_ar="راجع الفترة والبيئة قبل مقارنة أي قيمة مع خط الأساس.",
        before_en="Check the period and environment before comparing against a baseline.",
        step1_ar="افتح صفحة مراقبة النظام لعرض ملخص الصحة.",
        step1_en="Open the observability page to view the health summary.",
        step2_ar="راجع p95 ومعدل الخطأ والاستفادة من التخزين المؤقت وصحة الخدمة.",
        step2_en="Review p95 latency, error rate, cache-hit rate, and service health.",
        step3_ar="استخدم التحديث أو المرشحات إذا كان هناك ارتفاع غير متوقع.",
        step3_en="Use refresh or the filters if you see an unexpected spike.",
        expected_ar="تتعرف بسرعة على الخدمة أو المؤشر الذي يحتاج متابعة.",
        expected_en="You can quickly identify the service or metric that needs follow-up.",
        status_defs_ar=["القيم تعرض نافذة القياس والوحدات.", "توقف الصحة أو تدهورها يعني أن الخدمة تحتاج مراجعة."],
        status_defs_en=["Values include the measurement window and units.", "Degraded health means the service needs review."],
        common_errors_ar=["403 يعني أن الصفحة خاصة بالمسؤول.", "الشرطة تعني أن القياس غير متاح لهذه النافذة."],
        common_errors_en=["403 means the page is restricted to admins.", "A dash means the measurement is unavailable for this window."],
        privacy_ar=DEFAULT_PRIVACY_AR,
        privacy_en=DEFAULT_PRIVACY_EN,
        aliases_ar=["صحة النظام", "المراقبة"],
        aliases_en=["Health", "Monitoring"],
    ),
    topic(
        id="alerts",
        route="/admin/alerts",
        title_ar="التنبيهات",
        title_en="Alerts",
        purpose_ar="مراجعة التنبيهات التي وصلت إلى حدود حرجة أو عالية وتوثيق الإقرار بها.",
        purpose_en="Review alerts that crossed a threshold and record acknowledgement.",
        who_ar="المسؤولون",
        who_en="Admins",
        scope_ar="التنبيهات الناتجة عن المؤشرات والحدود المراقبة.",
        scope_en="Alerts generated from monitored indicators and thresholds.",
        before_ar="تأكد من أن سبب التنبيه ليس بسبب مرشح ضيق أو فترة قصيرة جدًا.",
        before_en="Make sure the alert is not the result of an overly narrow filter or period.",
        step1_ar="افتح صفحة التنبيهات وحدد الشدة والفترة.",
        step1_en="Open the alerts page and set the severity and time window.",
        step2_ar="راجع المؤشر والقيمة الحالية والحد والوقت الذي أُطلق فيه التنبيه.",
        step2_en="Review the metric, current value, threshold, and trigger time.",
        step3_ar="أقرّ التنبيه بعد اتخاذ الإجراء المناسب أو صعّده إذا لزم الأمر.",
        step3_en="Acknowledge the alert after action, or escalate it if needed.",
        expected_ar="تعرف التنبيهات المفتوحة ومن أقرّ بها وما زال يحتاج متابعة.",
        expected_en="You can see open alerts, who acknowledged them, and what still needs follow-up.",
        status_defs_ar=["الحالة توضّح ما إذا كان التنبيه نشطًا أو أُقرّ به أو حُلّ.", "الخطورة توضّح أولوية التعامل."],
        status_defs_en=["Status shows whether an alert is active, acknowledged, or resolved.", "Severity shows handling priority."],
        common_errors_ar=DEFAULT_ERRORS_AR,
        common_errors_en=DEFAULT_ERRORS_EN,
        privacy_ar=DEFAULT_PRIVACY_AR,
        privacy_en=DEFAULT_PRIVACY_EN,
        aliases_ar=["إدارة التنبيهات", "إنذارات النظام"],
        aliases_en=["Alert management", "System alerts"],
    ),
    topic(
        id="users",
        route="/admin/users",
        title_ar="المستخدمون",
        title_en="Users",
        purpose_ar="البحث في الحسابات وإدارتها حسب الدور والحالة والحضانة ضمن الصلاحية الممنوحة.",
        purpose_en="Search and manage accounts by role, status, and kindergarten within your authorization scope.",
        who_ar="المسؤولون، والمديرون حيث تسمح الصلاحية.",
        who_en="Admins, and managers where the permission allows.",
        scope_ar="الحسابات التي تقع داخل نطاق الوصول الممنوح لك فقط.",
        scope_en="Only the accounts inside your allowed scope.",
        before_ar="تأكد من الدور والنطاق قبل التعديل أو إعادة التعيين.",
        before_en="Confirm role and scope before editing or resetting credentials.",
        step1_ar="افتح قائمة المستخدمين وفلتر حسب الدور أو الحالة أو الحضانة.",
        step1_en="Open Users and filter by role, status, or kindergarten.",
        step2_ar="افتح السجل الذي تحتاجه ثم عدّل البيانات أو الصلاحية المسموح بها.",
        step2_en="Open the record you need, then edit the allowed fields.",
        step3_ar="استخدم إعادة التعيين الإداري فقط عندما يكون ذلك مطلوبًا وبإقرارك الحالي.",
        step3_en="Use the admin password reset only when required and with your current administrator password.",
        expected_ar="يتحدد الحساب المستهدف وتظهر لك الإجراءات المسموح بها فقط.",
        expected_en="The target account is identified and only the allowed actions are shown.",
        status_defs_ar=["لا تعرض الواجهة حسابات خارج النطاق.", "الدور يحدد مستوى الوصول العام والخادم يفرض التفصيل."],
        status_defs_en=["The UI does not expose accounts outside your scope.", "Role sets the general access level and the server enforces the details."],
        common_errors_ar=["403 يعني أن الحساب أو الإجراء خارج صلاحيتك.", "409 يظهر عند تعارض التعيين أو التحديث."],
        common_errors_en=["403 means the account or action is outside your scope.", "409 appears when an assignment or update conflicts."],
        privacy_ar="لا تشارك كلمات المرور أو رموز MFA أو بيانات الحسابات خارج الحاجة التشغيلية.",
        privacy_en="Do not share passwords, MFA codes, or account data beyond the operational need.",
        aliases_ar=["إدارة المستخدمين", "حسابات المستخدمين"],
        aliases_en=["User management", "User accounts"],
    ),
    topic(
        id="import-users",
        route="/admin/users/import",
        title_ar="استيراد المستخدمين",
        title_en="Import Users",
        purpose_ar="إنشاء حسابات متعددة من ملف CSV بعد التحقق من الأعمدة والقيم.",
        purpose_en="Create multiple accounts from a CSV file after validating columns and values.",
        who_ar="المسؤولون",
        who_en="Admins",
        scope_ar="الملف الحالي وصفوفه فقط.",
        scope_en="Only the current file and its rows.",
        before_ar="تأكد من وجود الأعمدة المطلوبة ومن صحة عناوين البريد والدور.",
        before_en="Confirm the required columns and the email and role values.",
        step1_ar="حمّل النموذج المرفق واملأه بالبيانات المطلوبة.",
        step1_en="Download the template and fill it with the required data.",
        step2_ar="ارفع الملف وراجع الأخطاء على مستوى الصف قبل الاعتماد.",
        step2_en="Upload the file and review row-level errors before confirming.",
        step3_ar="اعتمد الاستيراد إذا كانت النتائج المتوقعة مطابقة لما ظهر في المعاينة.",
        step3_en="Confirm the import if the preview matches the intended result.",
        expected_ar="تظهر الصفوف المنشأة أو المتجاوزة أو الخاطئة بوضوح.",
        expected_en="Created, skipped, and error rows are shown clearly.",
        status_defs_ar=["النتيجة تُعرض على مستوى الصف.", "الاستيراد لا يتجاوز التحقق من الصلاحيات."],
        status_defs_en=["Results are shown at row level.", "The import does not bypass permission checks."],
        common_errors_ar=["422 يعني أن عمودًا أو قيمة غير صحيحة.", "413 أو فشل الرفع يعني أن الملف كبير جدًا أو غير صالح."],
        common_errors_en=["422 means a column or value is invalid.", "413 or upload failure means the file is too large or invalid."],
        privacy_ar="لا تضع كلمات مرور غير لازمة في ملف CSV.",
        privacy_en="Do not include unnecessary passwords in the CSV file.",
        aliases_ar=["استيراد الحسابات", "إضافة مستخدمين جماعيًا"],
        aliases_en=["Account import", "Bulk user creation"],
    ),
    topic(
        id="kg-overview",
        route="/admin/kg-overview",
        title_ar="نظرة عامة على الحضانات",
        title_en="Kindergarten Overview",
        purpose_ar="مراقبة الشبكة واكتشاف الحالات أو البيانات التي تحتاج متابعة.",
        purpose_en="Monitor the network and spot operating or data conditions that need follow-up.",
        who_ar="المسؤولون",
        who_en="Admins",
        scope_ar="ملخصات الحضانة عبر النطاق المختار.",
        scope_en="Kindergarten summaries across the selected scope.",
        before_ar="تأكد من النطاق الجغرافي والفترة قبل تفسير الكثافة أو الإشغال.",
        before_en="Confirm geography and period before interpreting density or occupancy.",
        step1_ar="افتح النظرة العامة لمراجعة الملخصات الأساسية.",
        step1_en="Open the overview to review the key summaries.",
        step2_ar="استخدم المرشحات الجغرافية أو الزمنية لفهم سبب أي تباين.",
        step2_en="Use geographic or date filters to understand any variance.",
        step3_ar="انتقل إلى سجل الحضانة عند الحاجة إلى تعديل أو إجراء.",
        step3_en="Open Kindergarten Records when you need to edit or act.",
        expected_ar="تعرف أي حضانة أو منطقة تحتاج متابعة تشغيلية.",
        expected_en="You can identify which kindergarten or area needs operational follow-up.",
        status_defs_ar=["الإشغال يعتمد على السعة المتاحة والعدد الفعلي.", "الشرطة تعني عدم توفر البيانات الحالية."],
        status_defs_en=["Occupancy depends on available capacity and actual count.", "A dash means the current data is unavailable."],
        common_errors_ar=DEFAULT_ERRORS_AR,
        common_errors_en=DEFAULT_ERRORS_EN,
        privacy_ar=DEFAULT_PRIVACY_AR,
        privacy_en=DEFAULT_PRIVACY_EN,
        aliases_ar=["ملخص الحضانات", "مراقبة الشبكة"],
        aliases_en=["Kindergarten summary", "Network monitoring"],
    ),
    topic(
        id="kindergarten-records",
        route="/admin/kindergartens",
        title_ar="سجل الحضانات",
        title_en="Kindergarten Records",
        purpose_ar="إنشاء سجلات الحضانات وعرضها وتعديلها وتجميدها أو تفعيلها ضمن الصلاحية.",
        purpose_en="Create, view, edit, freeze, or activate kindergarten records within permission limits.",
        who_ar="المسؤولون",
        who_en="Admins",
        scope_ar="السجل الرسمي للحضانة وبياناتها التشغيلية والإدارية.",
        scope_en="The official kindergarten record and its operational and administrative data.",
        before_ar="جهّز الاسم العربي والعنوان وبيانات الاتصال قبل الإنشاء.",
        before_en="Prepare the Arabic name, address, and contact details before creating a record.",
        step1_ar="افتح سجل الحضانات وحدد سجلًا موجودًا أو أنشئ سجلًا جديدًا.",
        step1_en="Open Kindergarten Records and choose an existing record or create a new one.",
        step2_ar="راجع الحالة والترخيص والمدير والطاقة قبل الحفظ.",
        step2_en="Review status, licence, manager, and capacity before saving.",
        step3_ar="جمّد أو فعّل السجل فقط عندما تقتضي الحالة التشغيلية ذلك.",
        step3_en="Freeze or activate the record only when the operational state requires it.",
        expected_ar="تُحفظ بيانات الحضانة وتظهر حالتها التشغيلية بوضوح.",
        expected_en="The kindergarten data is saved and its operational state is clear.",
        status_defs_ar=["الحالة قد تكون مسودة أو نشطة أو مجمدة بحسب البيانات.", "لا تُظهر الواجهة إجراءات خارج الصلاحية."],
        status_defs_en=["Status may be draft, active, or frozen depending on the record.", "The UI does not show actions outside your permission."],
        common_errors_ar=["409 قد يعني تعارض مدير أو ترخيص.", "404 يعني أن السجل غير متاح في نطاقك."],
        common_errors_en=["409 may mean a manager or licence conflict.", "404 means the record is not available in your scope."],
        privacy_ar=DEFAULT_PRIVACY_AR,
        privacy_en=DEFAULT_PRIVACY_EN,
        aliases_ar=["سجل الروضات", "إدارة الحضانة"],
        aliases_en=["Kindergarten log", "Kindergarten administration"],
    ),
    topic(
        id="messages",
        route="/admin/messages",
        title_ar="الرسائل",
        title_en="Messages",
        purpose_ar="مراجعة الرسائل الإدارية المرسلة وحالة الاستلام وعدد المستلمين.",
        purpose_en="Review administrative messages, delivery state, and recipient count.",
        who_ar="المسؤولون",
        who_en="Admins",
        scope_ar="آخر دفعات الرسائل المتاحة ضمن الصلاحية.",
        scope_en="The latest message batches available within your scope.",
        before_ar="حدد ما إذا كنت تحتاج الرسالة نفسها أم ملخصًا للحالة فقط.",
        before_en="Decide whether you need the message body itself or only its status summary.",
        step1_ar="افتح قائمة الرسائل وراجع أحدث العمليات.",
        step1_en="Open the message list and review the latest sends.",
        step2_ar="افتح الرسالة لمراجعة المستلمين والحالة والتوقيت.",
        step2_en="Open a message to review recipients, status, and timing.",
        step3_ar="انتقل إلى الإنشاء أو رسائل التواصل إذا كان المطلوب إجراءً جديدًا.",
        step3_en="Go to compose or contact messages if you need a new action.",
        expected_ar="تعرف الرسالة المرسلة وحالتها وأي متابعة لازمة.",
        expected_en="You can identify the sent message, its status, and any follow-up needed.",
        status_defs_ar=["المعاينة تقديرية والإرسال يعيد الحساب.", "القائمة تعرض الصفحة الحالية من الرسائل فقط."],
        status_defs_en=["Preview is an estimate and sending recalculates recipients.", "The list shows the current page of messages only."],
        common_errors_ar=DEFAULT_ERRORS_AR,
        common_errors_en=DEFAULT_ERRORS_EN,
        privacy_ar=DEFAULT_PRIVACY_AR,
        privacy_en=DEFAULT_PRIVACY_EN,
        aliases_ar=["قائمة الرسائل"],
        aliases_en=["Message list"],
    ),
    topic(
        id="compose-message",
        route="/admin/messages/compose",
        title_ar="إنشاء رسالة",
        title_en="Compose Message",
        purpose_ar="تحديد الجمهور والمرشحات ثم إرسال رسالة إدارية.",
        purpose_en="Define the audience and filters, then send an administrative message.",
        who_ar="المسؤولون",
        who_en="Admins",
        scope_ar="المستلمون الذين تسمح بهم المرشحات والدور.",
        scope_en="Recipients allowed by the filters and role.",
        before_ar="تحقق من النطاق والدور والموقع قبل الإرسال.",
        before_en="Check scope, role, and location before sending.",
        step1_ar="اختر طريقة الاستهداف ثم الموقع أو الحضانة والأدوار المناسبة.",
        step1_en="Choose the targeting mode, then the location or kindergarten and the allowed roles.",
        step2_ar="راجع المعاينة، لأنها تقديرية وليست نهائية.",
        step2_en="Review the preview, which is an estimate rather than a final count.",
        step3_ar="أرسل الرسالة بعد التأكد من المستلمين والمحتوى.",
        step3_en="Send the message after confirming the recipients and content.",
        expected_ar="تُرسل الرسالة إلى المجموعة المقصودة فقط بعد إعادة الحساب في الخادم.",
        expected_en="The message is sent only to the intended group after the server recalculates recipients.",
        status_defs_ar=["المعاينة لا تُعد وعدًا نهائيًا بعدد المستلمين.", "الإرسال النهائي يطبّق التحقق الأمني من جديد."],
        status_defs_en=["Preview is not a final recipient promise.", "Final send re-applies security validation."],
        common_errors_ar=["422 يظهر عند عدم اكتمال الحقول أو صيغة غير صحيحة.", "403 يظهر عند اختيار جمهور خارج الصلاحية."],
        common_errors_en=["422 appears when fields are missing or a format is wrong.", "403 appears when the selected audience is out of scope."],
        privacy_ar="لا ترفق بيانات حساسة أو رموزًا أو معلومات طفل غير لازمة للرسالة.",
        privacy_en="Do not attach sensitive data, tokens, or unnecessary child information.",
        aliases_ar=["تأليف رسالة", "إرسال رسالة"],
        aliases_en=["Message composer", "Message sending"],
    ),
    topic(
        id="contact-messages",
        route="/admin/contact-messages",
        title_ar="رسائل التواصل",
        title_en="Contact Messages",
        purpose_ar="مراجعة الرسائل الواردة ووضعها مفتوحة أو تمت معالجتها.",
        purpose_en="Review incoming contact messages and mark them open or resolved.",
        who_ar="المسؤولون",
        who_en="Admins",
        scope_ar="رسائل الاتصال الواردة فقط.",
        scope_en="Incoming contact messages only.",
        before_ar="حدد إن كنت تبحث عن متابعة تشغيلية أم عن سجل دعم.",
        before_en="Decide whether you need operational follow-up or a support record.",
        step1_ar="افتح رسائل التواصل لمراجعة القائمة.",
        step1_en="Open Contact Messages to review the list.",
        step2_ar="افتح الرسالة وراجع بيانات المرسل والتفاصيل.",
        step2_en="Open a message and review the sender and details.",
        step3_ar="ضع علامة تمت المعالجة إذا اكتمل الإجراء المطلوب.",
        step3_en="Mark it resolved when the requested action is complete.",
        expected_ar="تعرف الرسائل المفتوحة وما تم التعامل معه.",
        expected_en="You can see which messages remain open and which were handled.",
        status_defs_ar=["هذه الصفحة ليست نظام تذاكر وردود.", "الحالة تعني مفتوحة أو تمت معالجتها فقط."],
        status_defs_en=["This page is not a ticket reply system.", "The status is only open or resolved."],
        common_errors_ar=DEFAULT_ERRORS_AR,
        common_errors_en=DEFAULT_ERRORS_EN,
        privacy_ar="لا تضع فيها كلمات مرور أو بيانات طفل غير لازمة للمعالجة.",
        privacy_en="Do not place passwords or unnecessary child data in the response.",
        aliases_ar=["رسائل الاتصال"],
        aliases_en=["Inbound contact messages"],
    ),
    topic(
        id="imported-kindergartens",
        route="/admin/imported-kindergartens",
        title_ar="بيانات الحضانات المستوردة",
        title_en="Imported Kindergarten Data",
        purpose_ar="مراجعة السجلات المستوردة ومصدرها وتاريخها وحقولها الجغرافية.",
        purpose_en="Review imported kindergarten records, their source, date, and geographic fields.",
        who_ar="المسؤولون",
        who_en="Admins",
        scope_ar="صفوف المراجعة الناتجة عن الاستيراد.",
        scope_en="Review rows produced by the import job.",
        before_ar="تأكد من أن الاستيراد المقصود انتهى قبل المراجعة.",
        before_en="Confirm the intended import has finished before reviewing.",
        step1_ar="افتح قائمة البيانات المستوردة.",
        step1_en="Open the imported data list.",
        step2_ar="راجع المصدر والتاريخ والحقول الجغرافية أو الإدارية.",
        step2_en="Review the source, date, and geographic or administrative fields.",
        step3_ar="عد إلى سجل الاستيراد إذا احتجت إلى نتيجة الصفوف أو الأخطاء.",
        step3_en="Return to Import History if you need row counts or errors.",
        expected_ar="تظهر لك البيانات المستوردة كما وصلت من العملية.",
        expected_en="The imported data is shown as it arrived from the job.",
        status_defs_ar=["هذه صفحة مراجعة وليست صفحة تعديل.", "الصفوف المستوردة قد تكون منشأة أو متجاوزة أو بها خطأ."],
        status_defs_en=["This is a review page, not an edit page.", "Imported rows may be created, skipped, or errored."],
        common_errors_ar=DEFAULT_ERRORS_AR,
        common_errors_en=DEFAULT_ERRORS_EN,
        privacy_ar=DEFAULT_PRIVACY_AR,
        privacy_en=DEFAULT_PRIVACY_EN,
        aliases_ar=["البيانات المستوردة"],
        aliases_en=["Imported records"],
    ),
    topic(
        id="import-kindergartens",
        route="/admin/import-kindergartens",
        title_ar="استيراد الحضانات",
        title_en="Import Kindergartens",
        purpose_ar="رفع ملف Excel والتحقق منه قبل إنشاء سجلات الحضانات أو تحديثها.",
        purpose_en="Upload and validate an Excel file before creating or updating kindergarten records.",
        who_ar="المسؤولون",
        who_en="Admins",
        scope_ar="ملف واحد وعملية استيراد واحدة في كل مرة.",
        scope_en="One file and one import job at a time.",
        before_ar="تأكد من أن الملف يطابق الصيغة المدعومة وأن الأعمدة مكتملة.",
        before_en="Confirm the file matches the supported format and has the required columns.",
        step1_ar="ارفع ملف Excel وحدد نوع الاستيراد.",
        step1_en="Upload the Excel file and choose the import type.",
        step2_ar="راجع الأخطاء على مستوى الصفوف والملخص قبل التأكيد.",
        step2_en="Review row-level errors and the summary before confirming.",
        step3_ar="أكمل الاستيراد عندما تكون النتائج متوافقة مع ما تتوقعه.",
        step3_en="Complete the import when the results match what you expect.",
        expected_ar="تعرض الصفحة عدد الصفوف المنشأة والمحدّثة والمتجاوزة والخاطئة.",
        expected_en="The page shows created, updated, skipped, and errored row counts.",
        status_defs_ar=["الصيغ المدعومة محددة في الصفحة.", "المعاينة لا تتجاوز التحقق من الأعمدة والقيَم."],
        status_defs_en=["Supported formats are listed on the page.", "The preview does not bypass column and value validation."],
        common_errors_ar=["413 يعني أن الملف كبير جدًا.", "422 يعني أن البيانات أو الأعمدة غير صحيحة."],
        common_errors_en=["413 means the file is too large.", "422 means the data or columns are invalid."],
        privacy_ar="لا ترفع سوى البيانات التشغيلية المطلوبة للاستيراد.",
        privacy_en="Upload only the operational data required for the import.",
        aliases_ar=["استيراد الروضات"],
        aliases_en=["Kindergarten upload"],
    ),
    topic(
        id="import-history",
        route="/admin/import-logs",
        title_ar="سجل الاستيراد",
        title_en="Import History",
        purpose_ar="متابعة ملفات الاستيراد وأعداد الصفوف والأخطاء وحالة كل عملية.",
        purpose_en="Track import files, row counts, errors, and each job's status.",
        who_ar="المسؤولون",
        who_en="Admins",
        scope_ar="سجل عمليات الاستيراد السابقة.",
        scope_en="Past import jobs only.",
        before_ar="حدد نوع الاستيراد أو الفترة إذا كنت تبحث عن عملية محددة.",
        before_en="Choose the import type or period if you are looking for a specific job.",
        step1_ar="افتح سجل الاستيراد لمراجعة العمليات السابقة.",
        step1_en="Open Import History to review past jobs.",
        step2_ar="افحص حالة كل عملية وعدد الصفوف والأخطاء.",
        step2_en="Inspect each job's status, row counts, and errors.",
        step3_ar="افتح التفاصيل إذا احتجت لمعرفة سبب الفشل أو التجاوز.",
        step3_en="Open details if you need to see why a row failed or was skipped.",
        expected_ar="تتفهم لماذا نجحت العملية أو فشلت أو جزئيًا اكتملت.",
        expected_en="You can understand why a job succeeded, failed, or completed partially.",
        status_defs_ar=["الصفحة تعرض ملخصًا لكل عملية وليس كل صف بالتفصيل.", "القيم تعتمد على نوع الاستيراد."],
        status_defs_en=["The page shows a per-job summary rather than every row.", "Values depend on the import type."],
        common_errors_ar=DEFAULT_ERRORS_AR,
        common_errors_en=DEFAULT_ERRORS_EN,
        privacy_ar=DEFAULT_PRIVACY_AR,
        privacy_en=DEFAULT_PRIVACY_EN,
        aliases_ar=["تاريخ الاستيراد"],
        aliases_en=["Import log"],
    ),
    topic(
        id="incident-reports",
        route="/admin/reports/incidents",
        title_ar="تقارير الحوادث",
        title_en="Incident Reports",
        purpose_ar="البحث في التقارير التحليلية للحوادث وفتحها أو إنشاء تقرير جديد.",
        purpose_en="Search generated incident-analysis reports, open one, or create a new report.",
        who_ar="المسؤولون",
        who_en="Admins",
        scope_ar="تقارير الحوادث المنشأة فقط، وليس سجل الحوادث الحي.",
        scope_en="Generated incident reports only, not the live incident queue.",
        before_ar="حدد الفترة والنطاق قبل إنشاء تقرير جديد.",
        before_en="Choose the period and scope before creating a new report.",
        step1_ar="افتح تقارير الحوادث وابحث في التقرير المطلوب.",
        step1_en="Open Incident Reports and search for the report you need.",
        step2_ar="افتح تقريرًا موجودًا أو أنشئ تقريرًا جديدًا بالنطاق المطلوب.",
        step2_en="Open an existing report or create a new one with the chosen scope.",
        step3_ar="راجع الملخص والتحليلات قبل استخدام التقرير خارجيًا.",
        step3_en="Review the summary and analytics before using the report externally.",
        expected_ar="تصل إلى تقرير حادثة محدد مع نطاقه وفترته ونتيجته.",
        expected_en="You get a specific incident report with its scope, period, and result.",
        status_defs_ar=["هذا تقرير تحليلي وليس قائمة الحوادث الحية.", "الصفحة تعرض ما أنشئ بالفعل."],
        status_defs_en=["This is an analytical report, not the live incident queue.", "The page shows what has already been generated."],
        common_errors_ar=DEFAULT_ERRORS_AR,
        common_errors_en=DEFAULT_ERRORS_EN,
        privacy_ar="تعامل مع البيانات على أنها حساسة ولا تصدّرها إلا لغرض معتمد.",
        privacy_en="Treat the data as sensitive and export it only for an approved purpose.",
        aliases_ar=["تقرير الحادث"],
        aliases_en=["Incident analysis report"],
    ),
    topic(
        id="incident-analytics",
        route="/admin/safety-analytics",
        title_ar="تحليلات الحوادث",
        title_en="Incident Analytics",
        purpose_ar="عرض الملخصات التحليلية للحوادث المفتوحة والمغلقة والخطورة والتكرار وإبلاغ ولي الأمر.",
        purpose_en="Show analytical summaries of open/closed incidents, severity, recurrence, and parent notification.",
        who_ar="المسؤولون",
        who_en="Admins",
        scope_ar="الملخصات الناتجة من بيانات الحوادث المسجلة.",
        scope_en="Summaries generated from the recorded incident data.",
        before_ar="تحقق من الفترة والنطاق الجغرافي قبل تفسير المعدلات.",
        before_en="Check the period and geographic scope before interpreting rates.",
        step1_ar="افتح تحليلات الحوادث لمراجعة الحالة العامة.",
        step1_en="Open Incident Analytics to review the overall state.",
        step2_ar="راجع المفتوح والمغلق والخطورة والتكرار وإبلاغ ولي الأمر.",
        step2_en="Review open, closed, severity, recurrence, and parent-notification state.",
        step3_ar="استخدم الفلترة أو التفصيل إذا احتجت إلى منطقة أو حضانة محددة.",
        step3_en="Use filters or drill-down if you need a specific governorate or kindergarten.",
        expected_ar="تفهم إن كانت المشكلة عابرة أم متكررة وأين تتركز.",
        expected_en="You can tell whether the issue is isolated or recurring and where it clusters.",
        status_defs_ar=["النتائج هنا تحليلية وليست سجلًا مباشرًا.", "عدم كفاية التغطية يمنع استنتاجات مضللة."],
        status_defs_en=["Results here are analytical, not live records.", "Insufficient coverage prevents misleading conclusions."],
        common_errors_ar=DEFAULT_ERRORS_AR,
        common_errors_en=DEFAULT_ERRORS_EN,
        privacy_ar=DEFAULT_PRIVACY_AR,
        privacy_en=DEFAULT_PRIVACY_EN,
        aliases_ar=["تحليل الحادث"],
        aliases_en=["Safety analytics"],
    ),
    topic(
        id="heatmap",
        route="/admin/heatmap",
        title_ar="التحليل الجغرافي",
        title_en="Geographic Analysis / Heatmap",
        purpose_ar="استكشاف التغطية والمخاطر والحضانات والأطفال حسب المحافظة والمنطقة.",
        purpose_en="Explore coverage, risk, kindergartens, and children by governorate and area.",
        who_ar="المسؤولون",
        who_en="Admins",
        scope_ar="الخريطة والملخصات المشتقة من النطاق الجغرافي المختار.",
        scope_en="The map and summaries derived from the selected geographic scope.",
        before_ar="تأكد من أن الخريطة تعرض النطاق الصحيح قبل تفسير الألوان أو التجميع.",
        before_en="Confirm the map scope before interpreting colors or clustering.",
        step1_ar="افتح الخريطة الجغرافية لمراجعة التوزيع.",
        step1_en="Open the heatmap to review the distribution.",
        step2_ar="استخدم المحافظة أو المنطقة لتضييق النتائج.",
        step2_en="Use the governorate or area filter to narrow the results.",
        step3_ar="افتح التفاصيل إذا احتجت إلى تفسير سبب ارتفاع المخاطر أو الكثافة.",
        step3_en="Open details if you need to explain a risk or density spike.",
        expected_ar="تعرف المناطق التي تحتاج متابعة أو توزيعًا أفضل.",
        expected_en="You can identify the areas that need follow-up or better allocation.",
        status_defs_ar=["النتيجة تعتمد على النطاق المختار.", "الشرطة تعني أن القيمة غير متاحة في هذا العرض."],
        status_defs_en=["Results depend on the selected scope.", "A dash means the value is unavailable in this view."],
        common_errors_ar=DEFAULT_ERRORS_AR,
        common_errors_en=DEFAULT_ERRORS_EN,
        privacy_ar=DEFAULT_PRIVACY_AR,
        privacy_en=DEFAULT_PRIVACY_EN,
        aliases_ar=["الخريطة الحرارية"],
        aliases_en=["Heat map"],
    ),
    topic(
        id="analytics-overview",
        route="/admin/analytics",
        title_ar="نظرة عامة على التحليلات",
        title_en="Analytics Overview",
        purpose_ar="عرض الأداء والتسجيل والحضور والسلامة والحوكمة مع إظهار جودة البيانات وحداثتها.",
        purpose_en="Show performance, enrollment, attendance, safety, and governance with data quality and freshness.",
        who_ar="المسؤولون",
        who_en="Admins",
        scope_ar="التحليلات على مستوى المنصة والنطاق المحدد.",
        scope_en="Platform and selected-scope analytics.",
        before_ar="راجع البسط والمقام والفترة والنطاق والوحدة قبل الحكم على أي نسبة.",
        before_en="Review numerator, denominator, period, scope, and unit before judging any rate.",
        step1_ar="افتح نظرة عامة على التحليلات وحدد التقرير أو البطاقة المطلوبة.",
        step1_en="Open Analytics Overview and choose the report or card you need.",
        step2_ar="راجع جودة البيانات وحداثتها قبل اتخاذ أي قرار.",
        step2_en="Review data quality and freshness before making a decision.",
        step3_ar="استخدم التفصيل أو التقارير المرتبطة عندما تحتاج إلى تفسير أعمق.",
        step3_en="Use drill-down or linked reports when you need a deeper explanation.",
        expected_ar="يمكنك التمييز بين النتائج المقاسة والمخرجات التحليلية.",
        expected_en="You can distinguish measured results from analytical outputs.",
        status_defs_ar=["التحليلات ليست حقائق مرصودة كلها.", "النتائج الناقصة لا ينبغي أن تظهر كأصفار."],
        status_defs_en=["Not every analytical output is an observed fact.", "Missing results should not appear as zero."],
        common_errors_ar=DEFAULT_ERRORS_AR,
        common_errors_en=DEFAULT_ERRORS_EN,
        privacy_ar=DEFAULT_PRIVACY_AR,
        privacy_en=DEFAULT_PRIVACY_EN,
        aliases_ar=["ملخص التحليلات"],
        aliases_en=["Analytics summary"],
    ),
    topic(
        id="network-kpis",
        route="/admin/kpi",
        title_ar="مؤشرات أداء الشبكة",
        title_en="Network KPIs",
        purpose_ar="مقارنة الحضور والسلامة والحوكمة والالتزام بنسبة المشرفين إلى الأطفال بين الحضانات.",
        purpose_en="Compare attendance, safety, governance, and staff-to-child ratio compliance across kindergartens.",
        who_ar="المسؤولون",
        who_en="Admins",
        scope_ar="المؤشرات المجمعة للحضانات ضمن النطاق.",
        scope_en="Aggregated kindergarten indicators in the selected scope.",
        before_ar="تأكد من أن المؤشر في النافذة الزمنية المطلوبة قبل المقارنة.",
        before_en="Confirm the indicator window before comparing.",
        step1_ar="افتح مؤشرات الأداء لمراجعة البطاقات أو الجدول.",
        step1_en="Open the KPI page and review the cards or table.",
        step2_ar="راجع كل نسبة مع البسط والمقام والوحدة والتغطية.",
        step2_en="Review each rate with its numerator, denominator, unit, and coverage.",
        step3_ar="قارن بين الحضانات فقط عندما تكون التغطية كافية.",
        step3_en="Compare kindergartens only when coverage is sufficient.",
        expected_ar="ترى من يحتاج تدخلًا وما إذا كانت المقارنة عادلة.",
        expected_en="You can see who needs intervention and whether the comparison is fair.",
        status_defs_ar=["الصفحة تركز على النسب المعيارية.", "التغطية غير الكافية تمنع الترتيب المضلل."],
        status_defs_en=["The page focuses on standardized rates.", "Insufficient coverage prevents misleading ranking."],
        common_errors_ar=DEFAULT_ERRORS_AR,
        common_errors_en=DEFAULT_ERRORS_EN,
        privacy_ar=DEFAULT_PRIVACY_AR,
        privacy_en=DEFAULT_PRIVACY_EN,
        aliases_ar=["KPIs الشبكة", "أداء الشبكة"],
        aliases_en=["Network performance KPIs"],
    ),
    topic(
        id="reports-center",
        route="/admin/analytics/reports",
        title_ar="مركز التقارير",
        title_en="Reports Center",
        purpose_ar="إنشاء التقارير التشغيلية ومتابعة الصادرات والجداول المتاحة حسب الفئة والفترة والنطاق.",
        purpose_en="Generate operational reports and monitor exports and schedules by category, period, and scope.",
        who_ar="المسؤولون",
        who_en="Admins",
        scope_ar="التقارير التي تدعمها الصفحة الحالية فقط.",
        scope_en="Only the reports supported by the current page.",
        before_ar="اختر الفئة والفترة والنطاق الصحيح قبل التصدير.",
        before_en="Choose the correct category, period, and scope before exporting.",
        step1_ar="افتح مركز التقارير وحدد التقرير المطلوب.",
        step1_en="Open Reports Center and choose the report you need.",
        step2_ar="راجع الجدول المتاح والتصدير المدعوم لكل تقرير.",
        step2_en="Review the available schedule and the export supported by each report.",
        step3_ar="صدّر فقط الصيغ التي يعرضها التقرير الحالي.",
        step3_en="Export only the formats offered by the current report.",
        expected_ar="تعرف ما يمكن تشغيله الآن وما ينتظر أو فشل.",
        expected_en="You can see what can run now and what is pending or failed.",
        status_defs_ar=["الصيغ لا تتساوى بين التقارير.", "الجدول المدعوم يختلف حسب الفئة."],
        status_defs_en=["Formats are not identical across reports.", "Supported schedules vary by category."],
        common_errors_ar=DEFAULT_ERRORS_AR,
        common_errors_en=DEFAULT_ERRORS_EN,
        privacy_ar=DEFAULT_PRIVACY_AR,
        privacy_en=DEFAULT_PRIVACY_EN,
        aliases_ar=["مركز الإبلاغ"],
        aliases_en=["Report hub"],
    ),
    topic(
        id="decision-support",
        route="/admin/analytics/decision-support",
        title_ar="دعم القرار",
        title_en="Decision Support",
        purpose_ar="مقارنة الموارد والطاقة وجودة البيانات والالتزام والمخاطر لتحديد فجوات التشغيل.",
        purpose_en="Compare resources, capacity, data quality, compliance, and risk to identify operating gaps.",
        who_ar="المسؤولون",
        who_en="Admins",
        scope_ar="النتائج التحليلية التي تساعد على تحديد الأولوية.",
        scope_en="Analytical outputs that help set priorities.",
        before_ar="راجع مصدر البيانات والتغطية قبل استخدام أي توصية أو فجوة.",
        before_en="Review the data source and coverage before using any recommendation or gap.",
        step1_ar="افتح دعم القرار لمراجعة الفجوات أو التوصيات.",
        step1_en="Open Decision Support to review gaps or recommendations.",
        step2_ar="تأكد من أن النطاق والتغطية كافيان قبل المقارنة.",
        step2_en="Confirm that the scope and coverage are sufficient before comparing.",
        step3_ar="استخدم النتائج لتحديد ترتيب المتابعة لا لتفسيرها كحكم نهائي.",
        step3_en="Use the results to prioritize follow-up, not as a final judgment.",
        expected_ar="تصل إلى قائمة أولويات مدعومة بالبيانات.",
        expected_en="You get a data-backed priority list.",
        status_defs_ar=["هذه توصية تحليلية وليست قرارًا آليًا.", "الحدود الضعيفة لا ينبغي أن تنتج ترتيبًا نهائيًا."],
        status_defs_en=["This is an analytical recommendation, not an automatic decision.", "Weak coverage should not produce a final rank."],
        common_errors_ar=DEFAULT_ERRORS_AR,
        common_errors_en=DEFAULT_ERRORS_EN,
        privacy_ar=DEFAULT_PRIVACY_AR,
        privacy_en=DEFAULT_PRIVACY_EN,
        aliases_ar=["دعم القرار التحليلي"],
        aliases_en=["Decision intelligence"],
    ),
    topic(
        id="daily-report-organization",
        route="/admin/daily-reports-organization",
        title_ar="تنظيم التقارير اليومية",
        title_en="Daily Report Organization",
        purpose_ar="البحث في التقارير اليومية وتجميعها وفرزها ومراجعتها.",
        purpose_en="Search, group, sort, and review daily reports.",
        who_ar="المسؤولون",
        who_en="Admins",
        scope_ar="تقارير يومية موجودة فقط، وليس جداول الإرسال.",
        scope_en="Existing daily reports only, not send schedules.",
        before_ar="حدد التاريخ والحضانة قبل التصفية.",
        before_en="Choose the date and kindergarten before filtering.",
        step1_ar="افتح تنظيم التقارير اليومية وحدد الفترة أو الحضانة.",
        step1_en="Open Daily Report Organization and choose the period or kindergarten.",
        step2_ar="رتّب النتائج أو اجمعها أو ابحث فيها حسب الحاجة.",
        step2_en="Sort, group, or search the results as needed.",
        step3_ar="افتح التقرير للمراجعة دون توقع إنشاء جدول إرسال.",
        step3_en="Open the report for review without expecting schedule creation.",
        expected_ar="تصل إلى التقرير المناسب وتراجع حالته بسرعة.",
        expected_en="You can reach the right report and review its state quickly.",
        status_defs_ar=["الصفحة لا تنشئ جداول إرسال.", "الحالة تعتمد على التقرير الظاهر."],
        status_defs_en=["This page does not create send schedules.", "Status depends on the report shown."],
        common_errors_ar=DEFAULT_ERRORS_AR,
        common_errors_en=DEFAULT_ERRORS_EN,
        privacy_ar=DEFAULT_PRIVACY_AR,
        privacy_en=DEFAULT_PRIVACY_EN,
        aliases_ar=["تنظيم التقارير"],
        aliases_en=["Daily report review"],
    ),
    topic(
        id="daily-reports-analytics",
        route="/reports/analytics",
        title_ar="تحليلات التقارير اليومية",
        title_en="Daily Reports Analytics",
        purpose_ar="عرض التحليلات التشغيلية للتقارير اليومية حسب الفترة والحضانة.",
        purpose_en="Show operational daily-report analytics by period and kindergarten.",
        who_ar="المسؤولون",
        who_en="Admins",
        scope_ar="الملخصات التحليلية للتقارير اليومية.",
        scope_en="Analytical summaries of daily reports.",
        before_ar="راجع الفترة والنطاق قبل تفسير أي نسبة أو متوسط.",
        before_en="Check the period and scope before interpreting a rate or average.",
        step1_ar="افتح تحليلات التقارير اليومية.",
        step1_en="Open Daily Reports Analytics.",
        step2_ar="راجع المؤشرات المتاحة مثل الحضور والطعام والقيلولة والمؤشرات الصحية.",
        step2_en="Review the available indicators such as attendance, meals, naps, and health.",
        step3_ar="صدّر فقط الصيغ التي يتيحها التقرير الحالي.",
        step3_en="Export only the formats supported by the current report.",
        expected_ar="تتضح لك صورة الأداء اليومي ومواضع الخلل.",
        expected_en="You can see daily performance and where the gaps are.",
        status_defs_ar=["التحليلات تختلف عن سجل التنظيم.", "القيم المفقودة لا ينبغي أن تظهر كأصفار."],
        status_defs_en=["Analytics are different from the organization list.", "Missing values should not be shown as zero."],
        common_errors_ar=DEFAULT_ERRORS_AR,
        common_errors_en=DEFAULT_ERRORS_EN,
        privacy_ar=DEFAULT_PRIVACY_AR,
        privacy_en=DEFAULT_PRIVACY_EN,
        aliases_ar=["تحليلات اليوميات"],
        aliases_en=["Daily report dashboard"],
    ),
    topic(
        id="charts-explorer",
        route="/admin/analytics/charts",
        title_ar="مستكشف الرسوم البيانية",
        title_en="Charts Explorer",
        purpose_ar="إنشاء عرض بصري لمؤشر واحد ضمن النطاق المختار.",
        purpose_en="Build a visualization for one metric within the selected scope.",
        who_ar="المسؤولون",
        who_en="Admins",
        scope_ar="الرسم والبيانات المصدر التي اختيرت له.",
        scope_en="The chart and the source data selected for it.",
        before_ar="تحقق من الوحدة والفترة وعدد الصفوف قبل تفسير الرسم.",
        before_en="Check the unit, period, and row count before interpreting the chart.",
        step1_ar="افتح مستكشف الرسوم وحدد المؤشر والمصدر.",
        step1_en="Open Charts Explorer and choose the metric and source.",
        step2_ar="راجع الرسم والجدول المرافق لفهم grain والمرشحات.",
        step2_en="Review the chart and its table to understand the grain and filters.",
        step3_ar="استخدم التنزيل أو الرجوع إلى التقرير عندما تحتاج إلى مشاركة أوسع.",
        step3_en="Use download or return to the report when you need broader sharing.",
        expected_ar="ترى الرسم المناسب للمؤشر المختار مع بياناته المساندة.",
        expected_en="You see the right chart for the selected metric along with supporting data.",
        status_defs_ar=["الرسم يعتمد على الحقلين المختارين.", "اللون أو السلسلة تظهر فقط عند وجود تجميع حقيقي."],
        status_defs_en=["The chart depends on the selected fields.", "Color or series only appears for a real grouping."],
        common_errors_ar=DEFAULT_ERRORS_AR,
        common_errors_en=DEFAULT_ERRORS_EN,
        privacy_ar=DEFAULT_PRIVACY_AR,
        privacy_en=DEFAULT_PRIVACY_EN,
        aliases_ar=["مستكشف المخططات", "الرسوم البيانية"],
        aliases_en=["Chart explorer", "Charts dashboard"],
    ),
    topic(
        id="daily-report-governance",
        route="/admin/governance-reports",
        title_ar="حوكمة التقارير اليومية",
        title_en="Daily Report Governance",
        purpose_ar="قياس الإكمال والتسليم والمشاهدة والقبول في الوقت المناسب ودعم التذكير.",
        purpose_en="Measure completion, delivery, viewing, timely acceptance, and reminder follow-up.",
        who_ar="المسؤولون",
        who_en="Admins",
        scope_ar="نسب الحوكمة الخاصة بالتقارير اليومية.",
        scope_en="Governance rates for daily reports.",
        before_ar="راجع البسط والمقام والنافذة الزمنية قبل استخلاص الحكم.",
        before_en="Review numerator, denominator, and time window before drawing conclusions.",
        step1_ar="افتح صفحة الحوكمة وحدد النطاق والفترة.",
        step1_en="Open the governance page and set the scope and period.",
        step2_ar="راجع نسبة التقديم والتسليم والمشاهدة والقبول.",
        step2_en="Review submission, delivery, view, and acceptance rates.",
        step3_ar="استخدم صفحة التذكيرات لتتبع الإرسال وليس الإنشاء.",
        step3_en="Use the reminders page to track sending, not creation.",
        expected_ar="تفهم مدى التزام الحضور والقبول والمتابعة.",
        expected_en="You can understand submission and acceptance compliance and follow-up.",
        status_defs_ar=["الصفحة تعرض النسب حسب تعريفها الظاهر.", "النتائج المنخفضة التغطية لا يجب أن تُفسر كفشل عام."],
        status_defs_en=["The page shows rates according to the visible definitions.", "Low-coverage results should not be treated as a general failure."],
        common_errors_ar=DEFAULT_ERRORS_AR,
        common_errors_en=DEFAULT_ERRORS_EN,
        privacy_ar=DEFAULT_PRIVACY_AR,
        privacy_en=DEFAULT_PRIVACY_EN,
        aliases_ar=["حوكمة اليوميات"],
        aliases_en=["Governance metrics"],
    ),
    topic(
        id="compliance-reminders",
        route="/admin/governance/reminders",
        title_ar="تذكيرات الالتزام",
        title_en="Compliance Reminders",
        purpose_ar="مراجعة سجل إرسال التذكيرات المرتبطة بحوكمة التقارير اليومية.",
        purpose_en="Review the sending history for reminders tied to daily-report governance.",
        who_ar="المسؤولون",
        who_en="Admins",
        scope_ar="سجل التذكيرات المرسلة فقط.",
        scope_en="Sent reminder history only.",
        before_ar="حدّد الفترة قبل البحث في سجل الإرسال.",
        before_en="Set the period before searching the sending history.",
        step1_ar="افتح التذكيرات وراجع السجل.",
        step1_en="Open Compliance Reminders and review the history.",
        step2_ar="افحص من أُرسل له التذكير ومتى.",
        step2_en="Check who received the reminder and when.",
        step3_ar="ارجع إلى الحوكمة إذا احتجت لمعرفة من كان مؤهلًا للتذكير.",
        step3_en="Return to governance if you need to know who was eligible for a reminder.",
        expected_ar="تعرف ما أُرسل ومتى ولأي نطاق.",
        expected_en="You can see what was sent, when, and for which scope.",
        status_defs_ar=["هذه الصفحة تعرض سجل الإرسال وليس زر الإرسال.", "الإرسال نفسه يبدأ من تقرير الحوكمة."],
        status_defs_en=["This page shows sending history, not the send action.", "The send action starts from the governance report."],
        common_errors_ar=DEFAULT_ERRORS_AR,
        common_errors_en=DEFAULT_ERRORS_EN,
        privacy_ar=DEFAULT_PRIVACY_AR,
        privacy_en=DEFAULT_PRIVACY_EN,
        aliases_ar=["سجل التذكير"],
        aliases_en=["Reminder log"],
    ),
    topic(
        id="classification-benchmarks",
        route="/admin/classification",
        title_ar="التصنيف والمقارنات",
        title_en="Classification & Benchmarks",
        purpose_ar="مقارنة الجهات بمؤشرات موحّدة مع إظهار التغطية والاتجاه وحدود العدالة.",
        purpose_en="Compare entities using consistent indicators with coverage, trend, and fairness limits.",
        who_ar="المسؤولون",
        who_en="Admins",
        scope_ar="الجهات المصنفة فقط مع التغطية الكافية.",
        scope_en="Ranked entities with sufficient coverage only.",
        before_ar="تحقق من التغطية قبل التعامل مع الترتيب على أنه نهائي.",
        before_en="Check coverage before treating the ranking as final.",
        step1_ar="افتح صفحة التصنيف وحدد النطاق أو الفئة.",
        step1_en="Open Classification and choose the scope or category.",
        step2_ar="راجع الدرجة والتغطية والاتجاه معًا.",
        step2_en="Review the score, coverage, and trend together.",
        step3_ar="استبعد الترتيب عندما تكون التغطية غير كافية.",
        step3_en="Ignore the ranking when coverage is insufficient.",
        expected_ar="تتعرف على المواقع المتقدمة والمتأخرة ضمن مقارنة عادلة.",
        expected_en="You can identify leaders and laggards in a fair comparison.",
        status_defs_ar=["الترتيب لا ينبغي أن يظهر عند ضعف التغطية.", "التصنيف يشرح مكوّن الدرجة وليس الرقم فقط."],
        status_defs_en=["Ranking should not appear when coverage is weak.", "Classification should explain the score composition, not just the number."],
        common_errors_ar=DEFAULT_ERRORS_AR,
        common_errors_en=DEFAULT_ERRORS_EN,
        privacy_ar=DEFAULT_PRIVACY_AR,
        privacy_en=DEFAULT_PRIVACY_EN,
        aliases_ar=["المقارنات", "الترتيب"],
        aliases_en=["Benchmarks", "Ranking"],
    ),
    topic(
        id="official-agency-reports",
        route="/admin/agency-reports",
        title_ar="تقارير الجهات الرسمية",
        title_en="Official Agency Reports",
        purpose_ar="اختيار الجهة والتقرير ومراجعة جاهزية البيانات أو إنشاء تقرير مصرح به.",
        purpose_en="Select an agency and report, review data readiness, or create an allowed report.",
        who_ar="المسؤولون",
        who_en="Admins",
        scope_ar="التقارير المعتمدة والجهات المتاحة في الصفحة الحالية.",
        scope_en="Approved reports and agencies available on the current page.",
        before_ar="تحقق من الخصوصية والتغطية والتصريح قبل التصدير.",
        before_en="Check privacy, coverage, and authorization before exporting.",
        step1_ar="افتح تقارير الجهات الرسمية واختر الجهة أو التقرير.",
        step1_en="Open Official Agency Reports and choose the agency or report.",
        step2_ar="راجع النطاق والجاهزية والمخرجات المتاحة.",
        step2_en="Review the scope, readiness, and available outputs.",
        step3_ar="صدّر فقط إذا كان التقرير مصرحًا والاستخدام محددًا.",
        step3_en="Export only if the report is authorized and the use is defined.",
        expected_ar="تعرف ما هو جاهز الآن وما يحتاج تنسيق بيانات إضافيًا.",
        expected_en="You can see what is ready now and what still needs structured data.",
        status_defs_ar=["الصيغ المتاحة تختلف حسب التقرير.", "لا تفترض أن كل تقرير يدعم CSV."],
        status_defs_en=["Available formats vary by report.", "Do not assume every report supports CSV."],
        common_errors_ar=DEFAULT_ERRORS_AR,
        common_errors_en=DEFAULT_ERRORS_EN,
        privacy_ar="اتبع قواعد الإخفاء والتجميع عند وجود بيانات طفل أو نطاق حساس.",
        privacy_en="Follow suppression and aggregation rules when child-level or sensitive scope is involved.",
        aliases_ar=["تقارير الجهة الرسمية"],
        aliases_en=["Agency reports"],
    ),
    topic(
        id="audit-log",
        route="/admin/audit-logs",
        title_ar="سجل التدقيق",
        title_en="Audit Log",
        purpose_ar="البحث في الإجراءات والتغييرات الإدارية والأمنية بحسب الفاعل والفعل والوقت والرقم المرجعي.",
        purpose_en="Search administrative and security actions by actor, action, time, and reference ID.",
        who_ar="المسؤولون",
        who_en="Admins",
        scope_ar="أحداث التدقيق المخزنة فقط.",
        scope_en="Stored audit events only.",
        before_ar="حدد الفلتر أو الفترة قبل التصدير أو المراجعة.",
        before_en="Set the filter or period before exporting or reviewing.",
        step1_ar="افتح سجل التدقيق وحدد المرشحات المطلوبة.",
        step1_en="Open the Audit Log and set the required filters.",
        step2_ar="افحص الفاعل والإجراء والوقت والرقم المرجعي.",
        step2_en="Check the actor, action, time, and reference ID.",
        step3_ar="صدّر السجل إذا احتجت إلى مشاركة داخلية مصرح بها.",
        step3_en="Export the log if you need approved internal sharing.",
        expected_ar="تتمكن من تتبع من فعل ماذا ومتى.",
        expected_en="You can trace who did what and when.",
        status_defs_ar=["التحقيق يبدأ من سجل التدقيق وليس من التقدير.", "الرقم المرجعي يربط الطلب بسجلات الخادم."],
        status_defs_en=["Investigation starts from the audit log, not from guesswork.", "The reference ID ties the request back to server logs."],
        common_errors_ar=DEFAULT_ERRORS_AR,
        common_errors_en=DEFAULT_ERRORS_EN,
        privacy_ar="لا تُشارك سجلات التدقيق خارج الحالة المصرح بها.",
        privacy_en="Do not share audit logs outside an approved case.",
        aliases_ar=["سجل المراجعة"],
        aliases_en=["Activity log"],
    ),
    topic(
        id="controlled-user-access",
        route="/admin/impersonate",
        title_ar="الدخول المقيّد بصفة مستخدم",
        title_en="Controlled User Access",
        purpose_ar="الدخول المؤقت لحساب مدير لحالة دعم معتمدة مع تسجيل السبب والبدء والانتهاء.",
        purpose_en="Temporarily access a manager account for an approved support case with reason, start, and end recorded.",
        who_ar="المسؤولون المخوّلون فقط",
        who_en="Authorized admins only",
        scope_ar="حالات الدعم المعتمدة فقط.",
        scope_en="Approved support cases only.",
        before_ar="تأكد من وجود موافقة واضحة وسبب محدد قبل البدء.",
        before_en="Confirm there is explicit approval and a defined reason before starting.",
        step1_ar="افتح صفحة الدخول المقيّد وحدد الحساب المستهدف.",
        step1_en="Open Controlled User Access and choose the target account.",
        step2_ar="سجّل السبب وابدأ الجلسة المؤقتة.",
        step2_en="Record the reason and start the temporary session.",
        step3_ar="أنهِ الجلسة بمجرد انتهاء الحاجة التشخيصية.",
        step3_en="End the session as soon as the diagnostic need is done.",
        expected_ar="يُسجل البدء والانتهاء والسبب ويمكن التراجع بسرعة.",
        expected_en="Start, end, and reason are recorded, and the access can be closed quickly.",
        status_defs_ar=["هذه أداة دعم استثنائية وليست وضع عمل دائم.", "السبب والتوقيت جزء من سجل التدقيق."],
        status_defs_en=["This is an exceptional support tool, not a normal operating mode.", "Reason and timing are part of the audit trail."],
        common_errors_ar=DEFAULT_ERRORS_AR,
        common_errors_en=DEFAULT_ERRORS_EN,
        privacy_ar="لا تستخدم هذه الأداة إلا للحالات المعتمدة ولا تنقل رموزًا أو كلمات مرور.",
        privacy_en="Use this tool only for approved cases and do not transfer tokens or passwords.",
        aliases_ar=["الانتحال المقيّد", "الدخول كمدير"],
        aliases_en=["Impersonation", "Support access"],
    ),
    topic(
        id="admin-profile",
        route="/admin/profile",
        title_ar="الملف الشخصي للمسؤول",
        title_en="Admin Profile",
        purpose_ar="مراجعة حساب المسؤول وأمانه وصلاحياته ونشاطه والبيانات القابلة للتعديل.",
        purpose_en="Review the Admin account, security, permissions, activity, and editable profile data.",
        who_ar="المسؤولون",
        who_en="Admins",
        scope_ar="الحساب الحالي فقط.",
        scope_en="The current account only.",
        before_ar="تحقق من الجلسة الحالية قبل تغيير كلمة المرور أو البيانات.",
        before_en="Confirm the current session before changing the password or profile data.",
        step1_ar="افتح الملف الشخصي للمسؤول لمراجعة البيانات.",
        step1_en="Open the Admin Profile to review the account data.",
        step2_ar="راجع الأمان والنشاط وتاريخ آخر دخول.",
        step2_en="Review security, activity, and the last login date.",
        step3_ar="عدّل ما هو مسموح فقط ثم احفظ.",
        step3_en="Edit only what is allowed and then save.",
        expected_ar="تفهم حالة حسابك وما يمكنك تعديله.",
        expected_en="You understand the state of your account and what you can edit.",
        status_defs_ar=["هذا عرض حسابي وليس مركز إعدادات عام.", "الملف الشخصي يعرض الأعمار والنشاط والتدقيق."],
        status_defs_en=["This is an account view, not a global settings center.", "The profile shows age, activity, and audit information."],
        common_errors_ar=DEFAULT_ERRORS_AR,
        common_errors_en=DEFAULT_ERRORS_EN,
        privacy_ar=DEFAULT_PRIVACY_AR,
        privacy_en=DEFAULT_PRIVACY_EN,
        aliases_ar=["ملف المسؤول"],
        aliases_en=["Account profile"],
    ),
    topic(
        id="system-settings",
        route="/admin/settings",
        title_ar="إعدادات النظام",
        title_en="System Settings",
        purpose_ar="عرض مهلة الجلسة ومعلومات البيئة التي يديرها الخادم.",
        purpose_en="View session timeout and server-managed environment information.",
        who_ar="المسؤولون",
        who_en="Admins",
        scope_ar="القيم المقروءة فقط التي يزودها الخادم.",
        scope_en="Read-only values provided by the server.",
        before_ar="توقع العرض فقط وليس الحفظ أو التعديل.",
        before_en="Expect display only, not saving or editing.",
        step1_ar="افتح إعدادات النظام لمراجعة القيم المعروضة.",
        step1_en="Open System Settings to review the displayed values.",
        step2_ar="تحقق من مهلة الجلسة وأي معلومات بيئية ظاهرة.",
        step2_en="Check the session timeout and any visible environment information.",
        step3_ar="ارجع إلى جهة الإعداد المصرح بها إذا احتجت تغييرًا فعليًا.",
        step3_en="Return to the authorized configuration source if you need a real change.",
        expected_ar="تعرف الإعدادات التي يعرضها الخادم فقط.",
        expected_en="You can see only the settings the server exposes.",
        status_defs_ar=["هذه الصفحة للقراءة فقط.", "لا توجد هنا تغييرات معلّقة أو محفوظة."],
        status_defs_en=["This page is read only.", "There are no pending or saved changes here."],
        common_errors_ar=DEFAULT_ERRORS_AR,
        common_errors_en=DEFAULT_ERRORS_EN,
        privacy_ar=DEFAULT_PRIVACY_AR,
        privacy_en=DEFAULT_PRIVACY_EN,
        aliases_ar=["إعدادات المسؤول"],
        aliases_en=["Settings"],
    ),
    topic(
        id="help-center",
        route="/admin/help",
        title_ar="مركز المساعدة",
        title_en="Help Center",
        purpose_ar="إرشادات موثقة للمهام الإدارية وفهم المؤشرات ومعالجة المشكلات.",
        purpose_en="Verified guidance for administrative tasks, metric interpretation, and troubleshooting.",
        who_ar="كل المسؤولين المصرح لهم",
        who_en="All authorized admins",
        scope_ar="الموضوعات والروابط والمصطلحات الموثقة في هذه الصفحة.",
        scope_en="The topics, links, and terms documented on this page.",
        before_ar="استخدم البحث أو جدول التغطية للانتقال إلى الموضوع الصحيح.",
        before_en="Use the search or coverage table to jump to the right topic.",
        step1_ar="اكتب اسم الصفحة أو المهمة أو المصطلح في البحث.",
        step1_en="Type a page name, task, or term into the search box.",
        step2_ar="افتح الموضوع أو الرابط المباشر المطابق.",
        step2_en="Open the matching topic or direct link.",
        step3_ar="استخدم الدعم أو سجل التدقيق عند الحاجة إلى تصعيد.",
        step3_en="Use support or the audit log when you need escalation.",
        expected_ar="تصل بسرعة إلى شرح المهمة أو المصطلح المطلوب.",
        expected_en="You can quickly reach the task or term explanation you need.",
        status_defs_ar=["لا توجد مؤشرات في هذه الصفحة.", "استخدم البحث والموضوعات للوصول إلى الإرشاد المناسب."],
        status_defs_en=["This page has no KPIs.", "Use search and topics to find the relevant guidance."],
        common_errors_ar=DEFAULT_ERRORS_AR,
        common_errors_en=DEFAULT_ERRORS_EN,
        privacy_ar=DEFAULT_PRIVACY_AR,
        privacy_en=DEFAULT_PRIVACY_EN,
        aliases_ar=["المساعدة", "الدليل الإداري"],
        aliases_en=["Support guide", "Admin guide"],
    ),
]


for item in HELP_CENTER_TOPICS:
    item["search_terms"] = make_search_blob(
        item["title"],
        item["aliases"],
        item["purpose"],
        item["who"],
        item["scope"],
        item["before"],
        item["steps"],
        item["expected"],
        item["status_defs"],
        item["common_errors"],
        item["privacy"],
        item["route"],
    )


HELP_CENTER_COVERAGE = [
    {"id": item["id"], "route": item["route"], "title": item["title"], "status": item["status"]}
    for item in HELP_CENTER_TOPICS
]


HELP_CENTER_GLOSSARY = [
    {"term": bi("النطاق", "Scope"), "meaning": bi("الجهات أو السجلات المشمولة في النتيجة.", "The organizations, locations, or records included in a result.")},
    {"term": bi("التغطية", "Coverage"), "meaning": bi("نسبة البيانات المتوقعة المتاحة للحساب.", "The share of expected data available for calculation.")},
    {"term": bi("حداثة البيانات", "Freshness"), "meaning": bi("وقت آخر تحديث ناجح للبيانات المصدرية.", "When the source data was last updated successfully.")},
    {"term": bi("الرقم المرجعي", "Reference ID"), "meaning": bi("معرّف يربط طلب المتصفح بسجلات الخادم.", "An identifier that correlates a browser request with server logs.")},
    {"term": bi("البسط", "Numerator"), "meaning": bi("الجزء المحسوب في النسبة.", "The counted part of a rate or fraction.")},
    {"term": bi("المقام", "Denominator"), "meaning": bi("المجموعة المرجعية التي تُقسَّم عليها القيمة.", "The reference group used as the divisor.")},
    {"term": bi("فترة القياس", "Measurement period"), "meaning": bi("النافذة الزمنية التي تُحتسب خلالها القيمة.", "The time window used to compute the value.")},
    {"term": bi("جودة البيانات", "Data quality"), "meaning": bi("مدى اكتمال البيانات وصلاحيتها للاعتماد.", "How complete and reliable the underlying data is.")},
    {"term": bi("بيانات غير كافية", "Insufficient data"), "meaning": bi("تغطية لا تكفي لنتيجة موثوقة أو لترتيب عادل.", "Coverage too low for a reliable result or fair ranking.")},
    {"term": bi("معيار مقارنة", "Benchmark"), "meaning": bi("قيمة أو نطاق مرجعي للمقارنة.", "A reference value or range used for comparison.")},
    {"term": bi("المئين", "Percentile"), "meaning": bi("موضع القيمة ضمن توزيع القيم.", "The position of a value within a distribution.")},
    {"term": bi("التصنيف", "Classification"), "meaning": bi("إسناد جهة إلى فئة أو درجة محددة.", "Assigning an entity to a specific category or band.")},
    {"term": bi("التنبؤ", "Forecast"), "meaning": bi("تقدير تحليلي للمستقبل وليس حقيقة مرصودة.", "An analytical estimate of a future state, not an observed fact.")},
    {"term": bi("الشذوذ", "Anomaly"), "meaning": bi("قيمة أو نمط غير معتاد يستحق المراجعة.", "An unusual value or pattern that deserves review.")},
    {"term": bi("درجة المخاطر", "Risk score"), "meaning": bi("مؤشر يعبّر عن احتمال أو أثر غير مرغوب.", "An indicator of likelihood or impact of an undesirable outcome.")},
    {"term": bi("الخطورة", "Severity"), "meaning": bi("أولوية المعالجة أو شدة التنبيه.", "The urgency or intensity of an alert or issue.")},
    {"term": bi("اتفاقية مستوى الخدمة", "SLA"), "meaning": bi("الحد الزمني أو التشغيلي المتوقع للخدمة.", "The expected service-level time or operating threshold.")},
    {"term": bi("معدل الحضور", "Attendance rate"), "meaning": bi("الحضور الفعلي مقسومًا على المتوقع.", "Actual attendance divided by expected attendance.")},
    {"term": bi("استغلال الطاقة", "Capacity utilization"), "meaning": bi("النسبة بين العدد الفعلي والسعة المتاحة.", "The ratio of actual count to available capacity.")},
    {"term": bi("درجة الحوكمة", "Governance score"), "meaning": bi("مؤشر مركب لالتزام التقارير أو المتابعة.", "A composite indicator of reporting or compliance behavior.")},
    {"term": bi("مسودة", "Draft"), "meaning": bi("حالة غير نهائية قابلة للتعديل.", "A non-final state that can still be edited.")},
    {"term": bi("مُرسل", "Sent"), "meaning": bi("تم الإرسال بنجاح إلى المستلمين المقصودين.", "Successfully sent to the intended recipients.")},
    {"term": bi("مُعتمد", "Approved"), "meaning": bi("تمت الموافقة عليه للمضي أو الإرسال.", "Approved to proceed or to be sent.")},
    {"term": bi("تم الإرسال إلى ولي الأمر", "Sent to Parent"), "meaning": bi("وصلت الرسالة أو التقرير إلى ولي الأمر.", "The message or report reached the parent.")},
    {"term": bi("مرفوض", "Rejected"), "meaning": bi("لم يمر الإجراء أو السجل بالتحقق المطلوب.", "The action or record did not pass validation.")},
    {"term": bi("مُعاد", "Returned"), "meaning": bi("أعيد للتعديل أو المراجعة قبل الإكمال.", "Sent back for correction or review before completion.")},
    {"term": bi("نشط", "Active"), "meaning": bi("الحالة الحالية المفعلة والقابلة للاستخدام.", "The current enabled and usable state.")},
    {"term": bi("مجمَّد", "Frozen"), "meaning": bi("الحالة الموقوفة مؤقتًا دون حذف.", "Temporarily stopped without deletion.")},
    {"term": bi("محذوف", "Deleted"), "meaning": bi("أزيل من العرض أو السجل بحسب السياسة.", "Removed from view or the record according to policy.")},
]


HELP_CENTER_FAQS = [
    {
        "question": bi("لماذا لا أرى صفحة إدارية؟", "Why can't I see an admin page?"),
        "answer": bi("تحقق من الجلسة والدور. الخادم يفرض الصلاحية حتى عندما يكون الرابط معروفًا.", "Check your session and role. The server enforces access even when the URL is known."),
    },
    {
        "question": bi("ماذا يعني 403؟", "What does 403 mean?"),
        "answer": bi("إما أن الدور أو النطاق لا يسمح بالإجراء، أو أن التحقق الأمني للطلب المعدِّل فشل.", "Either the role or scope does not allow the action, or the write request failed security validation."),
    },
    {
        "question": bi("ماذا يعني 404؟", "What does 404 mean?"),
        "answer": bi("السجل غير متاح في نطاقك أو غير موجود في هذا العرض.", "The record is unavailable within your scope or does not exist in this view."),
    },
    {
        "question": bi("كيف أفسر نسبة؟", "How should I interpret a rate?"),
        "answer": bi("راجع البسط والمقام والفترة والنطاق والوحدة والتغطية.", "Review the numerator, denominator, period, scope, unit, and coverage."),
    },
    {
        "question": bi("هل المعاينة نهائية؟", "Is the preview count final?"),
        "answer": bi("لا. الخادم يعيد حساب المستلمين عند الإرسال.", "No. The server recalculates recipients when sending."),
    },
    {
        "question": bi("أين أجد رسائل التواصل؟", "Where are contact messages?"),
        "answer": bi("من التواصل والبيانات ← رسائل التواصل.", "Open Communication & Data → Contact Messages."),
    },
    {
        "question": bi("هل يمكنني الرد على رسالة تواصل؟", "Can I reply to a contact message?"),
        "answer": bi("الصفحة الحالية تتيح المراجعة ووضع علامة تمت المعالجة، ولا توفر نظام ردود.", "The current page supports review and resolution state, not a reply workflow."),
    },
    {
        "question": bi("أين تحليلات التقارير اليومية؟", "Where is the Daily Reports Analytics page?"),
        "answer": bi("من التحليلات والتقارير ← تحليلات التقارير اليومية.", "Open Analytics & Reporting → Daily Reports Analytics."),
    },
    {
        "question": bi("هل تنظيم التقارير ينشئ جدولًا؟", "Does Daily Report Organization create schedules?"),
        "answer": bi("لا. الصفحة تبحث وتجمع وتفرز وتراجع التقارير فقط.", "No. The page searches, groups, sorts, and reviews reports only."),
    },
    {
        "question": bi("ما الفرق بين الحادث وتقرير الحادث؟", "What is the difference between an incident and an incident report?"),
        "answer": bi("الحادث سجل تشغيلي؛ أما التقرير فهو لقطة تحليلية منشأة.", "An incident is an operational record; a report is a generated analytical snapshot."),
    },
    {
        "question": bi("ماذا تعني بيانات غير كافية؟", "What does insufficient data mean?"),
        "answer": bi("التغطية لا تكفي لنتيجة موثوقة أو ترتيب عادل.", "Coverage is too low for a reliable result or fair ranking."),
    },
    {
        "question": bi("أين أرسل تذكير الحوكمة؟", "Where do I send a governance reminder?"),
        "answer": bi("من صفحة حوكمة التقارير اليومية؛ صفحة التذكيرات تعرض سجل الإرسال.", "Use Daily Report Governance; the reminders page shows sending history."),
    },
    {
        "question": bi("أين أصدّر سجل التدقيق؟", "Where do I export audit logs?"),
        "answer": bi("من صفحة سجل التدقيق بعد اختيار المرشحات والفترة.", "From Audit Log after selecting filters and period."),
    },
    {
        "question": bi("كيف أطلب الدعم؟", "How do I request support?"),
        "answer": bi("استخدم قناة الدعم المعتمدة في مؤسستك وأرفق الرقم المرجعي دون مشاركة كلمات المرور أو الرموز.", "Use your organization's approved support channel and include the reference ID without sharing passwords or tokens."),
    },
]
