"""
Translations module stub
"""
from typing import Callable


def setup_translator(language: str = "en") -> Callable:
    """Setup a translator function"""
    translations = {
        "ar": {
            "per 100 child-days": "لكل 100 يوم طفل",
            "children": "أطفال",
            # Admin Incident Reports
            "Incident Reports": "تقارير الحوادث",
            "Create New Report": "إنشاء تقرير جديد",
            "Filter Reports": "تصفية التقارير",
            "Scope": "النطاق",
            "All Scopes": "جميع النطاقات",
            "Specific Kindergarten": "حضانة محددة",
            "Governorate": "محافظة",
            "All Kindergartens": "جميع الحضانات",
            "Kindergarten": "الحضانة",
            "Choose Kindergarten": "اختر الحضانة",
            "Choose Governorate": "اختر المحافظة",
            "Search": "بحث",
            "Reset": "إعادة تعيين",
            "Reports List": "قائمة التقارير",
            "No Reports Found": "لا توجد تقارير",
            "No reports match your search criteria.": "لم يتم العثور على أي تقارير تطابق معايير البحث.",
            "Title": "العنوان",
            "Time Period": "الفترة الزمنية",
            "Created Date": "تاريخ الإنشاء",
            "Generated By": "المولد",
            "Total Incidents": "عدد الحوادث",
            "Actions": "الإجراءات",
            "View": "عرض",
            "Export": "تصدير",
            "Create Incident Report": "إنشاء تقرير حوادث جديد",
            "Report Scope": "نطاق التقرير",
            "Choose Scope": "اختر النطاق",
            "Time Period": "الفترة الزمنية",
            "Choose Period": "اختر الفترة",
            "Current Week": "الأسبوع الحالي",
            "Current Month": "الشهر الحالي",
            "Last 3 Years": "آخر 3 سنوات",
            "Current Year": "السنة الحالية",
            "Year": "السنة",
            "Choose Year": "اختر السنة",
            "Cancel": "إلغاء",
            "Create Report": "إنشاء التقرير",
            "Report Details": "تفاصيل التقرير",
            "Report Information": "معلومات التقرير",
            "Summary": "الملخص",
            "Total Incidents": "إجمالي الحوادث",
            "Open Incidents": "حوادث مفتوحة",
            "Incidents by Type": "الحوادث حسب النوع",
            "Incidents by Severity": "الحوادث حسب الخطورة",
            "Incidents by Kindergarten": "الحوادث حسب الحضانة",
            "Close": "إغلاق",
            "Export CSV": "تصدير CSV",
            "Please fill all required fields": "يرجى ملء جميع الحقول المطلوبة",
            "Please select a kindergarten": "يرجى اختيار الحضانة",
            "Please select a governorate": "يرجى اختيار المحافظة",
            "Please select a year": "يرجى اختيار السنة",
            "Report created successfully": "تم إنشاء التقرير بنجاح",
            "Error creating report": "حدث خطأ في إنشاء التقرير",
            "Error loading reports": "حدث خطأ في تحميل التقارير",
            "Error loading report": "حدث خطأ في تحميل التقرير",
            "Error exporting report": "حدث خطأ في التصدير",
            "Loading...": "جارٍ تحميل البيانات، يرجى الانتظار.",
            "Unknown": "غير معروف",
        },
        "en": {
            "per 100 child-days": "per 100 child-days",
            "children": "children",
            # Admin Incident Reports
            "Incident Reports": "Incident Reports",
            "Create New Report": "Create New Report",
            "Filter Reports": "Filter Reports",
            "Scope": "Scope",
            "All Scopes": "All Scopes",
            "Specific Kindergarten": "Specific Kindergarten",
            "Governorate": "Governorate",
            "All Kindergartens": "All Kindergartens",
            "Kindergarten": "Kindergarten",
            "Choose Kindergarten": "Choose Kindergarten",
            "Choose Governorate": "Choose Governorate",
            "Search": "Search",
            "Reset": "Reset",
            "Reports List": "Reports List",
            "No Reports Found": "No Reports Found",
            "No reports match your search criteria.": "No reports match your search criteria.",
            "Title": "Title",
            "Time Period": "Time Period",
            "Created Date": "Created Date",
            "Generated By": "Generated By",
            "Total Incidents": "Total Incidents",
            "Actions": "Actions",
            "View": "View",
            "Export": "Export",
            "Create Incident Report": "Create Incident Report",
            "Report Scope": "Report Scope",
            "Choose Scope": "Choose Scope",
            "Time Period": "Time Period",
            "Choose Period": "Choose Period",
            "Current Week": "Current Week",
            "Current Month": "Current Month",
            "Last 3 Years": "Last 3 Years",
            "Current Year": "Current Year",
            "Year": "Year",
            "Choose Year": "Choose Year",
            "Cancel": "Cancel",
            "Create Report": "Create Report",
            "Report Details": "Report Details",
            "Report Information": "Report Information",
            "Summary": "Summary",
            "Total Incidents": "Total Incidents",
            "Open Incidents": "Open Incidents",
            "Incidents by Type": "Incidents by Type",
            "Incidents by Severity": "Incidents by Severity",
            "Incidents by Kindergarten": "Incidents by Kindergarten",
            "Close": "Close",
            "Export CSV": "Export CSV",
            "Please fill all required fields": "Please fill all required fields",
            "Please select a kindergarten": "Please select a kindergarten",
            "Please select a governorate": "Please select a governorate",
            "Please select a year": "Please select a year",
            "Report created successfully": "Report created successfully",
            "Error creating report": "Error creating report",
            "Error loading reports": "Error loading reports",
            "Error loading report": "Error loading report",
            "Error exporting report": "Error exporting report",
            "Loading...": "Loading...",
            "Unknown": "Unknown",
        }
    }

    def translate(key: str) -> str:
        lang_dict = translations.get(language, {})
        return lang_dict.get(key, key)

    return translate


def get_translation(key: str, language: str = "en") -> str:
    """Get translation for a key, falling back to the key itself when missing."""
    return setup_translator(language)(key)


# ---------------------------------------------------------------------------
# Arabic display labels for enum values and audit constants rendered in
# server-side templates (profile activity feed, user badges, ...).
# ---------------------------------------------------------------------------

ROLE_LABELS_AR = {
    "ADMIN": "مدير النظام",
    "MANAGER": "مدير حضانة",
    "SUPERVISOR": "مشرفة",
    "PARENT": "ولي أمر",
}

STATUS_LABELS_AR = {
    "ACTIVE": "نشط",
    "INACTIVE": "غير نشط",
    "SUSPENDED": "موقوف",
    "PENDING": "قيد الانتظار",
    "DRAFT": "مسودة",
}

AUDIT_ENTITY_LABELS_AR = {
    "USER": "مستخدم",
    "CHILD": "طفل",
    "KINDERGARTEN": "حضانة",
    "ENROLLMENT": "تسجيل",
    "ATTENDANCE": "حضور",
    "REPORT": "تقرير",
    "INCIDENT": "حادثة",
    "TASK": "مهمة",
    "AUTH": "المصادقة",
    "SYSTEM": "النظام",
    "MESSAGE": "رسالة",
    "CLASS": "شعبة",
    "ALERT": "تنبيه",
    "BACKUP": "نسخة احتياطية",
}

# Token-based translation for AuditAction constants (LOGIN_SUCCESS → دخول ناجح).
_AUDIT_ACTION_LABELS_AR = {
    "HTTP_REQUEST": "طلب وصول",
    "LOGIN_SUCCESS": "دخول ناجح",
    "LOGIN_FAILED": "دخول فاشل",
    "LOGIN_LOCKED": "حساب مقفل",
    "LOGIN": "تسجيل دخول",
    "LOGOUT": "تسجيل خروج",
    "REGISTER": "تسجيل حساب",
    "CREATE": "إنشاء",
    "UPDATE": "تحديث",
    "DELETE": "حذف",
    "VIEW": "عرض",
    "ACCESS_DENIED": "رفض وصول",
}

_AUDIT_TOKENS_AR = {
    "USER": "مستخدم", "USERS": "مستخدمين", "BULK": "جماعي", "ADMIN": "إداري",
    "EXPORT": "تصدير", "IMPORT": "استيراد", "REPORT": "تقرير", "DAILY": "يومي",
    "ANALYTICS": "تحليلات", "AUDIT": "تدقيق", "LOG": "سجل", "CLEANUP": "تنظيف",
    "MESSAGE": "رسالة", "NOTIFICATIONS": "إشعارات", "SENT": "إرسال",
    "CREATED": "إنشاء", "UPDATED": "تحديث", "DELETED": "حذف", "EDITED": "تعديل",
    "VIEWED": "عرض", "GENERATED": "توليد", "RESOLVED": "معالجة",
    "SUBMITTED": "تقديم", "COMPLETED": "اكتمال", "FAILED": "فشل",
    "SUCCESS": "نجاح", "REQUESTED": "طلب", "DOWNLOADED": "تنزيل",
    "PASSWORD": "كلمة المرور", "RESET": "إعادة تعيين", "CHANGED": "تغيير",
    "CHANGE": "تغيير", "PROFILE": "الملف الشخصي", "BACKUP": "نسخة احتياطية",
    "RESTORED": "استعادة", "ENQUEUED": "جدولة", "ALERT": "تنبيه",
    "ACKNOWLEDGED": "تأكيد", "KINDERGARTEN": "حضانة", "CHILDREN": "أطفال",
    "INCIDENT": "حادثة", "ATTENDANCE": "حضور", "OVERRIDE": "تجاوز",
    "IMPERSONATION": "انتحال صلاحية", "START": "بدء", "END": "إنهاء",
    "ATTEMPT": "محاولة", "MFA": "التحقق الثنائي", "ENABLED": "تفعيل",
    "DISABLED": "تعطيل", "BYPASS": "تجاوز", "GOVERNANCE": "حوكمة",
    "REMINDER": "تذكير", "CONTACT": "تواصل", "STATUS": "حالة",
    "CLASSIFICATION": "تصنيف", "CACHE": "ذاكرة مؤقتة", "WARM": "تهيئة",
    "INVALIDATE": "إبطال", "DASHBOARD": "لوحة", "ERROR": "خطأ",
    "PREVIEW": "معاينة", "QUEUED": "جدولة", "SKIPPED": "تخطي",
    "READ": "قراءة", "REPLIED": "رد", "ARCHIVED": "أرشفة",
    "UNARCHIVED": "إلغاء أرشفة", "ATTACHMENT": "مرفق", "ADDED": "إضافة",
    "ANNOUNCEMENT": "إعلان", "FORCE": "إجباري", "PARENT": "ولي أمر",
    "TO": "إلى", "SYNC": "متزامن", "JOB": "مهمة",
    "INITIATED": "بدء", "AUTH": "مصادقة", "LOCKED": "قفل",
}


def audit_action_label_ar(action: str) -> str:
    """Arabic display label for an AuditAction constant."""
    if not action:
        return "—"
    action = str(action)
    if action in _AUDIT_ACTION_LABELS_AR:
        return _AUDIT_ACTION_LABELS_AR[action]
    return " ".join(_AUDIT_TOKENS_AR.get(t, t) for t in action.split("_"))


def audit_entity_label_ar(entity_type: str) -> str:
    if not entity_type:
        return "—"
    return AUDIT_ENTITY_LABELS_AR.get(str(entity_type).upper(), str(entity_type))


def role_label_ar(role: str) -> str:
    return ROLE_LABELS_AR.get(str(role or "").upper(), str(role or "—"))


def status_label_ar(status: str) -> str:
    return STATUS_LABELS_AR.get(str(status or "").upper(), str(status or "—"))
