from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TEMPLATE = ROOT / "templates" / "admin" / "import_logs.html"


def test_kinjo_lang_is_set_before_page_script_runs():
    """window.KINJO_LANG was read (`const _isEn = window.KINJO_LANG === 'en'`)
    but never assigned anywhere on this page or in admin_base.html -- it was
    always undefined, so _isEn was always false and every JS-rendered string
    (aria-labels, date formatting, modal labels, error messages) stayed in
    Arabic even when the admin had selected English."""
    html = TEMPLATE.read_text(encoding="utf-8")
    assert 'window.KINJO_LANG = "{{ ui_lang }}"' in html


def test_dead_csv_users_type_option_removed():
    """import_type is hardcoded to EXCEL_KINDERGARTENS in
    _serialize_import_log (ImportLog has no import_type column and no
    CSV-user import ever writes to this table), so the "CSV — Users" type
    filter option could never match anything."""
    html = TEMPLATE.read_text(encoding="utf-8")
    assert "CSV_USERS" not in html


def test_tables_have_caption_and_column_scope():
    """The main logs table (9 columns) had no <caption> and no
    scope="col" on any header. The error-details table generated by JS
    (3 columns) adds 3 more scope="col" occurrences to the file's total."""
    html = TEMPLATE.read_text(encoding="utf-8")
    assert '<caption class="visually-hidden">' in html
    assert html.count('scope="col"') == 12


def test_error_details_table_has_caption_and_scope():
    """The JS-generated error-details table inside the modal also had no
    caption/scope."""
    html = TEMPLATE.read_text(encoding="utf-8")
    assert "caption class=\\\"visually-hidden\\\"" in html or '<caption class="visually-hidden">${' in html
    assert 'scope="col">${_isEn' in html


def test_view_details_button_has_per_row_accessible_name():
    """Every row's "view details" button had the identical
    aria-label="View details" with no reference to which import it acts
    on."""
    html = TEMPLATE.read_text(encoding="utf-8")
    assert "aria-label=\"View details\"" not in html
    assert "View details for import #${log.id}" in html


def test_pagination_ui_exists_and_uses_delegated_clicks():
    """The backend already returned total/page/pages, but nothing in the
    template ever rendered pagination controls -- only the first page
    (per_page=20 backend default) was ever reachable."""
    html = TEMPLATE.read_text(encoding="utf-8")
    assert 'id="logsPaginationNav"' in html
    assert 'id="logsPagination"' in html
    assert "renderPagination" in html
    assert "data-page" in html


def test_filter_buttons_reset_to_page_one_not_the_click_event():
    """addEventListener('click', loadLogs) would pass the click Event
    object as loadLogs's `page` argument once loadLogs gained a page
    parameter for pagination -- must be wrapped so a real page number is
    passed instead."""
    html = TEMPLATE.read_text(encoding="utf-8")
    assert "addEventListener('click', loadLogs)" not in html
    assert "() => loadLogs(1)" in html
