"""Initial migration - all tables

Revision ID: 7d792f81c264
Revises: 
Create Date: 2026-01-13 22:42:27.429700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d792f81c264'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curriculum_outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.Enum('SOCIAL_EMOTIONAL', 'PHYSICAL', 'COGNITIVE', 'LANGUAGE', name='learningdomain'), nullable=False),
    sa.Column('age_band_min_months', sa.Integer(), nullable=False),
    sa.Column('age_band_max_months', sa.Integer(), nullable=False),
    sa.Column('indicator_code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('indicator_code')
    )
    op.create_index(op.f('ix_curriculum_outcomes_id'), 'curriculum_outcomes', ['id'], unique=False)
    op.create_table('kindergartens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_ar', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('governorate', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('area', sa.String(length=100), nullable=False),
    sa.Column('address_line', sa.Text(), nullable=False),
    sa.Column('contact_phone', sa.String(length=20), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'INACTIVE', name='kindergartenstatus'), nullable=False),
    sa.Column('operating_hours_start', sa.String(length=5), nullable=True),
    sa.Column('operating_hours_end', sa.String(length=5), nullable=True),
    sa.Column('license_number', sa.String(length=100), nullable=True),
    sa.Column('license_valid_until', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_kindergarten_location', 'kindergartens', ['governorate', 'city', 'area'], unique=False)
    op.create_index('idx_kindergarten_status', 'kindergartens', ['status'], unique=False)
    op.create_index(op.f('ix_kindergartens_id'), 'kindergartens', ['id'], unique=False)
    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kindergarten_id', sa.Integer(), nullable=False),
    sa.Column('name_ar', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=True),
    sa.Column('capacity_total', sa.Integer(), nullable=False),
    sa.Column('min_age_months', sa.Integer(), nullable=False),
    sa.Column('max_age_months', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('capacity_total >= 1', name='ck_capacity_positive'),
    sa.CheckConstraint('max_age_months >= min_age_months', name='ck_age_band_valid'),
    sa.ForeignKeyConstraint(['kindergarten_id'], ['kindergartens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classes_id'), 'classes', ['id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kindergarten_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('TRIP', 'MEETING', 'HOLIDAY', 'CELEBRATION', name='eventtype'), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('requires_consent_flag', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.CheckConstraint('end_at >= start_at', name='ck_event_end_after_start'),
    sa.ForeignKeyConstraint(['kindergarten_id'], ['kindergartens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_table('governance_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kindergarten_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('governance_quality_index', sa.Float(), nullable=False),
    sa.Column('child_experience_index', sa.Float(), nullable=False),
    sa.Column('final_governance_score', sa.Float(), nullable=False),
    sa.Column('band', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['kindergarten_id'], ['kindergartens.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kindergarten_id', 'period_start', name='uq_governance_score_period')
    )
    op.create_index(op.f('ix_governance_scores_id'), 'governance_scores', ['id'], unique=False)
    op.create_table('kindergarten_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kindergarten_id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('enabled_flag', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['kindergarten_id'], ['kindergartens.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kindergarten_id', 'service_name', name='uq_kindergarten_service')
    )
    op.create_index(op.f('ix_kindergarten_services_id'), 'kindergarten_services', ['id'], unique=False)
    op.create_table('kpi_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kindergarten_id', sa.Integer(), nullable=True),
    sa.Column('kpi_name', sa.String(length=100), nullable=False),
    sa.Column('kpi_value', sa.Float(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['kindergarten_id'], ['kindergartens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_kpi_snapshot', 'kpi_snapshots', ['kindergarten_id', 'kpi_name', 'period_start'], unique=False)
    op.create_index(op.f('ix_kpi_snapshots_id'), 'kpi_snapshots', ['id'], unique=False)
    op.create_table('operating_calendar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kindergarten_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['kindergarten_id'], ['kindergartens.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kindergarten_id', 'date', name='uq_kindergarten_date')
    )
    op.create_index('idx_calendar_date', 'operating_calendar', ['kindergarten_id', 'date'], unique=False)
    op.create_index(op.f('ix_operating_calendar_id'), 'operating_calendar', ['id'], unique=False)
    op.create_table('ratio_compliance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kindergarten_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('operating_minutes', sa.Integer(), nullable=False),
    sa.Column('compliant_minutes', sa.Integer(), nullable=False),
    sa.Column('staff_count_avg', sa.Float(), nullable=False),
    sa.Column('child_count_avg', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['kindergarten_id'], ['kindergartens.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kindergarten_id', 'date', name='uq_ratio_kindergarten_date')
    )
    op.create_index(op.f('ix_ratio_compliance_id'), 'ratio_compliance', ['id'], unique=False)
    op.create_table('surveys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kindergarten_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('nps_question_enabled', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['kindergarten_id'], ['kindergartens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_surveys_id'), 'surveys', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'SUPERVISOR', 'PARENT', name='userrole'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'INACTIVE', name='userstatus'), nullable=False),
    sa.Column('kindergarten_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['kindergarten_id'], ['kindergartens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_role_kindergarten', 'users', ['role', 'kindergarten_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('sensitivity_level', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_created', 'audit_logs', ['created_at'], unique=False)
    op.create_index('idx_audit_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_audit_user_action', 'audit_logs', ['user_id', 'action'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_type', sa.Enum('DIRECT', 'CLASS', 'BROADCAST', name='messagethreadtype'), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('kindergarten_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('message_body', sa.Text(), nullable=False),
    sa.Column('translated_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['kindergarten_id'], ['kindergartens.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_message_thread', 'messages', ['thread_type', 'kindergarten_id'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_table('parent_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('second_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('first_name_en', sa.String(length=100), nullable=True),
    sa.Column('last_name_en', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='gender'), nullable=False),
    sa.Column('nationality', sa.String(length=100), nullable=False),
    sa.Column('national_id', sa.String(length=50), nullable=True),
    sa.Column('passport_number', sa.String(length=50), nullable=True),
    sa.Column('home_governorate', sa.String(length=100), nullable=False),
    sa.Column('home_city', sa.String(length=100), nullable=False),
    sa.Column('home_area', sa.String(length=100), nullable=False),
    sa.Column('home_address_line', sa.Text(), nullable=False),
    sa.Column('work_address', sa.Text(), nullable=True),
    sa.Column('correspondence_preference', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(nationality = 'Jordanian' AND national_id IS NOT NULL) OR (nationality != 'Jordanian' AND passport_number IS NOT NULL)", name='ck_parent_identity_validation'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_parent_national_id', 'parent_profiles', ['national_id'], unique=False)
    op.create_index('idx_parent_phone', 'parent_profiles', ['phone_number'], unique=False)
    op.create_index(op.f('ix_parent_profiles_id'), 'parent_profiles', ['id'], unique=False)
    op.create_table('staff_presence_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('kindergarten_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.CheckConstraint('end_at IS NULL OR end_at > start_at', name='ck_presence_end_after_start'),
    sa.ForeignKeyConstraint(['kindergarten_id'], ['kindergartens.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_staff_presence', 'staff_presence_logs', ['kindergarten_id', 'date'], unique=False)
    op.create_index(op.f('ix_staff_presence_logs_id'), 'staff_presence_logs', ['id'], unique=False)
    op.create_table('supervisor_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('supervisor_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['supervisor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_supervisor_assignment', 'supervisor_assignments', ['supervisor_id', 'start_date', 'end_date'], unique=False)
    op.create_index(op.f('ix_supervisor_assignments_id'), 'supervisor_assignments', ['id'], unique=False)
    op.create_table('children',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='gender'), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('father_name', sa.String(length=255), nullable=False),
    sa.Column('mother_first_name', sa.String(length=100), nullable=False),
    sa.Column('mother_second_name', sa.String(length=100), nullable=True),
    sa.Column('mother_last_name', sa.String(length=100), nullable=False),
    sa.Column('mother_nationality', sa.String(length=100), nullable=False),
    sa.Column('mother_national_id', sa.String(length=50), nullable=True),
    sa.Column('mother_passport_number', sa.String(length=50), nullable=True),
    sa.Column('media_consent', sa.Boolean(), nullable=False),
    sa.Column('correspondence_flag', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(mother_nationality = 'Jordanian' AND mother_national_id IS NOT NULL) OR (mother_nationality != 'Jordanian' AND mother_passport_number IS NOT NULL)", name='ck_mother_identity_validation'),
    sa.ForeignKeyConstraint(['parent_id'], ['parent_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_child_dob', 'children', ['date_of_birth'], unique=False)
    op.create_index('idx_child_parent', 'children', ['parent_id'], unique=False)
    op.create_index(op.f('ix_children_id'), 'children', ['id'], unique=False)
    op.create_table('attendance_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('check_in_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('check_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('method', sa.Enum('PIN', 'QR', 'KIOSK', name='attendancemethod'), nullable=False),
    sa.Column('dropped_by_name', sa.String(length=255), nullable=True),
    sa.Column('picked_by_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.CheckConstraint('check_out_at IS NULL OR check_out_at > check_in_at', name='ck_checkout_after_checkin'),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('child_id', 'date', name='uq_attendance_child_date')
    )
    op.create_index('idx_attendance_date', 'attendance_logs', ['date'], unique=False)
    op.create_index(op.f('ix_attendance_logs_id'), 'attendance_logs', ['id'], unique=False)
    op.create_table('daily_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'RETURNED', name='dailyreportstatus'), nullable=False),
    sa.Column('submitted_by', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('arrival_time', sa.String(length=5), nullable=False),
    sa.Column('leave_time', sa.String(length=5), nullable=False),
    sa.Column('breakfast', sa.Boolean(), nullable=True),
    sa.Column('snack', sa.Boolean(), nullable=True),
    sa.Column('milk', sa.Boolean(), nullable=True),
    sa.Column('lunch', sa.Boolean(), nullable=True),
    sa.Column('nap_start', sa.String(length=5), nullable=True),
    sa.Column('nap_end', sa.String(length=5), nullable=True),
    sa.Column('nap_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('activities', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('child_id', 'date', name='uq_daily_report_child_date')
    )
    op.create_index('idx_daily_report_status', 'daily_reports', ['status'], unique=False)
    op.create_index(op.f('ix_daily_reports_id'), 'daily_reports', ['id'], unique=False)
    op.create_table('enrollment_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('kindergarten_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'PENDING_REVIEW', 'ACCEPTED', 'REJECTED', 'WITHDRAWN', 'WAITLISTED', 'ACTIVE', name='enrollmentstatus'), nullable=False),
    sa.Column('status_reason', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_by', sa.Integer(), nullable=True),
    sa.Column('decision_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enrollment_start_date', sa.Date(), nullable=True),
    sa.Column('enrollment_end_date', sa.Date(), nullable=True),
    sa.Column('class_assignment_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['decision_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['kindergarten_id'], ['kindergartens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_enrollment_class', 'enrollment_applications', ['class_id'], unique=False)
    op.create_index('idx_enrollment_kindergarten', 'enrollment_applications', ['kindergarten_id', 'status'], unique=False)
    op.create_index('idx_enrollment_status', 'enrollment_applications', ['status'], unique=False)
    op.create_index(op.f('ix_enrollment_applications_id'), 'enrollment_applications', ['id'], unique=False)
    op.create_table('health_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_alerts_id'), 'health_alerts', ['id'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('kindergarten_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('INJURY', 'BEHAVIOR', 'ILLNESS', 'OTHER', name='incidenttype'), nullable=False),
    sa.Column('severity_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severitylevel'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notify_parent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('followup_required_flag', sa.Boolean(), nullable=False),
    sa.Column('followup_sla_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['kindergarten_id'], ['kindergartens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_incident_followup', 'incidents', ['followup_required_flag', 'closed_at'], unique=False)
    op.create_index('idx_incident_severity', 'incidents', ['severity_level'], unique=False)
    op.create_index(op.f('ix_incidents_id'), 'incidents', ['id'], unique=False)
    op.create_table('observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('observed_by', sa.Integer(), nullable=False),
    sa.Column('domain', sa.Enum('SOCIAL_EMOTIONAL', 'PHYSICAL', 'COGNITIVE', 'LANGUAGE', name='learningdomain'), nullable=False),
    sa.Column('observation_text', sa.Text(), nullable=False),
    sa.Column('mastery_level', sa.Enum('ON_TRACK', 'NEEDS_SUPPORT', 'EXCEEDS', name='masterylevel'), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['observed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_observations_id'), 'observations', ['id'], unique=False)
    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='portfoliostatus'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parent_viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolios_id'), 'portfolios', ['id'], unique=False)
    op.create_table('safeguarding_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('kindergarten_id', sa.Integer(), nullable=False),
    sa.Column('case_description', sa.Text(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sla_escalation_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sla_closure_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['kindergarten_id'], ['kindergartens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_safeguarding_status', 'safeguarding_cases', ['closed_at'], unique=False)
    op.create_index(op.f('ix_safeguarding_cases_id'), 'safeguarding_cases', ['id'], unique=False)
    op.create_table('waitlist_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enrollment_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('WAITLISTED', 'OFFERED', 'ACCEPTED', 'DECLINED', 'EXPIRED', name='waitliststatus'), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('offer_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('offer_expiry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollment_applications.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enrollment_id')
    )
    op.create_index('idx_waitlist_status_priority', 'waitlist_entries', ['status', 'priority_score'], unique=False)
    op.create_index(op.f('ix_waitlist_entries_id'), 'waitlist_entries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_waitlist_entries_id'), table_name='waitlist_entries')
    op.drop_index('idx_waitlist_status_priority', table_name='waitlist_entries')
    op.drop_table('waitlist_entries')
    op.drop_index(op.f('ix_safeguarding_cases_id'), table_name='safeguarding_cases')
    op.drop_index('idx_safeguarding_status', table_name='safeguarding_cases')
    op.drop_table('safeguarding_cases')
    op.drop_index(op.f('ix_portfolios_id'), table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_index(op.f('ix_observations_id'), table_name='observations')
    op.drop_table('observations')
    op.drop_index(op.f('ix_incidents_id'), table_name='incidents')
    op.drop_index('idx_incident_severity', table_name='incidents')
    op.drop_index('idx_incident_followup', table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_health_alerts_id'), table_name='health_alerts')
    op.drop_table('health_alerts')
    op.drop_index(op.f('ix_enrollment_applications_id'), table_name='enrollment_applications')
    op.drop_index('idx_enrollment_status', table_name='enrollment_applications')
    op.drop_index('idx_enrollment_kindergarten', table_name='enrollment_applications')
    op.drop_index('idx_enrollment_class', table_name='enrollment_applications')
    op.drop_table('enrollment_applications')
    op.drop_index(op.f('ix_daily_reports_id'), table_name='daily_reports')
    op.drop_index('idx_daily_report_status', table_name='daily_reports')
    op.drop_table('daily_reports')
    op.drop_index(op.f('ix_attendance_logs_id'), table_name='attendance_logs')
    op.drop_index('idx_attendance_date', table_name='attendance_logs')
    op.drop_table('attendance_logs')
    op.drop_index(op.f('ix_children_id'), table_name='children')
    op.drop_index('idx_child_parent', table_name='children')
    op.drop_index('idx_child_dob', table_name='children')
    op.drop_table('children')
    op.drop_index(op.f('ix_supervisor_assignments_id'), table_name='supervisor_assignments')
    op.drop_index('idx_supervisor_assignment', table_name='supervisor_assignments')
    op.drop_table('supervisor_assignments')
    op.drop_index(op.f('ix_staff_presence_logs_id'), table_name='staff_presence_logs')
    op.drop_index('idx_staff_presence', table_name='staff_presence_logs')
    op.drop_table('staff_presence_logs')
    op.drop_index(op.f('ix_parent_profiles_id'), table_name='parent_profiles')
    op.drop_index('idx_parent_phone', table_name='parent_profiles')
    op.drop_index('idx_parent_national_id', table_name='parent_profiles')
    op.drop_table('parent_profiles')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index('idx_message_thread', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index('idx_audit_user_action', table_name='audit_logs')
    op.drop_index('idx_audit_entity', table_name='audit_logs')
    op.drop_index('idx_audit_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_user_role_kindergarten', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_surveys_id'), table_name='surveys')
    op.drop_table('surveys')
    op.drop_index(op.f('ix_ratio_compliance_id'), table_name='ratio_compliance')
    op.drop_table('ratio_compliance')
    op.drop_index(op.f('ix_operating_calendar_id'), table_name='operating_calendar')
    op.drop_index('idx_calendar_date', table_name='operating_calendar')
    op.drop_table('operating_calendar')
    op.drop_index(op.f('ix_kpi_snapshots_id'), table_name='kpi_snapshots')
    op.drop_index('idx_kpi_snapshot', table_name='kpi_snapshots')
    op.drop_table('kpi_snapshots')
    op.drop_index(op.f('ix_kindergarten_services_id'), table_name='kindergarten_services')
    op.drop_table('kindergarten_services')
    op.drop_index(op.f('ix_governance_scores_id'), table_name='governance_scores')
    op.drop_table('governance_scores')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_classes_id'), table_name='classes')
    op.drop_table('classes')
    op.drop_index(op.f('ix_kindergartens_id'), table_name='kindergartens')
    op.drop_index('idx_kindergarten_status', table_name='kindergartens')
    op.drop_index('idx_kindergarten_location', table_name='kindergartens')
    op.drop_table('kindergartens')
    op.drop_index(op.f('ix_curriculum_outcomes_id'), table_name='curriculum_outcomes')
    op.drop_table('curriculum_outcomes')
    # ### end Alembic commands ###
