"""Add announcement messaging with MessageRecipient table and allow_replies field

Revision ID: 8f3cc3e78b4f
Revises: 20260121_add_message_indexes
Create Date: 2026-01-22 00:32:25.387145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f3cc3e78b4f'
down_revision: Union[str, None] = '20260121_add_message_indexes'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_recipients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('recipient_user_id', sa.Integer(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'recipient_user_id', name='uq_message_recipient')
    )
    op.create_index(op.f('ix_message_recipients_id'), 'message_recipients', ['id'], unique=False)
    op.create_index('ix_message_recipients_message_id', 'message_recipients', ['message_id'], unique=False)
    op.create_index('ix_message_recipients_recipient_user_id', 'message_recipients', ['recipient_user_id'], unique=False)
    op.create_index('ix_message_recipients_status', 'message_recipients', ['status'], unique=False)
    op.drop_index('ix_curriculum_outcomes_id', table_name='curriculum_outcomes')
    op.drop_table('curriculum_outcomes')
    op.add_column('messages', sa.Column('allow_replies', sa.Boolean(), nullable=False, default=True))
    op.alter_column('messages', 'thread_type',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('DIRECT', 'ANNOUNCEMENT', 'CLASS', 'BROADCAST', name='messagethreadtype'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'thread_type',
               existing_type=sa.Enum('DIRECT', 'ANNOUNCEMENT', 'CLASS', 'BROADCAST', name='messagethreadtype'),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)
    op.drop_column('messages', 'allow_replies')
    op.create_table('curriculum_outcomes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('domain', sa.VARCHAR(length=16), nullable=False),
    sa.Column('age_band_min_months', sa.INTEGER(), nullable=False),
    sa.Column('age_band_max_months', sa.INTEGER(), nullable=False),
    sa.Column('indicator_code', sa.VARCHAR(length=50), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('indicator_code')
    )
    op.create_index('ix_curriculum_outcomes_id', 'curriculum_outcomes', ['id'], unique=False)
    op.drop_index('ix_message_recipients_status', table_name='message_recipients')
    op.drop_index('ix_message_recipients_recipient_user_id', table_name='message_recipients')
    op.drop_index('ix_message_recipients_message_id', table_name='message_recipients')
    op.drop_index(op.f('ix_message_recipients_id'), table_name='message_recipients')
    op.drop_table('message_recipients')
    # ### end Alembic commands ###
