"""reconcile orm schema

Revision ID: a38db517a179
Revises: 20260213_daily_checklists_kpi
Create Date: 2026-02-17 08:33:28.469047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a38db517a179'
down_revision: Union[str, None] = '20260213_daily_checklists_kpi'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _drop_constraint_if_named(batch_op, constraint_name: str | None, constraint_type: str) -> None:
    """SQLite batch operations cannot drop unnamed constraints safely."""
    if constraint_name:
        batch_op.drop_constraint(constraint_name, type_=constraint_type)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advanced_analytics_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dimension_type', sa.Enum('NETWORK', 'GOVERNORATE', 'KINDERGARTEN', 'CLASS', 'CHILD', 'CITY', 'AREA', 'STAFF', 'PARENT', name='analyticsdimensiontype'), nullable=False),
    sa.Column('dimension_id', sa.String(length=100), nullable=False),
    sa.Column('period_type', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'QUARTERLY', 'YEARLY', name='analyticsperiodtype'), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('attendance_rate', sa.Float(), nullable=True),
    sa.Column('chronic_absence_rate', sa.Float(), nullable=True),
    sa.Column('incident_rate_per_100', sa.Float(), nullable=True),
    sa.Column('serious_incident_rate', sa.Float(), nullable=True),
    sa.Column('ratio_compliance_rate', sa.Float(), nullable=True),
    sa.Column('report_completion_rate', sa.Float(), nullable=True),
    sa.Column('parent_satisfaction_nps', sa.Float(), nullable=True),
    sa.Column('child_development_index', sa.Float(), nullable=True),
    sa.Column('staff_turnover_rate', sa.Float(), nullable=True),
    sa.Column('regulatory_compliance_score', sa.Float(), nullable=True),
    sa.Column('attendance_trend_slope', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('improvement_velocity', sa.Float(), nullable=True),
    sa.Column('attendance_incident_correlation', sa.Float(), nullable=True),
    sa.Column('staffing_quality_correlation', sa.Float(), nullable=True),
    sa.Column('health_alerts_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('advanced_analytics_cache', schema=None) as batch_op:
        batch_op.create_index('ix_adv_analytics_cache_dim', ['dimension_type', 'dimension_id'], unique=False)
        batch_op.create_index('ix_adv_analytics_cache_lookup', ['dimension_type', 'dimension_id', 'period_type', 'period_start', 'period_end'], unique=True)
        batch_op.create_index('ix_adv_analytics_cache_period', ['period_type', 'period_start', 'period_end'], unique=False)
        batch_op.create_index(batch_op.f('ix_advanced_analytics_cache_id'), ['id'], unique=False)

    op.create_table('training_modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('training_modules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_modules_id'), ['id'], unique=False)

    op.create_table('kpi_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kpi_name', sa.String(length=100), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('kindergarten_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['kindergarten_id'], ['kindergartens.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kpi_name', 'effective_date', 'kindergarten_id', name='uq_kpi_target')
    )
    with op.batch_alter_table('kpi_targets', schema=None) as batch_op:
        batch_op.create_index('ix_kpi_target_name_date', ['kpi_name', 'effective_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_kpi_targets_id'), ['id'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.Enum('INCIDENT_SUMMARY', 'ATTENDANCE_SUMMARY', 'COMPLIANCE_REPORT', name='reporttype'), nullable=False),
    sa.Column('scope_type', sa.Enum('KINDERGARTEN', 'GOVERNORATE', 'ALL', name='reportscopetype'), nullable=False),
    sa.Column('kindergarten_id', sa.Integer(), nullable=True),
    sa.Column('governorate', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('metrics_json', sa.JSON(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['kindergarten_id'], ['kindergartens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index('idx_reports_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_reports_created_by', ['created_by'], unique=False)
        batch_op.create_index('idx_reports_scope_type', ['scope_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_id'), ['id'], unique=False)

    op.create_table('staff_training_completion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('training_module_id', sa.Integer(), nullable=False),
    sa.Column('kindergarten_id', sa.Integer(), nullable=True),
    sa.Column('completion_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'OVERDUE', name='trainingstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['kindergarten_id'], ['kindergartens.id'], ),
    sa.ForeignKeyConstraint(['training_module_id'], ['training_modules.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'training_module_id', name='uq_staff_training')
    )
    with op.batch_alter_table('staff_training_completion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staff_training_completion_id'), ['id'], unique=False)
        batch_op.create_index('ix_staff_training_kindergarten', ['kindergarten_id'], unique=False)

    op.create_table('supervisor_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kindergarten_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['kindergarten_id'], ['kindergartens.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_id', 'kindergarten_id', name='uq_supervisor_profiles_user_kindergarten')
    )
    op.create_table('survey_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('nps_score', sa.Integer(), nullable=True),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('survey_id', 'parent_id', name='uq_survey_responses_survey_parent')
    )
    with op.batch_alter_table('survey_responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_survey_responses_id'), ['id'], unique=False)

    op.create_table('absence_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('kindergarten_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('SUBMITTED', 'APPROVED', 'REJECTED', 'CANCELLED', name='absencerequeststatus'), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('start_date <= end_date', name='ck_absence_start_lte_end'),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['kindergarten_id'], ['kindergartens.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['parent_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('absence_requests', schema=None) as batch_op:
        batch_op.create_index('ix_absence_child_dates', ['child_id', 'start_date', 'end_date'], unique=False)
        batch_op.create_index('ix_absence_kg_status', ['kindergarten_id', 'status', 'created_at'], unique=False)
        batch_op.create_index('ix_absence_parent', ['parent_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_absence_requests_id'), ['id'], unique=False)

    op.create_table('child_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('child_documents', schema=None) as batch_op:
        batch_op.create_index('idx_child_documents_child_id', ['child_id'], unique=False)
        batch_op.create_index('idx_child_documents_type', ['document_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_child_documents_id'), ['id'], unique=False)

    with op.batch_alter_table('action_plans', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('OPEN', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='actionplanstatus'),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_action_plans_id'), ['id'], unique=False)

    with op.batch_alter_table('active_alerts', schema=None) as batch_op:
        batch_op.alter_column('severity',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severitylevel'),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('ACTIVE', 'ACKNOWLEDGED', 'RESOLVED', name='alertstatus'),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_active_alerts_id'), ['id'], unique=False)

    with op.batch_alter_table('alert_thresholds', schema=None) as batch_op:
        batch_op.alter_column('operator',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('GT', 'GTE', 'LT', 'LTE', name='alertoperator'),
               existing_nullable=False)
        batch_op.alter_column('severity',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severitylevel'),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_alert_thresholds_id'), ['id'], unique=False)

    with op.batch_alter_table('analytics_dimension_cache', schema=None) as batch_op:
        batch_op.alter_column('dimension_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('NETWORK', 'GOVERNORATE', 'KINDERGARTEN', 'CLASS', 'CHILD', 'CITY', 'AREA', 'STAFF', 'PARENT', name='analyticsdimensiontype'),
               existing_nullable=False)
        batch_op.alter_column('period_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'QUARTERLY', 'YEARLY', name='analyticsperiodtype'),
               existing_nullable=False)

    with op.batch_alter_table('anomaly_alerts', schema=None) as batch_op:
        batch_op.alter_column('severity',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severitylevel'),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_anomaly_alerts_id'), ['id'], unique=False)

    with op.batch_alter_table('attendance_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.Enum('PRESENT', 'ABSENT', 'LATE', 'EXCUSED', name='attendancestatus'), nullable=True))
        batch_op.add_column(sa.Column('recorded_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.alter_column('check_in_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('picked_by_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.drop_index('idx_attendance_date')
        batch_op.drop_index('ix_attendance_logs_date_child')
        batch_op.drop_column('dropped_by_name')
        batch_op.drop_column('method')

    # Backfill newly introduced NOT NULL attendance fields from legacy data.
    op.execute(
        sa.text(
            """
            UPDATE attendance_logs
            SET status = CASE
                WHEN check_in_at IS NULL THEN 'ABSENT'
                ELSE 'PRESENT'
            END
            WHERE status IS NULL
            """
        )
    )
    op.execute(
        sa.text(
            """
            UPDATE attendance_logs
            SET recorded_by = (
                SELECT dr.submitted_by
                FROM daily_reports dr
                WHERE dr.child_id = attendance_logs.child_id
                  AND dr.date = attendance_logs.date
                ORDER BY dr.id DESC
                LIMIT 1
            )
            WHERE recorded_by IS NULL
            """
        )
    )
    op.execute(
        sa.text(
            """
            UPDATE attendance_logs
            SET recorded_by = (
                SELECT id
                FROM users
                WHERE role IN ('ADMIN', 'MANAGER', 'SUPERVISOR')
                ORDER BY id
                LIMIT 1
            )
            WHERE recorded_by IS NULL
            """
        )
    )
    op.execute(
        sa.text(
            """
            UPDATE attendance_logs
            SET recorded_by = (
                SELECT id
                FROM users
                ORDER BY id
                LIMIT 1
            )
            WHERE recorded_by IS NULL
            """
        )
    )
    op.execute(
        sa.text(
            """
            UPDATE attendance_logs
            SET class_id = (
                SELECT ea.class_id
                FROM enrollment_applications ea
                WHERE ea.child_id = attendance_logs.child_id
                  AND ea.class_id IS NOT NULL
                ORDER BY COALESCE(ea.is_active, 0) DESC,
                         COALESCE(ea.updated_at, ea.created_at) DESC,
                         ea.id DESC
                LIMIT 1
            )
            WHERE class_id IS NULL
            """
        )
    )
    op.execute(
        sa.text(
            """
            UPDATE attendance_logs
            SET class_id = (
                SELECT id
                FROM classes
                ORDER BY id
                LIMIT 1
            )
            WHERE class_id IS NULL
            """
        )
    )
    with op.batch_alter_table('attendance_logs', schema=None) as batch_op:
        batch_op.alter_column('class_id',
               existing_type=sa.Integer(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.Enum('PRESENT', 'ABSENT', 'LATE', 'EXCUSED', name='attendancestatus'),
               nullable=False)
        batch_op.alter_column('recorded_by',
               existing_type=sa.Integer(),
               nullable=False)
        batch_op.create_foreign_key('fk_attendance_logs_recorded_by_users', 'users', ['recorded_by'], ['id'])
        batch_op.create_foreign_key('fk_attendance_logs_class_id_classes', 'classes', ['class_id'], ['id'])

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_audit_created')
        batch_op.drop_index('idx_audit_entity')
        batch_op.drop_index('idx_audit_user_action')
        batch_op.drop_index('ix_audit_logs_action')
        batch_op.drop_index('ix_audit_logs_created_at')
        batch_op.drop_index('ix_audit_logs_user_id')
        batch_op.create_index('idx_audit_logs_action', ['action'], unique=False)
        batch_op.create_index('idx_audit_logs_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_audit_logs_entity_type', ['entity_type'], unique=False)
        batch_op.create_index('idx_audit_logs_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('benchmark_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_benchmark_data_id'), ['id'], unique=False)

    with op.batch_alter_table('children', schema=None) as batch_op:
        batch_op.add_column(sa.Column('second_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('nationality', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('national_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('passport_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('photo_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('photo_metadata', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('health_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('educational_notes', sa.Text(), nullable=True))
        batch_op.drop_index('idx_child_parent')
        batch_op.create_index('idx_child_parent_id', ['parent_id'], unique=False)

    # Backfill nullable legacy class fields before tightening constraints.
    op.execute(
        sa.text(
            """
            UPDATE classes
            SET class_code = 'LEGACY-' || CAST(id AS VARCHAR)
            WHERE class_code IS NULL
            """
        )
    )
    op.execute(
        sa.text(
            """
            UPDATE classes
            SET age_group = CASE
                WHEN COALESCE(max_age_months, 0) <= 12 THEN 'AGE_0_1'
                WHEN COALESCE(max_age_months, 0) <= 24 THEN 'AGE_1_2'
                ELSE 'AGE_2_4'
            END
            WHERE age_group IS NULL
            """
        )
    )

    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supervisor_id', sa.Integer(), nullable=True))
        batch_op.alter_column('class_code',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
        batch_op.alter_column('age_group',
               existing_type=sa.VARCHAR(length=7),
               nullable=False)
        batch_op.create_index('idx_classes_is_active', ['is_active'], unique=False)
        batch_op.create_index('idx_classes_kindergarten_id', ['kindergarten_id'], unique=False)
        batch_op.create_unique_constraint('uq_classes_supervisor', ['supervisor_id'])
        batch_op.create_foreign_key('fk_classes_supervisor_profile', 'supervisor_profiles', ['supervisor_id', 'kindergarten_id'], ['user_id', 'kindergarten_id'])

    with op.batch_alter_table('daily_checklists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_checklists_id'), ['id'], unique=False)

    with op.batch_alter_table('daily_report_views', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_report_views_id'), ['id'], unique=False)

    with op.batch_alter_table('daily_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kindergarten_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sent_to_parent_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('rejected_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('mood', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('health_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('bathroom_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('diaper_wet', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('diaper_soiled', sa.Boolean(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'SENT_TO_PARENT', 'REJECTED', 'RETURNED', name='dailyreportstatus'),
               existing_nullable=False)
        batch_op.alter_column('leave_time',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
        batch_op.drop_index('idx_daily_report_status')
        batch_op.drop_index('ix_daily_reports_date_status')
        batch_op.drop_constraint('uq_daily_report_child_date', type_='unique')
        batch_op.create_unique_constraint('uq_daily_report_kindergarten_child_date', ['kindergarten_id', 'child_id', 'date'])
        batch_op.create_foreign_key(
            'fk_daily_reports_kindergarten_id_kindergartens',
            'kindergartens',
            ['kindergarten_id'],
            ['id'],
        )

    # Populate kindergarten_id for historical reports before making it required.
    op.execute(
        sa.text(
            """
            UPDATE daily_reports
            SET kindergarten_id = (
                SELECT ea.kindergarten_id
                FROM enrollment_applications ea
                WHERE ea.child_id = daily_reports.child_id
                ORDER BY COALESCE(ea.is_active, 0) DESC,
                         COALESCE(ea.updated_at, ea.created_at) DESC,
                         ea.id DESC
                LIMIT 1
            )
            WHERE kindergarten_id IS NULL
            """
        )
    )
    op.execute(
        sa.text(
            """
            UPDATE daily_reports
            SET kindergarten_id = (
                SELECT id
                FROM kindergartens
                ORDER BY id
                LIMIT 1
            )
            WHERE kindergarten_id IS NULL
            """
        )
    )
    with op.batch_alter_table('daily_reports', schema=None) as batch_op:
        batch_op.alter_column('kindergarten_id',
               existing_type=sa.Integer(),
               nullable=False)

    with op.batch_alter_table('data_quality_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_quality_metrics_id'), ['id'], unique=False)

    with op.batch_alter_table('drilldown_paths', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drilldown_paths_id'), ['id'], unique=False)

    with op.batch_alter_table('enrollment_applications', schema=None) as batch_op:
        batch_op.drop_index('idx_enrollment_class')
        batch_op.drop_index('idx_enrollment_kindergarten')
        batch_op.drop_index('idx_enrollment_status')

    with op.batch_alter_table('export_jobs', schema=None) as batch_op:
        batch_op.alter_column('export_format',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('CSV', 'PDF', 'EXCEL', name='exportformat'),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='exportstatus'),
               existing_nullable=False)

    with op.batch_alter_table('governance_reminders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_governance_reminders_id'), ['id'], unique=False)

    with op.batch_alter_table('governance_scores', schema=None) as batch_op:
        batch_op.drop_constraint('uq_governance_score_period', type_='unique')

    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index('idx_incident_followup')
        batch_op.drop_index('idx_incident_severity')
        batch_op.drop_index('ix_incidents_occurred_kg')

    with op.batch_alter_table('kindergarten_services', schema=None) as batch_op:
        batch_op.alter_column('kindergarten_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('uq_kindergarten_service', type_='unique')

    with op.batch_alter_table('kindergartens', schema=None) as batch_op:
        batch_op.drop_index('idx_kindergarten_location')
        batch_op.drop_index('idx_kindergarten_status')
        batch_op.drop_index('ix_kindergartens_governorate')
        batch_op.drop_index('uq_kindergarten_name_en_governorate', sqlite_where=sa.text('name_en IS NOT NULL'))
        batch_op.create_index('idx_kindergartens_governorate', ['governorate'], unique=False)
        batch_op.create_index('idx_kindergartens_status', ['status'], unique=False)

    with op.batch_alter_table('kpi_snapshots', schema=None) as batch_op:
        batch_op.drop_index('idx_kpi_snapshot')

    with op.batch_alter_table('message_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_attachments_id'), ['id'], unique=False)

    with op.batch_alter_table('message_recipients', schema=None) as batch_op:
        batch_op.drop_index('ix_message_recipients_message_recipient')

    with op.batch_alter_table('message_user_states', schema=None) as batch_op:
        batch_op.drop_index('ix_message_user_states_message_id')
        batch_op.drop_index('ix_message_user_states_user_id')
        batch_op.create_index(batch_op.f('ix_message_user_states_id'), ['id'], unique=False)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('thread_type',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('DIRECT', 'ANNOUNCEMENT', 'CLASS', 'BROADCAST', name='messagethreadtype'),
               existing_nullable=False)
        batch_op.drop_index('idx_message_thread')
        batch_op.drop_index('ix_messages_reply_to_id')
        batch_op.create_foreign_key('fk_messages_recipient_id_users', 'users', ['recipient_id'], ['id'])

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_report_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('absence_request_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('notification_type', sa.Enum('MESSAGE', 'DAILY_REPORT_SENT', 'DAILY_REPORT_SUBMITTED', 'DAILY_REPORT_REJECTED', 'DAILY_REPORT_MISSING', 'ABSENCE_REQUEST_SUBMITTED', 'ABSENCE_REQUEST_APPROVED', 'ABSENCE_REQUEST_REJECTED', 'ATTENDANCE_CORRECTED', 'SYSTEM', 'GOVERNANCE_REMINDER', name='notificationtype'), nullable=True))
        batch_op.create_index('ix_notifications_daily_report', ['daily_report_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_id'), ['id'], unique=False)
        batch_op.create_foreign_key(
            'fk_notifications_daily_report_id_daily_reports',
            'daily_reports',
            ['daily_report_id'],
            ['id'],
        )
        batch_op.create_foreign_key(
            'fk_notifications_absence_request_id_absence_requests',
            'absence_requests',
            ['absence_request_id'],
            ['id'],
        )

    with op.batch_alter_table('operating_calendar', schema=None) as batch_op:
        batch_op.drop_index('idx_calendar_date')
        batch_op.drop_constraint('uq_kindergarten_date', type_='unique')

    with op.batch_alter_table('parent_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emergency_contact_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_relationship', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('relationship_to_child', sa.String(length=100), nullable=True))
        batch_op.drop_index('idx_parent_national_id')
        batch_op.drop_index('idx_parent_phone')

    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.alter_column('used',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index('ix_password_reset_tokens_token')
        batch_op.drop_index('ix_password_reset_tokens_user_valid')
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_id'), ['id'], unique=False)
        batch_op.create_unique_constraint('uq_password_reset_tokens_token', ['token'])

    with op.batch_alter_table('performance_targets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_performance_targets_id'), ['id'], unique=False)

    with op.batch_alter_table('prediction_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prediction_cache_id'), ['id'], unique=False)

    with op.batch_alter_table('predictive_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_predictive_models_id'), ['id'], unique=False)

    with op.batch_alter_table('ratio_compliance', schema=None) as batch_op:
        batch_op.drop_constraint('uq_ratio_kindergarten_date', type_='unique')

    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.alter_column('severity',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severitylevel'),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_recommendations_id'), ['id'], unique=False)

    with op.batch_alter_table('safeguarding_cases', schema=None) as batch_op:
        batch_op.drop_index('idx_safeguarding_status')

    with op.batch_alter_table('staff_presence_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_staff_presence')

    with op.batch_alter_table('supervisor_assignments', schema=None) as batch_op:
        batch_op.drop_index('idx_supervisor_assignment')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_to', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.alter_column('kindergarten_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='taskstatus'),
               existing_nullable=False)
        batch_op.alter_column('priority',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='taskpriority'),
               existing_nullable=False)
        batch_op.alter_column('due_date',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.drop_index('idx_task_assigned_to')
        batch_op.drop_index('idx_task_due_date')
        batch_op.drop_index('idx_task_kindergarten')
        batch_op.drop_index('idx_task_status_priority')
    op.execute(
        sa.text(
            """
            UPDATE tasks
            SET created_by = created_by_id
            WHERE created_by IS NULL
            """
        )
    )
    op.execute(
        sa.text(
            """
            UPDATE tasks
            SET assigned_to = assigned_to_id
            WHERE assigned_to IS NULL
            """
        )
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('created_by',
               existing_type=sa.Integer(),
               nullable=False)
        batch_op.create_foreign_key('fk_tasks_created_by_users', 'users', ['created_by'], ['id'])
        batch_op.create_foreign_key('fk_tasks_assigned_to_users', 'users', ['assigned_to'], ['id'])
        batch_op.drop_column('child_id')
        batch_op.drop_column('created_by_id')
        batch_op.drop_column('assigned_to_id')

    with op.batch_alter_table('user_dashboard_preferences', schema=None) as batch_op:
        batch_op.drop_index('ix_user_dashboard_prefs_user_id')
        batch_op.create_index('idx_user_dashboard_preferences_user_id', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_dashboard_preferences_id'), ['id'], unique=False)

    with op.batch_alter_table('user_device_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_device_tokens_id'), ['id'], unique=False)

    with op.batch_alter_table('user_filter_preferences', schema=None) as batch_op:
        batch_op.drop_index('ix_user_filter_prefs_user_id')
        batch_op.create_index('idx_user_filter_preferences_user_id', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_filter_preferences_id'), ['id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('must_change_password', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.drop_index('idx_user_role_kindergarten')
        batch_op.drop_index('ix_users_kindergarten_id')
        batch_op.drop_index('ix_users_role_status')
        batch_op.drop_index('ix_users_username_lookup')
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)

    with op.batch_alter_table('waitlist_entries', schema=None) as batch_op:
        batch_op.drop_index('idx_waitlist_status_priority')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waitlist_entries', schema=None) as batch_op:
        batch_op.create_index('idx_waitlist_status_priority', ['status', 'priority_score'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_index('ix_users_username_lookup', ['username'], unique=1)
        batch_op.create_index('ix_users_role_status', ['role', 'status'], unique=False)
        batch_op.create_index('ix_users_kindergarten_id', ['kindergarten_id'], unique=False)
        batch_op.create_index('idx_user_role_kindergarten', ['role', 'kindergarten_id'], unique=False)
        batch_op.drop_column('must_change_password')

    with op.batch_alter_table('user_filter_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_filter_preferences_id'))
        batch_op.drop_index('idx_user_filter_preferences_user_id')
        batch_op.create_index('ix_user_filter_prefs_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('user_device_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_device_tokens_id'))

    with op.batch_alter_table('user_dashboard_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_dashboard_preferences_id'))
        batch_op.drop_index('idx_user_dashboard_preferences_user_id')
        batch_op.create_index('ix_user_dashboard_prefs_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_to_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('created_by_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('child_id', sa.INTEGER(), nullable=True))
        _drop_constraint_if_named(batch_op, None, 'foreignkey')
        batch_op.create_foreign_key('fk_tasks_created_by_id_users', 'users', ['created_by_id'], ['id'])
        batch_op.create_foreign_key('fk_tasks_child_id_children', 'children', ['child_id'], ['id'])
        batch_op.create_foreign_key('fk_tasks_assigned_to_id_users', 'users', ['assigned_to_id'], ['id'])
        batch_op.create_index('idx_task_status_priority', ['status', 'priority'], unique=False)
        batch_op.create_index('idx_task_kindergarten', ['kindergarten_id', 'status'], unique=False)
        batch_op.create_index('idx_task_due_date', ['due_date'], unique=False)
        batch_op.create_index('idx_task_assigned_to', ['assigned_to_id', 'status'], unique=False)
        batch_op.alter_column('due_date',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('priority',
               existing_type=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='taskpriority'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='taskstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('kindergarten_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('created_by')
        batch_op.drop_column('assigned_to')

    with op.batch_alter_table('supervisor_assignments', schema=None) as batch_op:
        batch_op.create_index('idx_supervisor_assignment', ['supervisor_id', 'start_date', 'end_date'], unique=False)

    with op.batch_alter_table('staff_presence_logs', schema=None) as batch_op:
        batch_op.create_index('idx_staff_presence', ['kindergarten_id', 'date'], unique=False)

    with op.batch_alter_table('safeguarding_cases', schema=None) as batch_op:
        batch_op.create_index('idx_safeguarding_status', ['closed_at'], unique=False)

    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendations_id'))
        batch_op.alter_column('severity',
               existing_type=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severitylevel'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('ratio_compliance', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_ratio_kindergarten_date', ['kindergarten_id', 'date'])

    with op.batch_alter_table('predictive_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_predictive_models_id'))

    with op.batch_alter_table('prediction_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prediction_cache_id'))

    with op.batch_alter_table('performance_targets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_performance_targets_id'))

    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        _drop_constraint_if_named(batch_op, None, 'unique')
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_id'))
        batch_op.create_index('ix_password_reset_tokens_user_valid', ['user_id', 'used', 'expires_at'], unique=False)
        batch_op.create_index('ix_password_reset_tokens_token', ['token'], unique=1)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('used',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('parent_profiles', schema=None) as batch_op:
        batch_op.create_index('idx_parent_phone', ['phone_number'], unique=False)
        batch_op.create_index('idx_parent_national_id', ['national_id'], unique=False)
        batch_op.drop_column('relationship_to_child')
        batch_op.drop_column('emergency_contact_relationship')
        batch_op.drop_column('emergency_contact_phone')
        batch_op.drop_column('emergency_contact_name')

    with op.batch_alter_table('operating_calendar', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_kindergarten_date', ['kindergarten_id', 'date'])
        batch_op.create_index('idx_calendar_date', ['kindergarten_id', 'date'], unique=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        _drop_constraint_if_named(batch_op, None, 'foreignkey')
        batch_op.drop_index(batch_op.f('ix_notifications_id'))
        batch_op.drop_index('ix_notifications_daily_report')
        batch_op.drop_column('notification_type')
        batch_op.drop_column('absence_request_id')
        batch_op.drop_column('daily_report_id')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        _drop_constraint_if_named(batch_op, None, 'foreignkey')
        batch_op.create_index('ix_messages_reply_to_id', ['reply_to_id'], unique=False)
        batch_op.create_index('idx_message_thread', ['thread_type', 'kindergarten_id'], unique=False)
        batch_op.alter_column('thread_type',
               existing_type=sa.Enum('DIRECT', 'ANNOUNCEMENT', 'CLASS', 'BROADCAST', name='messagethreadtype'),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)

    with op.batch_alter_table('message_user_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_user_states_id'))
        batch_op.create_index('ix_message_user_states_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_message_user_states_message_id', ['message_id'], unique=False)

    with op.batch_alter_table('message_recipients', schema=None) as batch_op:
        batch_op.create_index('ix_message_recipients_message_recipient', ['message_id', 'recipient_user_id'], unique=False)

    with op.batch_alter_table('message_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_attachments_id'))

    with op.batch_alter_table('kpi_snapshots', schema=None) as batch_op:
        batch_op.create_index('idx_kpi_snapshot', ['kindergarten_id', 'kpi_name', 'period_start'], unique=False)

    with op.batch_alter_table('kindergartens', schema=None) as batch_op:
        batch_op.drop_index('idx_kindergartens_status')
        batch_op.drop_index('idx_kindergartens_governorate')
        batch_op.create_index('uq_kindergarten_name_en_governorate', ['name_en', 'governorate'], unique=1, sqlite_where=sa.text('name_en IS NOT NULL'))
        batch_op.create_index('ix_kindergartens_governorate', ['governorate', 'status'], unique=False)
        batch_op.create_index('idx_kindergarten_status', ['status'], unique=False)
        batch_op.create_index('idx_kindergarten_location', ['governorate', 'city', 'area'], unique=False)

    with op.batch_alter_table('kindergarten_services', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_kindergarten_service', ['kindergarten_id', 'service_name'])
        batch_op.alter_column('kindergarten_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index('ix_incidents_occurred_kg', ['occurred_at', 'kindergarten_id'], unique=False)
        batch_op.create_index('idx_incident_severity', ['severity_level'], unique=False)
        batch_op.create_index('idx_incident_followup', ['followup_required_flag', 'closed_at'], unique=False)

    with op.batch_alter_table('governance_scores', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_governance_score_period', ['kindergarten_id', 'period_start'])

    with op.batch_alter_table('governance_reminders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_governance_reminders_id'))

    with op.batch_alter_table('export_jobs', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='exportstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('export_format',
               existing_type=sa.Enum('CSV', 'PDF', 'EXCEL', name='exportformat'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('enrollment_applications', schema=None) as batch_op:
        batch_op.create_index('idx_enrollment_status', ['status'], unique=False)
        batch_op.create_index('idx_enrollment_kindergarten', ['kindergarten_id', 'status'], unique=False)
        batch_op.create_index('idx_enrollment_class', ['class_id'], unique=False)

    with op.batch_alter_table('drilldown_paths', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drilldown_paths_id'))

    with op.batch_alter_table('data_quality_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_quality_metrics_id'))

    with op.batch_alter_table('daily_reports', schema=None) as batch_op:
        _drop_constraint_if_named(batch_op, None, 'foreignkey')
        batch_op.drop_constraint('uq_daily_report_kindergarten_child_date', type_='unique')
        batch_op.create_unique_constraint('uq_daily_report_child_date', ['child_id', 'date'])
        batch_op.create_index('ix_daily_reports_date_status', ['date', 'status'], unique=False)
        batch_op.create_index('idx_daily_report_status', ['status'], unique=False)
        batch_op.alter_column('leave_time',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'SENT_TO_PARENT', 'REJECTED', 'RETURNED', name='dailyreportstatus'),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)
        batch_op.drop_column('diaper_soiled')
        batch_op.drop_column('diaper_wet')
        batch_op.drop_column('bathroom_count')
        batch_op.drop_column('health_notes')
        batch_op.drop_column('mood')
        batch_op.drop_column('rejected_reason')
        batch_op.drop_column('sent_to_parent_at')
        batch_op.drop_column('kindergarten_id')

    with op.batch_alter_table('daily_report_views', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_report_views_id'))

    with op.batch_alter_table('daily_checklists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_checklists_id'))

    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_classes_supervisor_profile', type_='foreignkey')
        batch_op.drop_constraint('uq_classes_supervisor', type_='unique')
        batch_op.drop_index('idx_classes_kindergarten_id')
        batch_op.drop_index('idx_classes_is_active')
        batch_op.alter_column('age_group',
               existing_type=sa.VARCHAR(length=7),
               nullable=True)
        batch_op.alter_column('class_code',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
        batch_op.drop_column('supervisor_id')

    with op.batch_alter_table('children', schema=None) as batch_op:
        batch_op.drop_index('idx_child_parent_id')
        batch_op.create_index('idx_child_parent', ['parent_id'], unique=False)
        batch_op.drop_column('educational_notes')
        batch_op.drop_column('health_notes')
        batch_op.drop_column('photo_metadata')
        batch_op.drop_column('photo_url')
        batch_op.drop_column('passport_number')
        batch_op.drop_column('national_id')
        batch_op.drop_column('nationality')
        batch_op.drop_column('second_name')

    with op.batch_alter_table('benchmark_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_benchmark_data_id'))

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_audit_logs_user_id')
        batch_op.drop_index('idx_audit_logs_entity_type')
        batch_op.drop_index('idx_audit_logs_created_at')
        batch_op.drop_index('idx_audit_logs_action')
        batch_op.create_index('ix_audit_logs_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_audit_logs_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_audit_logs_action', ['action'], unique=False)
        batch_op.create_index('idx_audit_user_action', ['user_id', 'action'], unique=False)
        batch_op.create_index('idx_audit_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index('idx_audit_created', ['created_at'], unique=False)

    with op.batch_alter_table('attendance_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('method', sa.VARCHAR(length=5), nullable=False))
        batch_op.add_column(sa.Column('dropped_by_name', sa.VARCHAR(length=255), nullable=True))
        _drop_constraint_if_named(batch_op, None, 'foreignkey')
        batch_op.create_index('ix_attendance_logs_date_child', ['date', 'child_id'], unique=False)
        batch_op.create_index('idx_attendance_date', ['date'], unique=False)
        batch_op.alter_column('picked_by_name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('check_in_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_column('notes')
        batch_op.drop_column('recorded_by')
        batch_op.drop_column('status')
        batch_op.drop_column('class_id')

    with op.batch_alter_table('anomaly_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_anomaly_alerts_id'))
        batch_op.alter_column('severity',
               existing_type=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severitylevel'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('analytics_dimension_cache', schema=None) as batch_op:
        batch_op.alter_column('period_type',
               existing_type=sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'QUARTERLY', 'YEARLY', name='analyticsperiodtype'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('dimension_type',
               existing_type=sa.Enum('NETWORK', 'GOVERNORATE', 'KINDERGARTEN', 'CLASS', 'CHILD', 'CITY', 'AREA', 'STAFF', 'PARENT', name='analyticsdimensiontype'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('alert_thresholds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_thresholds_id'))
        batch_op.alter_column('severity',
               existing_type=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severitylevel'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('operator',
               existing_type=sa.Enum('GT', 'GTE', 'LT', 'LTE', name='alertoperator'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    with op.batch_alter_table('active_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_active_alerts_id'))
        batch_op.alter_column('status',
               existing_type=sa.Enum('ACTIVE', 'ACKNOWLEDGED', 'RESOLVED', name='alertstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('severity',
               existing_type=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severitylevel'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('action_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_action_plans_id'))
        batch_op.alter_column('status',
               existing_type=sa.Enum('OPEN', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='actionplanstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('child_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_child_documents_id'))
        batch_op.drop_index('idx_child_documents_type')
        batch_op.drop_index('idx_child_documents_child_id')

    op.drop_table('child_documents')
    with op.batch_alter_table('absence_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_absence_requests_id'))
        batch_op.drop_index('ix_absence_parent')
        batch_op.drop_index('ix_absence_kg_status')
        batch_op.drop_index('ix_absence_child_dates')

    op.drop_table('absence_requests')
    with op.batch_alter_table('survey_responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_survey_responses_id'))

    op.drop_table('survey_responses')
    op.drop_table('supervisor_profiles')
    with op.batch_alter_table('staff_training_completion', schema=None) as batch_op:
        batch_op.drop_index('ix_staff_training_kindergarten')
        batch_op.drop_index(batch_op.f('ix_staff_training_completion_id'))

    op.drop_table('staff_training_completion')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_id'))
        batch_op.drop_index('idx_reports_scope_type')
        batch_op.drop_index('idx_reports_created_by')
        batch_op.drop_index('idx_reports_created_at')

    op.drop_table('reports')
    with op.batch_alter_table('kpi_targets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kpi_targets_id'))
        batch_op.drop_index('ix_kpi_target_name_date')

    op.drop_table('kpi_targets')
    with op.batch_alter_table('training_modules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_modules_id'))

    op.drop_table('training_modules')
    with op.batch_alter_table('advanced_analytics_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_advanced_analytics_cache_id'))
        batch_op.drop_index('ix_adv_analytics_cache_period')
        batch_op.drop_index('ix_adv_analytics_cache_lookup')
        batch_op.drop_index('ix_adv_analytics_cache_dim')

    op.drop_table('advanced_analytics_cache')
    # ### end Alembic commands ###
