"""initial_squash_all_tables

Revision ID: db828d82089e
Revises: 
Create Date: 2026-04-18 00:39:08.537376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db828d82089e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advanced_analytics_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dimension_type', sa.Enum('NETWORK', 'GOVERNORATE', 'KINDERGARTEN', 'CLASS', 'CHILD', 'CITY', 'AREA', 'STAFF', 'PARENT', name='analyticsdimensiontype'), nullable=False),
    sa.Column('dimension_id', sa.String(length=100), nullable=False),
    sa.Column('period_type', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'QUARTERLY', 'YEARLY', name='analyticsperiodtype'), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('attendance_rate', sa.Float(), nullable=True),
    sa.Column('chronic_absence_rate', sa.Float(), nullable=True),
    sa.Column('incident_rate_per_100', sa.Float(), nullable=True),
    sa.Column('serious_incident_rate', sa.Float(), nullable=True),
    sa.Column('ratio_compliance_rate', sa.Float(), nullable=True),
    sa.Column('report_completion_rate', sa.Float(), nullable=True),
    sa.Column('parent_satisfaction_nps', sa.Float(), nullable=True),
    sa.Column('child_development_index', sa.Float(), nullable=True),
    sa.Column('staff_turnover_rate', sa.Float(), nullable=True),
    sa.Column('regulatory_compliance_score', sa.Float(), nullable=True),
    sa.Column('attendance_trend_slope', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('improvement_velocity', sa.Float(), nullable=True),
    sa.Column('attendance_incident_correlation', sa.Float(), nullable=True),
    sa.Column('staffing_quality_correlation', sa.Float(), nullable=True),
    sa.Column('health_alerts_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('advanced_analytics_cache', schema=None) as batch_op:
        batch_op.create_index('ix_adv_analytics_cache_dim', ['dimension_type', 'dimension_id'], unique=False)
        batch_op.create_index('ix_adv_analytics_cache_lookup', ['dimension_type', 'dimension_id', 'period_type', 'period_start', 'period_end'], unique=True)
        batch_op.create_index('ix_adv_analytics_cache_period', ['period_type', 'period_start', 'period_end'], unique=False)
        batch_op.create_index(batch_op.f('ix_advanced_analytics_cache_id'), ['id'], unique=False)

    op.create_table('analytics_dimension_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dimension_type', sa.Enum('NETWORK', 'GOVERNORATE', 'KINDERGARTEN', 'CLASS', 'CHILD', 'CITY', 'AREA', 'STAFF', 'PARENT', name='analyticsdimensiontype'), nullable=False),
    sa.Column('dimension_id', sa.String(length=100), nullable=False),
    sa.Column('period_type', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'QUARTERLY', 'YEARLY', name='analyticsperiodtype'), nullable=False),
    sa.Column('period_date', sa.Date(), nullable=False),
    sa.Column('total_capacity', sa.Integer(), nullable=True),
    sa.Column('total_enrolled', sa.Integer(), nullable=True),
    sa.Column('enrollment_rate', sa.Float(), nullable=True),
    sa.Column('pending_applications', sa.Integer(), nullable=True),
    sa.Column('expected_attendance', sa.Integer(), nullable=True),
    sa.Column('actual_attendance', sa.Integer(), nullable=True),
    sa.Column('attendance_rate', sa.Float(), nullable=True),
    sa.Column('chronic_absence_count', sa.Integer(), nullable=True),
    sa.Column('expected_reports', sa.Integer(), nullable=True),
    sa.Column('submitted_reports', sa.Integer(), nullable=True),
    sa.Column('report_completion_rate', sa.Float(), nullable=True),
    sa.Column('total_incidents', sa.Integer(), nullable=True),
    sa.Column('high_severity_incidents', sa.Integer(), nullable=True),
    sa.Column('incident_rate_per_100', sa.Float(), nullable=True),
    sa.Column('total_staff', sa.Integer(), nullable=True),
    sa.Column('ratio_compliant_minutes', sa.Integer(), nullable=True),
    sa.Column('ratio_total_minutes', sa.Integer(), nullable=True),
    sa.Column('ratio_compliance_rate', sa.Float(), nullable=True),
    sa.Column('surveys_sent', sa.Integer(), nullable=True),
    sa.Column('survey_responses', sa.Integer(), nullable=True),
    sa.Column('survey_response_rate', sa.Float(), nullable=True),
    sa.Column('nps_score', sa.Float(), nullable=True),
    sa.Column('governance_quality_index', sa.Float(), nullable=True),
    sa.Column('child_experience_index', sa.Float(), nullable=True),
    sa.Column('final_governance_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analytics_dimension_cache', schema=None) as batch_op:
        batch_op.create_index('ix_analytics_cache_dimension', ['dimension_type', 'dimension_id'], unique=False)
        batch_op.create_index('ix_analytics_cache_lookup', ['dimension_type', 'dimension_id', 'period_type', 'period_date'], unique=False)
        batch_op.create_index('ix_analytics_cache_period', ['period_type', 'period_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_dimension_cache_id'), ['id'], unique=False)

    op.create_table('benchmark_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metric_type', sa.String(length=100), nullable=False),
    sa.Column('scope_type', sa.String(length=50), nullable=False),
    sa.Column('scope_id', sa.String(length=100), nullable=True),
    sa.Column('comparison_group', sa.String(length=50), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('benchmark_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_benchmark_data_id'), ['id'], unique=False)
        batch_op.create_index('ix_benchmark_data_period', ['period_start', 'period_end'], unique=False)
        batch_op.create_index('ix_benchmark_data_scope', ['metric_type', 'scope_type', 'scope_id'], unique=False)

    op.create_table('data_quality_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('completeness_percent', sa.Float(), nullable=False),
    sa.Column('accuracy_score', sa.Float(), nullable=False),
    sa.Column('timeliness_score', sa.Float(), nullable=False),
    sa.Column('consistency_score', sa.Float(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_quality_metrics', schema=None) as batch_op:
        batch_op.create_index('ix_data_quality_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index('ix_data_quality_evaluated_at', ['evaluated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_quality_metrics_id'), ['id'], unique=False)

    op.create_table('import_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('stored_file_path', sa.String(length=500), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('imported_count', sa.Integer(), nullable=False),
    sa.Column('updated_count', sa.Integer(), nullable=False),
    sa.Column('skipped_count', sa.Integer(), nullable=False),
    sa.Column('errors_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_logs_id'), ['id'], unique=False)

    op.create_table('imported_kindergartens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_ar', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('governorate', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('area', sa.String(length=100), nullable=True),
    sa.Column('detailed_address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_ar', 'city', 'phone', name='uq_imported_kindergartens_name_city_phone')
    )
    with op.batch_alter_table('imported_kindergartens', schema=None) as batch_op:
        batch_op.create_index('idx_imported_kindergartens_city', ['city'], unique=False)
        batch_op.create_index('idx_imported_kindergartens_governorate', ['governorate'], unique=False)
        batch_op.create_index(batch_op.f('ix_imported_kindergartens_id'), ['id'], unique=False)

    op.create_table('kindergartens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_ar', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('governorate', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('area', sa.String(length=100), nullable=False),
    sa.Column('address_line', sa.Text(), nullable=False),
    sa.Column('contact_phone', sa.String(length=20), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'INACTIVE', name='kindergartenstatus'), nullable=False),
    sa.Column('operating_hours_start', sa.String(length=5), nullable=True),
    sa.Column('operating_hours_end', sa.String(length=5), nullable=True),
    sa.Column('license_number', sa.String(length=100), nullable=True),
    sa.Column('license_valid_until', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_number', name='uq_kindergartens_license_number')
    )
    with op.batch_alter_table('kindergartens', schema=None) as batch_op:
        batch_op.create_index('idx_kindergartens_governorate', ['governorate'], unique=False)
        batch_op.create_index('idx_kindergartens_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_kindergartens_id'), ['id'], unique=False)

    op.create_table('prediction_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metric_type', sa.String(length=100), nullable=False),
    sa.Column('scope_type', sa.String(length=50), nullable=False),
    sa.Column('scope_id', sa.String(length=100), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('params_hash', sa.String(length=128), nullable=False),
    sa.Column('points', sa.JSON(), nullable=False),
    sa.Column('forecast_points', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.JSON(), nullable=False),
    sa.Column('model_meta', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prediction_cache', schema=None) as batch_op:
        batch_op.create_index('ix_prediction_cache_created_at', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_prediction_cache_id'), ['id'], unique=False)
        batch_op.create_index('ix_prediction_cache_lookup', ['metric_type', 'scope_type', 'scope_id', 'params_hash'], unique=True)

    op.create_table('training_modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('training_modules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_modules_id'), ['id'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kindergarten_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('TRIP', 'MEETING', 'HOLIDAY', 'CELEBRATION', name='eventtype'), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('requires_consent_flag', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['kindergarten_id'], ['kindergartens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_id'), ['id'], unique=False)

    op.create_table('governance_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kindergarten_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('governance_quality_index', sa.Float(), nullable=False),
    sa.Column('child_experience_index', sa.Float(), nullable=False),
    sa.Column('final_governance_score', sa.Float(), nullable=False),
    sa.Column('band', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['kindergarten_id'], ['kindergartens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('governance_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_governance_scores_id'), ['id'], unique=False)

    op.create_table('kindergarten_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kindergarten_id', sa.Integer(), nullable=True),
    sa.Column('service_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('enabled_flag', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['kindergarten_id'], ['kindergartens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kindergarten_services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kindergarten_services_id'), ['id'], unique=False)

    op.create_table('kpi_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kindergarten_id', sa.Integer(), nullable=True),
    sa.Column('kpi_name', sa.String(length=100), nullable=False),
    sa.Column('kpi_value', sa.Float(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['kindergarten_id'], ['kindergartens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kpi_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kpi_snapshots_id'), ['id'], unique=False)

    op.create_table('kpi_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kpi_name', sa.String(length=100), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('kindergarten_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['kindergarten_id'], ['kindergartens.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kpi_name', 'effective_date', 'kindergarten_id', name='uq_kpi_target')
    )
    with op.batch_alter_table('kpi_targets', schema=None) as batch_op:
        batch_op.create_index('ix_kpi_target_name_date', ['kpi_name', 'effective_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_kpi_targets_id'), ['id'], unique=False)

    op.create_table('operating_calendar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kindergarten_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['kindergarten_id'], ['kindergartens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('operating_calendar', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operating_calendar_id'), ['id'], unique=False)

    op.create_table('ratio_compliance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kindergarten_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('operating_minutes', sa.Integer(), nullable=False),
    sa.Column('compliant_minutes', sa.Integer(), nullable=False),
    sa.Column('staff_count_avg', sa.Float(), nullable=False),
    sa.Column('child_count_avg', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['kindergarten_id'], ['kindergartens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ratio_compliance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ratio_compliance_id'), ['id'], unique=False)

    op.create_table('surveys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kindergarten_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('nps_question_enabled', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['kindergarten_id'], ['kindergartens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('surveys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_surveys_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'SUPERVISOR', 'PARENT', name='userrole'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'INACTIVE', name='userstatus'), nullable=False),
    sa.Column('kindergarten_id', sa.Integer(), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('national_id', sa.String(length=50), nullable=True),
    sa.Column('passport_number', sa.String(length=50), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('preferred_language', sa.String(length=10), server_default='ar', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(role != 'MANAGER') OR (kindergarten_id IS NOT NULL)", name='manager_must_have_kindergarten'),
    sa.ForeignKeyConstraint(['kindergarten_id'], ['kindergartens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index('ix_users_kindergarten_id', ['kindergarten_id'], unique=False)
        batch_op.create_index('ix_users_role', ['role'], unique=False)
        batch_op.create_index('ix_users_role_status', ['role', 'status'], unique=False)
        batch_op.create_index('ix_users_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('alert_thresholds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metric_type', sa.String(length=100), nullable=False),
    sa.Column('scope_type', sa.String(length=50), nullable=False),
    sa.Column('scope_id', sa.String(length=100), nullable=True),
    sa.Column('operator', sa.Enum('GT', 'GTE', 'LT', 'LTE', name='alertoperator'), nullable=False),
    sa.Column('threshold_value', sa.Float(), nullable=False),
    sa.Column('window_days', sa.Integer(), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severitylevel'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert_thresholds', schema=None) as batch_op:
        batch_op.create_index('ix_alert_thresholds_active', ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_thresholds_id'), ['id'], unique=False)
        batch_op.create_index('ix_alert_thresholds_scope', ['metric_type', 'scope_type', 'scope_id'], unique=False)

    op.create_table('anomaly_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metric_type', sa.String(length=100), nullable=False),
    sa.Column('scope_type', sa.String(length=50), nullable=False),
    sa.Column('scope_id', sa.String(length=100), nullable=True),
    sa.Column('detected_at', sa.Date(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severitylevel'), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('is_acknowledged', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_by', sa.Integer(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('anomaly_alerts', schema=None) as batch_op:
        batch_op.create_index('ix_anomaly_alerts_ack', ['is_acknowledged'], unique=False)
        batch_op.create_index('ix_anomaly_alerts_detected_at', ['detected_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_anomaly_alerts_id'), ['id'], unique=False)
        batch_op.create_index('ix_anomaly_alerts_metric_scope', ['metric_type', 'scope_type', 'scope_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('sensitivity_level', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('idx_audit_logs_action', ['action'], unique=False)
        batch_op.create_index('idx_audit_logs_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_audit_logs_entity_type', ['entity_type'], unique=False)
        batch_op.create_index('idx_audit_logs_user_id', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)

    op.create_table('daily_checklists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kindergarten_id', sa.Integer(), nullable=False),
    sa.Column('checklist_date', sa.Date(), nullable=False),
    sa.Column('checklist_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'NOT_REQUIRED', name='dailycheckliststatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('submitted_by', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['kindergarten_id'], ['kindergartens.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kindergarten_id', 'checklist_date', 'checklist_type', name='uq_daily_checklist_kindergarten_date_type')
    )
    with op.batch_alter_table('daily_checklists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_checklists_id'), ['id'], unique=False)
        batch_op.create_index('ix_daily_checklists_kindergarten_date', ['kindergarten_id', 'checklist_date'], unique=False)
        batch_op.create_index('ix_daily_checklists_status', ['status'], unique=False)

    op.create_table('drilldown_paths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scope_type', sa.String(length=50), nullable=False),
    sa.Column('scope_id', sa.String(length=100), nullable=True),
    sa.Column('visited_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('drilldown_paths', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drilldown_paths_id'), ['id'], unique=False)
        batch_op.create_index('ix_drilldown_paths_user_ts', ['user_id', 'visited_at'], unique=False)

    op.create_table('export_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('export_format', sa.Enum('CSV', 'PDF', 'EXCEL', name='exportformat'), nullable=False),
    sa.Column('report_type', sa.String(length=100), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='exportstatus'), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('export_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_export_jobs_id'), ['id'], unique=False)
        batch_op.create_index('ix_export_jobs_user_status', ['user_id', 'status'], unique=False)

    op.create_table('governance_reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('reminder_type', sa.String(length=50), nullable=False),
    sa.Column('sent_by', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('cooldown_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['sent_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('governance_reminders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_governance_reminders_id'), ['id'], unique=False)
        batch_op.create_index('ix_governance_reminders_target', ['target_type', 'target_id', 'cooldown_expires_at'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_type', sa.Enum('DIRECT', 'ANNOUNCEMENT', 'CLASS', 'BROADCAST', name='messagethreadtype'), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.Column('thread_id', sa.Integer(), nullable=True),
    sa.Column('reply_to_id', sa.Integer(), nullable=True),
    sa.Column('kindergarten_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('message_body', sa.Text(), nullable=False),
    sa.Column('allow_replies', sa.Boolean(), nullable=False),
    sa.Column('target_mode', sa.String(length=50), nullable=True),
    sa.Column('target_roles', sa.JSON(), nullable=True),
    sa.Column('target_governorates', sa.JSON(), nullable=True),
    sa.Column('target_kindergarten_ids', sa.JSON(), nullable=True),
    sa.Column('target_search', sa.String(length=255), nullable=True),
    sa.Column('recipient_count', sa.Integer(), nullable=True),
    sa.Column('translated_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['kindergarten_id'], ['kindergartens.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reply_to_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_id'), ['id'], unique=False)
        batch_op.create_index('ix_messages_kindergarten_created_at', ['kindergarten_id', 'created_at'], unique=False)
        batch_op.create_index('ix_messages_recipient_id', ['recipient_id'], unique=False)
        batch_op.create_index('ix_messages_sender_id', ['sender_id'], unique=False)
        batch_op.create_index('ix_messages_thread_id', ['thread_id'], unique=False)
        batch_op.create_index('ix_messages_thread_type', ['thread_type'], unique=False)

    op.create_table('parent_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('second_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('first_name_en', sa.String(length=100), nullable=True),
    sa.Column('last_name_en', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='gender'), nullable=False),
    sa.Column('nationality', sa.String(length=100), nullable=False),
    sa.Column('national_id', sa.String(length=50), nullable=True),
    sa.Column('passport_number', sa.String(length=50), nullable=True),
    sa.Column('home_governorate', sa.String(length=100), nullable=False),
    sa.Column('home_city', sa.String(length=100), nullable=False),
    sa.Column('home_area', sa.String(length=100), nullable=False),
    sa.Column('home_address_line', sa.Text(), nullable=False),
    sa.Column('work_address', sa.Text(), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=200), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True),
    sa.Column('emergency_contact_relationship', sa.String(length=100), nullable=True),
    sa.Column('relationship_to_child', sa.String(length=100), nullable=True),
    sa.Column('correspondence_preference', sa.Boolean(), nullable=False),
    sa.Column('profile_complete', sa.Boolean(), nullable=False),
    sa.Column('profile_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('parent_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parent_profiles_id'), ['id'], unique=False)
        batch_op.create_index('ix_parent_profiles_phone_number', ['phone_number'], unique=False)
        batch_op.create_index('uq_parent_profiles_national_id', ['national_id'], unique=True)

    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_id'), ['id'], unique=False)
        batch_op.create_index('ix_password_reset_tokens_used', ['used'], unique=False)
        batch_op.create_index('ix_password_reset_tokens_user_id', ['user_id'], unique=False)

    op.create_table('performance_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metric_type', sa.String(length=100), nullable=False),
    sa.Column('scope_type', sa.String(length=50), nullable=False),
    sa.Column('scope_id', sa.String(length=100), nullable=True),
    sa.Column('target_value', sa.Float(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('performance_targets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_performance_targets_id'), ['id'], unique=False)
        batch_op.create_index('ix_performance_targets_lookup', ['metric_type', 'scope_type', 'scope_id', 'effective_date'], unique=False)

    op.create_table('predictive_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metric_type', sa.String(length=100), nullable=False),
    sa.Column('scope_type', sa.String(length=50), nullable=False),
    sa.Column('scope_id', sa.String(length=100), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('training_start', sa.Date(), nullable=True),
    sa.Column('training_end', sa.Date(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('predictive_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_predictive_models_id'), ['id'], unique=False)
        batch_op.create_index('ix_predictive_models_metric_scope', ['metric_type', 'scope_type', 'scope_id'], unique=False)
        batch_op.create_index('ix_predictive_models_trained_at', ['trained_at'], unique=False)

    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kindergarten_id', sa.Integer(), nullable=True),
    sa.Column('scope_type', sa.String(length=50), nullable=False),
    sa.Column('scope_id', sa.String(length=100), nullable=True),
    sa.Column('metric_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severitylevel'), nullable=False),
    sa.Column('recommended_actions', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['kindergarten_id'], ['kindergartens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendations_id'), ['id'], unique=False)
        batch_op.create_index('ix_recommendations_kindergarten', ['kindergarten_id'], unique=False)
        batch_op.create_index('ix_recommendations_scope', ['scope_type', 'scope_id'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.Enum('INCIDENT_SUMMARY', 'ATTENDANCE_SUMMARY', 'COMPLIANCE_REPORT', name='reporttype'), nullable=False),
    sa.Column('scope_type', sa.Enum('KINDERGARTEN', 'GOVERNORATE', 'ALL', name='reportscopetype'), nullable=False),
    sa.Column('kindergarten_id', sa.Integer(), nullable=True),
    sa.Column('governorate', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('metrics_json', sa.JSON(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['kindergarten_id'], ['kindergartens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index('idx_reports_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_reports_created_by', ['created_by'], unique=False)
        batch_op.create_index('idx_reports_scope_type', ['scope_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_id'), ['id'], unique=False)

    op.create_table('staff_presence_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('kindergarten_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['kindergarten_id'], ['kindergartens.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('staff_presence_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staff_presence_logs_id'), ['id'], unique=False)

    op.create_table('staff_training_completion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('training_module_id', sa.Integer(), nullable=False),
    sa.Column('kindergarten_id', sa.Integer(), nullable=True),
    sa.Column('completion_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'OVERDUE', name='trainingstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['kindergarten_id'], ['kindergartens.id'], ),
    sa.ForeignKeyConstraint(['training_module_id'], ['training_modules.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'training_module_id', name='uq_staff_training')
    )
    with op.batch_alter_table('staff_training_completion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staff_training_completion_id'), ['id'], unique=False)
        batch_op.create_index('ix_staff_training_kindergarten', ['kindergarten_id'], unique=False)

    op.create_table('supervisor_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kindergarten_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['kindergarten_id'], ['kindergartens.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_id', 'kindergarten_id', name='uq_supervisor_profiles_user_kindergarten')
    )
    op.create_table('survey_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('nps_score', sa.Integer(), nullable=True),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('survey_id', 'parent_id', name='uq_survey_responses_survey_parent')
    )
    with op.batch_alter_table('survey_responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_survey_responses_id'), ['id'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kindergarten_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='taskstatus'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='taskpriority'), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['kindergarten_id'], ['kindergartens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_id'), ['id'], unique=False)

    op.create_table('user_dashboard_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('widget_config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('user_dashboard_preferences', schema=None) as batch_op:
        batch_op.create_index('idx_user_dashboard_preferences_user_id', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_dashboard_preferences_id'), ['id'], unique=False)

    op.create_table('user_device_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('platform', sa.Enum('IOS', 'ANDROID', 'WEB', name='deviceplatform'), nullable=False),
    sa.Column('device_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    with op.batch_alter_table('user_device_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_device_tokens_id'), ['id'], unique=False)
        batch_op.create_index('ix_user_device_tokens_platform', ['platform'], unique=False)
        batch_op.create_index('ix_user_device_tokens_user_id', ['user_id'], unique=False)

    op.create_table('user_filter_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filter_config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('user_filter_preferences', schema=None) as batch_op:
        batch_op.create_index('idx_user_filter_preferences_user_id', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_filter_preferences_id'), ['id'], unique=False)

    op.create_table('action_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=True),
    sa.Column('kindergarten_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='actionplanstatus'), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['kindergarten_id'], ['kindergartens.id'], ),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('action_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_action_plans_id'), ['id'], unique=False)
        batch_op.create_index('ix_action_plans_kindergarten', ['kindergarten_id'], unique=False)
        batch_op.create_index('ix_action_plans_status', ['status'], unique=False)

    op.create_table('active_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('threshold_id', sa.Integer(), nullable=False),
    sa.Column('metric_type', sa.String(length=100), nullable=False),
    sa.Column('scope_type', sa.String(length=50), nullable=False),
    sa.Column('scope_id', sa.String(length=100), nullable=True),
    sa.Column('current_value', sa.Float(), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severitylevel'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ACKNOWLEDGED', 'RESOLVED', name='alertstatus'), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_by', sa.Integer(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['threshold_id'], ['alert_thresholds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('active_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_active_alerts_id'), ['id'], unique=False)
        batch_op.create_index('ix_active_alerts_scope', ['metric_type', 'scope_type', 'scope_id'], unique=False)
        batch_op.create_index('ix_active_alerts_status', ['status'], unique=False)

    op.create_table('children',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='gender'), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('father_name', sa.String(length=255), nullable=False),
    sa.Column('mother_first_name', sa.String(length=100), nullable=False),
    sa.Column('mother_second_name', sa.String(length=100), nullable=True),
    sa.Column('mother_last_name', sa.String(length=100), nullable=False),
    sa.Column('mother_nationality', sa.String(length=100), nullable=False),
    sa.Column('mother_national_id', sa.String(length=50), nullable=True),
    sa.Column('mother_passport_number', sa.String(length=50), nullable=True),
    sa.Column('media_consent', sa.Boolean(), nullable=False),
    sa.Column('correspondence_flag', sa.Boolean(), nullable=False),
    sa.Column('profile_complete', sa.Boolean(), nullable=False),
    sa.Column('profile_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('second_name', sa.String(length=100), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('national_id', sa.String(length=50), nullable=True),
    sa.Column('passport_number', sa.String(length=50), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('photo_metadata', sa.JSON(), nullable=True),
    sa.Column('health_notes', sa.Text(), nullable=True),
    sa.Column('educational_notes', sa.Text(), nullable=True),
    sa.Column('has_special_needs', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('has_medical_condition', sa.Boolean(), server_default='false', nullable=False),
    sa.CheckConstraint('date_of_birth <= CURRENT_DATE', name='ck_children_dob_not_future'),
    sa.ForeignKeyConstraint(['parent_id'], ['parent_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'first_name', 'last_name', 'date_of_birth', name='uq_children_parent_name_dob')
    )
    with op.batch_alter_table('children', schema=None) as batch_op:
        batch_op.create_index('idx_child_dob', ['date_of_birth'], unique=False)
        batch_op.create_index('idx_child_parent_id', ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_children_id'), ['id'], unique=False)

    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kindergarten_id', sa.Integer(), nullable=False),
    sa.Column('name_ar', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=True),
    sa.Column('class_code', sa.String(length=32), nullable=False),
    sa.Column('age_group', sa.Enum('AGE_0_1', 'AGE_1_2', 'AGE_2_4', name='age_group_enum'), nullable=False),
    sa.Column('enrolled_children_count', sa.Integer(), nullable=False),
    sa.Column('capacity_total', sa.Integer(), nullable=False),
    sa.Column('min_age_months', sa.Integer(), nullable=False),
    sa.Column('max_age_months', sa.Integer(), nullable=False),
    sa.Column('supervisor_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['kindergarten_id'], ['kindergartens.id'], ),
    sa.ForeignKeyConstraint(['supervisor_id', 'kindergarten_id'], ['supervisor_profiles.user_id', 'supervisor_profiles.kindergarten_id'], name='fk_classes_supervisor_profile'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_code'),
    sa.UniqueConstraint('supervisor_id', name='uq_classes_supervisor')
    )
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.create_index('idx_classes_is_active', ['is_active'], unique=False)
        batch_op.create_index('idx_classes_kindergarten_id', ['kindergarten_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_classes_id'), ['id'], unique=False)

    op.create_table('message_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('storage_provider', sa.String(length=50), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_attachments_id'), ['id'], unique=False)
        batch_op.create_index('ix_message_attachments_message_id', ['message_id'], unique=False)
        batch_op.create_index('ix_message_attachments_uploaded_by', ['uploaded_by_id'], unique=False)

    op.create_table('message_recipients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('recipient_user_id', sa.Integer(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'recipient_user_id', name='uq_message_recipient')
    )
    with op.batch_alter_table('message_recipients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_recipients_id'), ['id'], unique=False)
        batch_op.create_index('ix_message_recipients_message_id', ['message_id'], unique=False)
        batch_op.create_index('ix_message_recipients_recipient_user_id', ['recipient_user_id'], unique=False)
        batch_op.create_index('ix_message_recipients_status', ['status'], unique=False)

    op.create_table('message_user_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'user_id', name='uq_message_user_state')
    )
    with op.batch_alter_table('message_user_states', schema=None) as batch_op:
        batch_op.create_index('ix_message_user_state_user_archived', ['user_id', 'archived_at'], unique=False)
        batch_op.create_index('ix_message_user_state_user_deleted', ['user_id', 'deleted_at'], unique=False)
        batch_op.create_index('ix_message_user_state_user_read', ['user_id', 'read_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_user_states_id'), ['id'], unique=False)

    op.create_table('absence_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('kindergarten_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('SUBMITTED', 'APPROVED', 'REJECTED', 'CANCELLED', name='absencerequeststatus'), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('start_date <= end_date', name='ck_absence_start_lte_end'),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['kindergarten_id'], ['kindergartens.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['parent_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('absence_requests', schema=None) as batch_op:
        batch_op.create_index('ix_absence_child_dates', ['child_id', 'start_date', 'end_date'], unique=False)
        batch_op.create_index('ix_absence_kg_status', ['kindergarten_id', 'status', 'created_at'], unique=False)
        batch_op.create_index('ix_absence_parent', ['parent_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_absence_requests_id'), ['id'], unique=False)

    op.create_table('attendance_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PRESENT', 'ABSENT', 'LATE', 'EXCUSED', name='attendancestatus'), nullable=False),
    sa.Column('check_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recorded_by', sa.Integer(), nullable=False),
    sa.Column('picked_by_name', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.CheckConstraint('(check_out_at IS NULL) OR (check_in_at IS NULL) OR (check_out_at >= check_in_at)', name='ck_attendance_checkout_after_checkin'),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('child_id', 'date', name='uq_attendance_child_date')
    )
    with op.batch_alter_table('attendance_logs', schema=None) as batch_op:
        batch_op.create_index('ix_attendance_class_date', ['class_id', 'date'], unique=False)
        batch_op.create_index('ix_attendance_class_id', ['class_id'], unique=False)
        batch_op.create_index('ix_attendance_date', ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_logs_id'), ['id'], unique=False)
        batch_op.create_index('ix_attendance_recorded_by', ['recorded_by'], unique=False)

    op.create_table('child_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('child_documents', schema=None) as batch_op:
        batch_op.create_index('idx_child_documents_child_id', ['child_id'], unique=False)
        batch_op.create_index('idx_child_documents_type', ['document_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_child_documents_id'), ['id'], unique=False)

    op.create_table('daily_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('kindergarten_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'SENT_TO_PARENT', 'REJECTED', 'RETURNED', name='dailyreportstatus'), nullable=False),
    sa.Column('submitted_by', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_to_parent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_reason', sa.Text(), nullable=True),
    sa.Column('arrival_time', sa.String(length=5), nullable=False),
    sa.Column('leave_time', sa.String(length=5), nullable=True),
    sa.Column('mood', sa.String(length=20), nullable=True),
    sa.Column('health_notes', sa.Text(), nullable=True),
    sa.Column('breakfast', sa.Boolean(), nullable=True),
    sa.Column('snack', sa.Boolean(), nullable=True),
    sa.Column('milk', sa.Boolean(), nullable=True),
    sa.Column('lunch', sa.Boolean(), nullable=True),
    sa.Column('nap_start', sa.String(length=5), nullable=True),
    sa.Column('nap_end', sa.String(length=5), nullable=True),
    sa.Column('nap_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('bathroom_count', sa.Integer(), nullable=True),
    sa.Column('diaper_wet', sa.Boolean(), nullable=True),
    sa.Column('diaper_soiled', sa.Boolean(), nullable=True),
    sa.Column('activities', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['kindergarten_id'], ['kindergartens.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kindergarten_id', 'child_id', 'date', name='uq_daily_report_kindergarten_child_date')
    )
    with op.batch_alter_table('daily_reports', schema=None) as batch_op:
        batch_op.create_index('ix_daily_reports_child_date', ['child_id', 'date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_reports_id'), ['id'], unique=False)

    op.create_table('enrollment_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('kindergarten_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'PENDING_REVIEW', 'ACCEPTED', 'REJECTED', 'WITHDRAWN', 'WAITLISTED', 'ACTIVE', name='enrollmentstatus'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('status_reason', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_by', sa.Integer(), nullable=True),
    sa.Column('decision_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enrollment_start_date', sa.Date(), nullable=True),
    sa.Column('enrollment_end_date', sa.Date(), nullable=True),
    sa.Column('class_assignment_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['decision_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['kindergarten_id'], ['kindergartens.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('child_id', 'kindergarten_id', name='uq_enrollment_child_kindergarten')
    )
    with op.batch_alter_table('enrollment_applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enrollment_applications_id'), ['id'], unique=False)
        batch_op.create_index('ix_enrollment_child_id', ['child_id'], unique=False)
        batch_op.create_index('ix_enrollment_child_status', ['child_id', 'status'], unique=False)
        batch_op.create_index('uq_enrollment_child_active', ['child_id', 'is_active'], unique=True)

    op.create_table('health_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('health_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_health_alerts_id'), ['id'], unique=False)

    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('kindergarten_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('INJURY', 'BEHAVIOR', 'ILLNESS', 'OTHER', name='incidenttype'), nullable=False),
    sa.Column('severity_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severitylevel'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notify_parent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('followup_required_flag', sa.Boolean(), nullable=False),
    sa.Column('followup_sla_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['kindergarten_id'], ['kindergartens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incidents_id'), ['id'], unique=False)

    op.create_table('observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('observed_by', sa.Integer(), nullable=False),
    sa.Column('domain', sa.Enum('SOCIAL_EMOTIONAL', 'PHYSICAL', 'COGNITIVE', 'LANGUAGE', name='learningdomain'), nullable=False),
    sa.Column('observation_text', sa.Text(), nullable=False),
    sa.Column('mastery_level', sa.Enum('ON_TRACK', 'NEEDS_SUPPORT', 'EXCEEDS', name='masterylevel'), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['observed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_observations_id'), ['id'], unique=False)

    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='portfoliostatus'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parent_viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolios_id'), ['id'], unique=False)

    op.create_table('safeguarding_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('kindergarten_id', sa.Integer(), nullable=False),
    sa.Column('case_description', sa.Text(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sla_escalation_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sla_closure_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['kindergarten_id'], ['kindergartens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('safeguarding_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_safeguarding_cases_id'), ['id'], unique=False)

    op.create_table('supervisor_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('supervisor_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('full_time_dedication', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['supervisor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supervisor_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supervisor_assignments_id'), ['id'], unique=False)

    op.create_table('daily_report_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('daily_report_id', sa.Integer(), nullable=False),
    sa.Column('parent_user_id', sa.Integer(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['daily_report_id'], ['daily_reports.id'], ),
    sa.ForeignKeyConstraint(['parent_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('daily_report_id', 'parent_user_id', name='uq_daily_report_view')
    )
    with op.batch_alter_table('daily_report_views', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_report_views_id'), ['id'], unique=False)
        batch_op.create_index('ix_daily_report_views_report', ['daily_report_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('daily_report_id', sa.Integer(), nullable=True),
    sa.Column('absence_request_id', sa.Integer(), nullable=True),
    sa.Column('notification_type', sa.Enum('MESSAGE', 'DAILY_REPORT_SENT', 'DAILY_REPORT_SUBMITTED', 'DAILY_REPORT_REJECTED', 'DAILY_REPORT_MISSING', 'ABSENCE_REQUEST_SUBMITTED', 'ABSENCE_REQUEST_APPROVED', 'ABSENCE_REQUEST_REJECTED', 'ATTENDANCE_CORRECTED', 'SYSTEM', 'GOVERNANCE_REMINDER', name='notificationtype'), nullable=True),
    sa.Column('channel', sa.Enum('EMAIL', 'PUSH', 'IN_APP', name='notificationchannel'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', name='notificationstatus'), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['absence_request_id'], ['absence_requests.id'], ),
    sa.ForeignKeyConstraint(['daily_report_id'], ['daily_reports.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notifications_channel', ['channel'], unique=False)
        batch_op.create_index('ix_notifications_daily_report', ['daily_report_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_id'), ['id'], unique=False)
        batch_op.create_index('ix_notifications_message', ['message_id'], unique=False)
        batch_op.create_index('ix_notifications_user_status', ['user_id', 'status'], unique=False)

    op.create_table('waitlist_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enrollment_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('WAITLISTED', 'OFFERED', 'ACCEPTED', 'DECLINED', 'EXPIRED', name='waitliststatus'), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('offer_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('offer_expiry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollment_applications.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enrollment_id')
    )
    with op.batch_alter_table('waitlist_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_waitlist_entries_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waitlist_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_waitlist_entries_id'))

    op.drop_table('waitlist_entries')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_user_status')
        batch_op.drop_index('ix_notifications_message')
        batch_op.drop_index(batch_op.f('ix_notifications_id'))
        batch_op.drop_index('ix_notifications_daily_report')
        batch_op.drop_index('ix_notifications_channel')

    op.drop_table('notifications')
    with op.batch_alter_table('daily_report_views', schema=None) as batch_op:
        batch_op.drop_index('ix_daily_report_views_report')
        batch_op.drop_index(batch_op.f('ix_daily_report_views_id'))

    op.drop_table('daily_report_views')
    with op.batch_alter_table('supervisor_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supervisor_assignments_id'))

    op.drop_table('supervisor_assignments')
    with op.batch_alter_table('safeguarding_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_safeguarding_cases_id'))

    op.drop_table('safeguarding_cases')
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolios_id'))

    op.drop_table('portfolios')
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_observations_id'))

    op.drop_table('observations')
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incidents_id'))

    op.drop_table('incidents')
    with op.batch_alter_table('health_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_health_alerts_id'))

    op.drop_table('health_alerts')
    with op.batch_alter_table('enrollment_applications', schema=None) as batch_op:
        batch_op.drop_index('uq_enrollment_child_active')
        batch_op.drop_index('ix_enrollment_child_status')
        batch_op.drop_index('ix_enrollment_child_id')
        batch_op.drop_index(batch_op.f('ix_enrollment_applications_id'))

    op.drop_table('enrollment_applications')
    with op.batch_alter_table('daily_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_reports_id'))
        batch_op.drop_index('ix_daily_reports_child_date')

    op.drop_table('daily_reports')
    with op.batch_alter_table('child_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_child_documents_id'))
        batch_op.drop_index('idx_child_documents_type')
        batch_op.drop_index('idx_child_documents_child_id')

    op.drop_table('child_documents')
    with op.batch_alter_table('attendance_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_attendance_recorded_by')
        batch_op.drop_index(batch_op.f('ix_attendance_logs_id'))
        batch_op.drop_index('ix_attendance_date')
        batch_op.drop_index('ix_attendance_class_id')
        batch_op.drop_index('ix_attendance_class_date')

    op.drop_table('attendance_logs')
    with op.batch_alter_table('absence_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_absence_requests_id'))
        batch_op.drop_index('ix_absence_parent')
        batch_op.drop_index('ix_absence_kg_status')
        batch_op.drop_index('ix_absence_child_dates')

    op.drop_table('absence_requests')
    with op.batch_alter_table('message_user_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_user_states_id'))
        batch_op.drop_index('ix_message_user_state_user_read')
        batch_op.drop_index('ix_message_user_state_user_deleted')
        batch_op.drop_index('ix_message_user_state_user_archived')

    op.drop_table('message_user_states')
    with op.batch_alter_table('message_recipients', schema=None) as batch_op:
        batch_op.drop_index('ix_message_recipients_status')
        batch_op.drop_index('ix_message_recipients_recipient_user_id')
        batch_op.drop_index('ix_message_recipients_message_id')
        batch_op.drop_index(batch_op.f('ix_message_recipients_id'))

    op.drop_table('message_recipients')
    with op.batch_alter_table('message_attachments', schema=None) as batch_op:
        batch_op.drop_index('ix_message_attachments_uploaded_by')
        batch_op.drop_index('ix_message_attachments_message_id')
        batch_op.drop_index(batch_op.f('ix_message_attachments_id'))

    op.drop_table('message_attachments')
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_classes_id'))
        batch_op.drop_index('idx_classes_kindergarten_id')
        batch_op.drop_index('idx_classes_is_active')

    op.drop_table('classes')
    with op.batch_alter_table('children', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_children_id'))
        batch_op.drop_index('idx_child_parent_id')
        batch_op.drop_index('idx_child_dob')

    op.drop_table('children')
    with op.batch_alter_table('active_alerts', schema=None) as batch_op:
        batch_op.drop_index('ix_active_alerts_status')
        batch_op.drop_index('ix_active_alerts_scope')
        batch_op.drop_index(batch_op.f('ix_active_alerts_id'))

    op.drop_table('active_alerts')
    with op.batch_alter_table('action_plans', schema=None) as batch_op:
        batch_op.drop_index('ix_action_plans_status')
        batch_op.drop_index('ix_action_plans_kindergarten')
        batch_op.drop_index(batch_op.f('ix_action_plans_id'))

    op.drop_table('action_plans')
    with op.batch_alter_table('user_filter_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_filter_preferences_id'))
        batch_op.drop_index('idx_user_filter_preferences_user_id')

    op.drop_table('user_filter_preferences')
    with op.batch_alter_table('user_device_tokens', schema=None) as batch_op:
        batch_op.drop_index('ix_user_device_tokens_user_id')
        batch_op.drop_index('ix_user_device_tokens_platform')
        batch_op.drop_index(batch_op.f('ix_user_device_tokens_id'))

    op.drop_table('user_device_tokens')
    with op.batch_alter_table('user_dashboard_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_dashboard_preferences_id'))
        batch_op.drop_index('idx_user_dashboard_preferences_user_id')

    op.drop_table('user_dashboard_preferences')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_id'))

    op.drop_table('tasks')
    with op.batch_alter_table('survey_responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_survey_responses_id'))

    op.drop_table('survey_responses')
    op.drop_table('supervisor_profiles')
    with op.batch_alter_table('staff_training_completion', schema=None) as batch_op:
        batch_op.drop_index('ix_staff_training_kindergarten')
        batch_op.drop_index(batch_op.f('ix_staff_training_completion_id'))

    op.drop_table('staff_training_completion')
    with op.batch_alter_table('staff_presence_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_presence_logs_id'))

    op.drop_table('staff_presence_logs')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_id'))
        batch_op.drop_index('idx_reports_scope_type')
        batch_op.drop_index('idx_reports_created_by')
        batch_op.drop_index('idx_reports_created_at')

    op.drop_table('reports')
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.drop_index('ix_recommendations_scope')
        batch_op.drop_index('ix_recommendations_kindergarten')
        batch_op.drop_index(batch_op.f('ix_recommendations_id'))

    op.drop_table('recommendations')
    with op.batch_alter_table('predictive_models', schema=None) as batch_op:
        batch_op.drop_index('ix_predictive_models_trained_at')
        batch_op.drop_index('ix_predictive_models_metric_scope')
        batch_op.drop_index(batch_op.f('ix_predictive_models_id'))

    op.drop_table('predictive_models')
    with op.batch_alter_table('performance_targets', schema=None) as batch_op:
        batch_op.drop_index('ix_performance_targets_lookup')
        batch_op.drop_index(batch_op.f('ix_performance_targets_id'))

    op.drop_table('performance_targets')
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index('ix_password_reset_tokens_user_id')
        batch_op.drop_index('ix_password_reset_tokens_used')
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_id'))

    op.drop_table('password_reset_tokens')
    with op.batch_alter_table('parent_profiles', schema=None) as batch_op:
        batch_op.drop_index('uq_parent_profiles_national_id')
        batch_op.drop_index('ix_parent_profiles_phone_number')
        batch_op.drop_index(batch_op.f('ix_parent_profiles_id'))

    op.drop_table('parent_profiles')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index('ix_messages_thread_type')
        batch_op.drop_index('ix_messages_thread_id')
        batch_op.drop_index('ix_messages_sender_id')
        batch_op.drop_index('ix_messages_recipient_id')
        batch_op.drop_index('ix_messages_kindergarten_created_at')
        batch_op.drop_index(batch_op.f('ix_messages_id'))

    op.drop_table('messages')
    with op.batch_alter_table('governance_reminders', schema=None) as batch_op:
        batch_op.drop_index('ix_governance_reminders_target')
        batch_op.drop_index(batch_op.f('ix_governance_reminders_id'))

    op.drop_table('governance_reminders')
    with op.batch_alter_table('export_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_export_jobs_user_status')
        batch_op.drop_index(batch_op.f('ix_export_jobs_id'))

    op.drop_table('export_jobs')
    with op.batch_alter_table('drilldown_paths', schema=None) as batch_op:
        batch_op.drop_index('ix_drilldown_paths_user_ts')
        batch_op.drop_index(batch_op.f('ix_drilldown_paths_id'))

    op.drop_table('drilldown_paths')
    with op.batch_alter_table('daily_checklists', schema=None) as batch_op:
        batch_op.drop_index('ix_daily_checklists_status')
        batch_op.drop_index('ix_daily_checklists_kindergarten_date')
        batch_op.drop_index(batch_op.f('ix_daily_checklists_id'))

    op.drop_table('daily_checklists')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))
        batch_op.drop_index('idx_audit_logs_user_id')
        batch_op.drop_index('idx_audit_logs_entity_type')
        batch_op.drop_index('idx_audit_logs_created_at')
        batch_op.drop_index('idx_audit_logs_action')

    op.drop_table('audit_logs')
    with op.batch_alter_table('anomaly_alerts', schema=None) as batch_op:
        batch_op.drop_index('ix_anomaly_alerts_metric_scope')
        batch_op.drop_index(batch_op.f('ix_anomaly_alerts_id'))
        batch_op.drop_index('ix_anomaly_alerts_detected_at')
        batch_op.drop_index('ix_anomaly_alerts_ack')

    op.drop_table('anomaly_alerts')
    with op.batch_alter_table('alert_thresholds', schema=None) as batch_op:
        batch_op.drop_index('ix_alert_thresholds_scope')
        batch_op.drop_index(batch_op.f('ix_alert_thresholds_id'))
        batch_op.drop_index('ix_alert_thresholds_active')

    op.drop_table('alert_thresholds')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index('ix_users_status')
        batch_op.drop_index('ix_users_role_status')
        batch_op.drop_index('ix_users_role')
        batch_op.drop_index('ix_users_kindergarten_id')
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('surveys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_surveys_id'))

    op.drop_table('surveys')
    with op.batch_alter_table('ratio_compliance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ratio_compliance_id'))

    op.drop_table('ratio_compliance')
    with op.batch_alter_table('operating_calendar', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operating_calendar_id'))

    op.drop_table('operating_calendar')
    with op.batch_alter_table('kpi_targets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kpi_targets_id'))
        batch_op.drop_index('ix_kpi_target_name_date')

    op.drop_table('kpi_targets')
    with op.batch_alter_table('kpi_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kpi_snapshots_id'))

    op.drop_table('kpi_snapshots')
    with op.batch_alter_table('kindergarten_services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kindergarten_services_id'))

    op.drop_table('kindergarten_services')
    with op.batch_alter_table('governance_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_governance_scores_id'))

    op.drop_table('governance_scores')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_id'))

    op.drop_table('events')
    with op.batch_alter_table('training_modules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_modules_id'))

    op.drop_table('training_modules')
    with op.batch_alter_table('prediction_cache', schema=None) as batch_op:
        batch_op.drop_index('ix_prediction_cache_lookup')
        batch_op.drop_index(batch_op.f('ix_prediction_cache_id'))
        batch_op.drop_index('ix_prediction_cache_created_at')

    op.drop_table('prediction_cache')
    with op.batch_alter_table('kindergartens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kindergartens_id'))
        batch_op.drop_index('idx_kindergartens_status')
        batch_op.drop_index('idx_kindergartens_governorate')

    op.drop_table('kindergartens')
    with op.batch_alter_table('imported_kindergartens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_imported_kindergartens_id'))
        batch_op.drop_index('idx_imported_kindergartens_governorate')
        batch_op.drop_index('idx_imported_kindergartens_city')

    op.drop_table('imported_kindergartens')
    with op.batch_alter_table('import_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_logs_id'))

    op.drop_table('import_logs')
    with op.batch_alter_table('data_quality_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_quality_metrics_id'))
        batch_op.drop_index('ix_data_quality_evaluated_at')
        batch_op.drop_index('ix_data_quality_entity')

    op.drop_table('data_quality_metrics')
    with op.batch_alter_table('benchmark_data', schema=None) as batch_op:
        batch_op.drop_index('ix_benchmark_data_scope')
        batch_op.drop_index('ix_benchmark_data_period')
        batch_op.drop_index(batch_op.f('ix_benchmark_data_id'))

    op.drop_table('benchmark_data')
    with op.batch_alter_table('analytics_dimension_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analytics_dimension_cache_id'))
        batch_op.drop_index('ix_analytics_cache_period')
        batch_op.drop_index('ix_analytics_cache_lookup')
        batch_op.drop_index('ix_analytics_cache_dimension')

    op.drop_table('analytics_dimension_cache')
    with op.batch_alter_table('advanced_analytics_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_advanced_analytics_cache_id'))
        batch_op.drop_index('ix_adv_analytics_cache_period')
        batch_op.drop_index('ix_adv_analytics_cache_lookup')
        batch_op.drop_index('ix_adv_analytics_cache_dim')

    op.drop_table('advanced_analytics_cache')
    # ### end Alembic commands ###
