"""analytics cache and enums

Revision ID: f3da6d982bac
Revises: a1b2c3d4e5f6
Create Date: 2026-01-18 06:17:11.043833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3da6d982bac'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Get the current database dialect
    bind = op.get_bind()
    dialect = bind.dialect.name

    # Skip PostgreSQL-specific operations on SQLite
    if dialect == 'postgresql':
        # Ensure enums exist before altering columns (idempotent)
        op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'analyticsdimensiontype') THEN
                CREATE TYPE analyticsdimensiontype AS ENUM ('NETWORK', 'GOVERNORATE', 'KINDERGARTEN', 'CLASS', 'CHILD', 'CITY', 'AREA', 'STAFF', 'PARENT');
            END IF;
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'analyticsperiodtype') THEN
                CREATE TYPE analyticsperiodtype AS ENUM ('DAILY', 'WEEKLY', 'MONTHLY', 'QUARTERLY', 'YEARLY');
            END IF;
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'attendancemethod') THEN
                CREATE TYPE attendancemethod AS ENUM ('PIN', 'QR', 'KIOSK', 'MANUAL');
            END IF;
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'exportformat') THEN
                CREATE TYPE exportformat AS ENUM ('CSV', 'PDF', 'EXCEL');
            END IF;
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'exportstatus') THEN
                CREATE TYPE exportstatus AS ENUM ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED');
            END IF;
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'kindergartenstatus') THEN
                CREATE TYPE kindergartenstatus AS ENUM ('DRAFT', 'ACTIVE', 'INACTIVE');
            END IF;
        END$$;
        """)

        op.alter_column('analytics_dimension_cache', 'dimension_type',
                   existing_type=sa.VARCHAR(length=20),
                   type_=sa.Enum('NETWORK', 'GOVERNORATE', 'KINDERGARTEN', 'CLASS', 'CHILD', 'CITY', 'AREA', 'STAFF', 'PARENT', name='analyticsdimensiontype'),
                   existing_nullable=False,
                   postgresql_using="dimension_type::analyticsdimensiontype")
        op.alter_column('analytics_dimension_cache', 'period_type',
                   existing_type=sa.VARCHAR(length=20),
                   type_=sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'QUARTERLY', 'YEARLY', name='analyticsperiodtype'),
                   existing_nullable=False,
                   postgresql_using="period_type::analyticsperiodtype")
        op.alter_column('attendance_logs', 'method',
                   existing_type=sa.VARCHAR(length=5),
                   type_=sa.Enum('PIN', 'QR', 'KIOSK', 'MANUAL', name='attendancemethod'),
                   existing_nullable=False,
                   postgresql_using="method::attendancemethod")
        op.alter_column('export_jobs', 'export_format',
                   existing_type=sa.VARCHAR(length=20),
                   type_=sa.Enum('CSV', 'PDF', 'EXCEL', name='exportformat'),
                   existing_nullable=False,
                   postgresql_using="export_format::exportformat")
        op.alter_column('export_jobs', 'status',
                   existing_type=sa.VARCHAR(length=20),
                   type_=sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='exportstatus'),
                   existing_nullable=False,
                   postgresql_using="status::exportstatus")
        op.alter_column('kindergartens', 'status',
                   existing_type=sa.VARCHAR(length=10),
                   type_=sa.Enum('DRAFT', 'ACTIVE', 'INACTIVE', name='kindergartenstatus'),
                   existing_nullable=False,
                   existing_server_default=sa.text("'DRAFT'"),
                   postgresql_using="status::kindergartenstatus")

        # Drop indexes only on PostgreSQL (may not exist on fresh SQLite)
        op.drop_index('ix_attendance_logs_date_child', table_name='attendance_logs')
        op.drop_index('ix_daily_reports_date_status', table_name='daily_reports')
        op.drop_index('ix_incidents_occurred_kg', table_name='incidents')
        op.drop_index('ix_kindergartens_governorate', table_name='kindergartens')

    # SQLite: no-op since enums are stored as VARCHAR and indexes may differ
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        # SQLite path in upgrade is intentionally no-op.
        return

    # password_reset_tokens adjustments skipped (handled in earlier revisions)
    op.create_index('ix_kindergartens_governorate', 'kindergartens', ['governorate', 'status'], unique=False)
    op.alter_column('kindergartens', 'status',
               existing_type=sa.Enum('DRAFT', 'ACTIVE', 'INACTIVE', name='kindergartenstatus'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False,
               existing_server_default=sa.text("'DRAFT'"))
    op.create_index('ix_incidents_occurred_kg', 'incidents', ['occurred_at', 'kindergarten_id'], unique=False)
    op.alter_column('export_jobs', 'status',
               existing_type=sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='exportstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('export_jobs', 'export_format',
               existing_type=sa.Enum('CSV', 'PDF', 'EXCEL', name='exportformat'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.create_index('ix_daily_reports_date_status', 'daily_reports', ['date', 'status'], unique=False)
    op.create_index('ix_attendance_logs_date_child', 'attendance_logs', ['date', 'child_id'], unique=False)
    op.alter_column('attendance_logs', 'method',
               existing_type=sa.Enum('PIN', 'QR', 'KIOSK', 'MANUAL', name='attendancemethod'),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False)
    op.alter_column('analytics_dimension_cache', 'period_type',
               existing_type=sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'QUARTERLY', 'YEARLY', name='analyticsperiodtype'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('analytics_dimension_cache', 'dimension_type',
               existing_type=sa.Enum('NETWORK', 'GOVERNORATE', 'KINDERGARTEN', 'CLASS', 'CHILD', 'CITY', 'AREA', 'STAFF', 'PARENT', name='analyticsdimensiontype'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###
