"""Shared field-label maps (Arabic + English) for summary/column keys.

Extracted from the monolithic ``agency_reports_service.py`` to eliminate
duplication: every agency service imports these from one place.
"""
from __future__ import annotations

_FIELD_LABELS: dict[str, str] = {
    "admission_year": "سنة القبول",
    "cutoff_date": "تاريخ القطع (مواليد قبل)",
    "eligible_children": "الأطفال المؤهلون",
    "total_children": "إجمالي الأطفال",
    "total_kindergartens": "إجمالي الحضانات",
    "active_kindergartens": "الحضانات النشطة",
    "managers": "المدراء",
    "supervisors": "المشرفون",
    "total_staff": "إجمالي الكوادر",
    "training_records": "سجلات التدريب",
    "completed": "المكتملة",
    "completion_rate_pct": "نسبة الإكمال %",
    "message_count": "عدد الرسائل",
    "incident_count": "إجمالي حوادث السلامة",
    "eligible_child_days": "أيام الأطفال المؤهلة",
    "incident_rate_per_1000_child_days": "معدل الحوادث لكل 1000 يوم طفل",
    "areas": "عدد المناطق",
    "children": "الأطفال",
    "enrolled_children": "الأطفال المسجلون",
    "total_institutions": "إجمالي المؤسسات",
    "active_institutions": "المؤسسات النشطة",
    "licensed_institutions": "المؤسسات المرخّصة (سارية)",
    "active_and_licensed": "نشطة ومرخّصة",
    "expired_licenses": "تراخيص منتهية",
    "missing_license_data": "بدون بيانات ترخيص",
    "total_capacity": "الطاقة الاستيعابية",
    "total_enrolled": "العدد الفعلي للمسجلين",
    "occupancy_rate_pct": "نسبة الإشغال %",
    "occupancy_rate": "نسبة الإشغال %",
    "overcrowded_kindergartens": "الحضانات المكتظة",
    "overcrowding_rate_pct": "نسبة الاكتظاظ %",
    "total_records": "إجمالي السجلات",
    "present_records": "سجلات الحضور",
    "absent_records": "سجلات الغياب",
    "attendance_rate_pct": "نسبة الحضور %",
    "absence_rate_pct": "نسبة الغياب %",
    "total_supervisors": "إجمالي المشرفين",
    "children_missing_dob": "أطفال بدون تاريخ ميلاد",
    "data_quality_note_ar": "ملاحظة جودة البيانات",
    "trend_years": "سنوات القياس",
    "period_start": "بداية الفترة",
    "period_end": "نهاية الفترة",
    "total_enrolled_children": "إجمالي الأطفال المسجلين",
    "period": "الفترة",
    "quarter": "الربع",
    "النسبة %": "النسبة %",
    "governorate": "المحافظة",
    "city": "المدينة/اللواء",
    "district": "اللواء",
    "area": "المنطقة/الحي",
    "gender": "الجنس",
    "count": "العدد",
    "status": "الحالة",
    "role": "الدور",
    "severity": "درجة الخطورة",
    "thread_type": "نوع المحادثة",
    "children_per_kindergarten": "أطفال لكل حضانة",
    "age_group": "الفئة العمرية",
    "enrolled_total": "إجمالي المسجلين (0-60)",
    "enrolled_0_11m": "0-11 شهر",
    "enrolled_12_23m": "12-23 شهر",
    "enrolled_24_35m": "24-35 شهر",
    "enrolled_36_47m": "36-47 شهر",
    "enrolled_48_60m": "48-60 شهر",
    "enrolled": "الأطفال المسجلين",
    "children_per_supervisor": "أطفال لكل مشرف",
    "missing_dob": "بدون تاريخ ميلاد",
    "year": "السنة",
    "new_kindergartens": "حضانات جديدة",
    "national_ratio": "المعدل الوطني للأطفال لكل حضانة",
    "unserved_districts_count": "عدد الألوية المحرومة",
    "unserved_children_count": "الأطفال غير المخدومين في المناطق المحرومة",
    "is_unserved_zone": "منطقة محرومة",
    "status_ar": "حالة الخدمة",
    "available_expansion_capacity": "سعة التوسع المتاحة",
    "is_overcrowded": "حالة الاكتظاظ",
    "investment_priority_score": "مؤشر أولوية الاستثمار التنموي",
    "priority_level_ar": "درجة الأولوية",
    "priority_rank": "الترتيب التنموي",
    "governorates_count": "عدد المحافظات المشمولة",
    "top_priority_governorate": "المحافظة الأعلى أولوية",
    "average_investment_priority_score": "متوسط درجة الأولوية الوطني",
    "vaccine": "المطعوم",
    "due_age": "العمر المستحق",
    "vaccines_in_schedule": "عدد المطاعيم في الجدول",
    "children_considered": "الأطفال المشمولون",
    "vaccine_doses_due": "إجمالي الجرعات المستحقة",
    "ineligible_children": "الأطفال غير المؤهلين",
    "unevaluatable_records": "سجلات تعذر تقييمها",
    "eligibility_rate": "نسبة المؤهلين %",
    "data_completeness_rate": "نسبة اكتمال البيانات %",
    "highest_governorate": "أعلى محافظة",
    "total_evaluated": "إجمالي السجلات المشمولة",
    "total_licensed_capacity": "مجموع السعة الاستيعابية",
    "overall_occupancy_rate": "نسبة الإشغال الكلية %",
    "critical_high_incidents": "الحوادث عالية الخطورة والحرجة",
    "share_pct": "النسبة %",
    "indicator": "المؤشر",
    "category": "التصنيف",
    "value": "القيمة",
}

_FIELD_LABELS_EN: dict[str, str] = {
    "admission_year": "Admission Year",
    "cutoff_date": "Cutoff Date (born before)",
    "eligible_children": "Eligible Children",
    "total_children": "Total Children",
    "total_kindergartens": "Total Kindergartens",
    "active_kindergartens": "Active Kindergartens",
    "managers": "Managers",
    "supervisors": "Supervisors",
    "total_staff": "Total Staff",
    "training_records": "Training Records",
    "completed": "Completed",
    "completion_rate_pct": "Completion Rate %",
    "message_count": "Message Count",
    "incident_count": "Incident Count",
    "eligible_child_days": "Eligible Child-Days",
    "incident_rate_per_1000_child_days": "Incident Rate per 1000 Child-Days",
    "areas": "Number of Areas",
    "children": "Children",
    "enrolled_children": "Enrolled Children",
    "total_institutions": "Total Institutions",
    "active_institutions": "Active Institutions",
    "licensed_institutions": "Licensed Institutions (Active)",
    "active_and_licensed": "Active and Licensed",
    "expired_licenses": "Expired Licenses",
    "missing_license_data": "Missing License Data",
    "total_capacity": "Total Capacity",
    "total_enrolled": "Actual Enrolled Count",
    "occupancy_rate_pct": "Occupancy Rate %",
    "occupancy_rate": "Occupancy Rate %",
    "overcrowded_kindergartens": "Overcrowded Kindergartens",
    "overcrowding_rate_pct": "Overcrowding Rate %",
    "total_records": "Total Records",
    "present_records": "Present Records",
    "absent_records": "Absent Records",
    "attendance_rate_pct": "Attendance Rate %",
    "absence_rate_pct": "Absence Rate %",
    "total_supervisors": "Total Supervisors",
    "children_missing_dob": "Children Missing Date of Birth",
    "data_quality_note_ar": "Data Quality Note",
    "trend_years": "Measurement Years",
    "period_start": "Period Start",
    "period_end": "Period End",
    "total_enrolled_children": "Total Enrolled Children",
    "period": "Period",
    "quarter": "Quarter",
    "share_pct": "Share %",
    "indicator": "Indicator",
    "category": "Category",
    "value": "Value",
    "governorate": "Governorate",
    "city": "City/District",
    "district": "District",
    "area": "Area/Neighborhood",
    "gender": "Gender",
    "count": "Count",
    "status": "Status",
    "role": "Role",
    "severity": "Severity",
    "thread_type": "Conversation Type",
    "children_per_kindergarten": "Children per Kindergarten",
    "age_group": "Age Group",
    "enrolled_total": "Total Enrolled (0-60)",
    "enrolled_0_11m": "0-11 months",
    "enrolled_12_23m": "12-23 months",
    "enrolled_24_35m": "24-35 months",
    "enrolled_36_47m": "36-47 months",
    "enrolled_48_60m": "48-60 months",
    "enrolled": "Enrolled Children",
    "children_per_supervisor": "Children per Supervisor",
    "missing_dob": "Missing Date of Birth",
    "year": "Year",
    "new_kindergartens": "New Kindergartens",
    "national_ratio": "National Ratio of Children per Kindergarten",
    "unserved_districts_count": "Number of Underserved Districts",
    "unserved_children_count": "Underserved Children in Deprived Areas",
    "is_unserved_zone": "Underserved Zone",
    "status_ar": "Service Status",
    "available_expansion_capacity": "Available Expansion Capacity",
    "is_overcrowded": "Overcrowding Status",
    "investment_priority_score": "Developmental Investment Priority Score",
    "priority_level_ar": "Priority Level",
    "priority_rank": "Developmental Rank",
    "governorates_count": "Number of Governorates Covered",
    "النسبة %": "Share %",
    "top_priority_governorate": "Top Priority Governorate",
    "average_investment_priority_score": "Average National Priority Score",
    "vaccine": "Vaccine",
    "due_age": "Due Age",
    "vaccines_in_schedule": "Vaccines in Schedule",
    "children_considered": "Children Considered",
    "vaccine_doses_due": "Total Due Doses",
    "ineligible_children": "Ineligible Children",
    "unevaluatable_records": "Records That Could Not Be Evaluated",
    "eligibility_rate": "Eligibility Rate %",
    "data_completeness_rate": "Data Completeness Rate %",
    "highest_governorate": "Top Governorate",
    "total_evaluated": "Total Records Covered",
    "total_licensed_capacity": "Total Licensed Capacity",
    "overall_occupancy_rate": "Overall Occupancy Rate %",
    "critical_high_incidents": "High and Critical Incidents",
}
